-- 批次18:俄语名回填·第二批(51macc 收割 25 对权威译名 + 标准术语词典,中文品名精确匹配)
-- 覆盖 name_ru 为空的 535 行(发动机件为主);幂等:WHERE slug + name_ru IS NULL
-- 词典:scripts/ru-dict-zh.json (68 条);额度消耗:10 次(196→186)
-- 预期影响:535 行;执行后 name_ru 覆盖率 75.4% → 79.9%
BEGIN;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'benz-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'benz-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'benz-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'benz-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'benz-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'benz-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'benz-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'benz-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'benz-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'benz-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'benz-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'benz-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'benz-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'caterpillar-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'caterpillar-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'caterpillar-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'caterpillar-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'caterpillar-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'caterpillar-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'caterpillar-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'caterpillar-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'caterpillar-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'caterpillar-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'caterpillar-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'caterpillar-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'caterpillar-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'cummins-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'cummins-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'cummins-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'cummins-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'cummins-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'cummins-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'cummins-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'cummins-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'cummins-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'cummins-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'cummins-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'cummins-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'cummins-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина клапана' WHERE slug = 'deda-inv-01222051-01222009' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина клапана 3.8*27.1*66.1*9.7' WHERE slug = 'deda-inv-080v04102-0155' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна' WHERE slug = 'deda-inv-080v90490-0028' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-1000034412' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина впускного клапана B-V6.5' WHERE slug = 'deda-inv-1000083620' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе' WHERE slug = 'deda-inv-1000089492' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-1000101611' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-1000101614' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора V52' WHERE slug = 'deda-inv-1000286997' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1000295925' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя' WHERE slug = 'deda-inv-1000315187' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-1000319666' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора 612640030025' WHERE slug = 'deda-inv-1000342181' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя' WHERE slug = 'deda-inv-1000351200' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе' WHERE slug = 'deda-inv-1000525595' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-1000562253' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя в сборе' WHERE slug = 'deda-inv-1000588658-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе' WHERE slug = 'deda-inv-1000595037' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе' WHERE slug = 'deda-inv-1000611912' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе' WHERE slug = 'deda-inv-1000612045' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник в сборе V90' WHERE slug = 'deda-inv-1000618448' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки B-V85' WHERE slug = 'deda-inv-1000622600' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина выпускного клапана B-V7.5' WHERE slug = 'deda-inv-1000645793' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1000646276-3604' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки B97' WHERE slug = 'deda-inv-1000697179' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна V8.4' WHERE slug = 'deda-inv-1000702305' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба в сборе V242' WHERE slug = 'deda-inv-1000720104' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба в сборе V248' WHERE slug = 'deda-inv-1000720183' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба в сборе' WHERE slug = 'deda-inv-1000721194' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора в сборе V40' WHERE slug = 'deda-inv-1000737069' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе B-52' WHERE slug = 'deda-inv-1000766904' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная сливная трубка B-230' WHERE slug = 'deda-inv-1000766908' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп B-17' WHERE slug = 'deda-inv-1000859627' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная сливная трубка в сборе B-V35' WHERE slug = 'deda-inv-1000875006' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коромысло клапана в сборе' WHERE slug = 'deda-inv-1000881645-612630050062-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе B-V46' WHERE slug = 'deda-inv-1000951036' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки B-V94.5' WHERE slug = 'deda-inv-1000951667' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора H10 B-V55' WHERE slug = 'deda-inv-1000952078' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки B-V99' WHERE slug = 'deda-inv-1000979668' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя B-67' WHERE slug = 'deda-inv-1000994093' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1001002008' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1001002012' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора' WHERE slug = 'deda-inv-1001040474' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки' WHERE slug = 'deda-inv-1001050008' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка V1.5' WHERE slug = 'deda-inv-1001063342' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки' WHERE slug = 'deda-inv-1001069227' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки в сборе' WHERE slug = 'deda-inv-1001112103' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе B-58' WHERE slug = 'deda-inv-1001133337' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе B-V64' WHERE slug = 'deda-inv-1001133338' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора V75' WHERE slug = 'deda-inv-1001156397' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора V50' WHERE slug = 'deda-inv-1001156424-86830' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора V45' WHERE slug = 'deda-inv-1001156566' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора' WHERE slug = 'deda-inv-1001156566-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора' WHERE slug = 'deda-inv-1001156730' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора' WHERE slug = 'deda-inv-1001156730-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка' WHERE slug = 'deda-inv-1001251573' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1001253380' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе' WHERE slug = 'deda-inv-1001273037' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра в сборе V541' WHERE slug = 'deda-inv-1001362234' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива B-V25' WHERE slug = 'deda-inv-1001385825-1000093593' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок B-V6.9' WHERE slug = 'deda-inv-1001397483' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе B57' WHERE slug = 'deda-inv-1001398765-130067' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки в сборе' WHERE slug = 'deda-inv-1001413516' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе V57' WHERE slug = 'deda-inv-1001421630-130068' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник B110' WHERE slug = 'deda-inv-1001424873' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе B-V35' WHERE slug = 'deda-inv-1001439412-62629-01612' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора' WHERE slug = 'deda-inv-1001474065' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ B160' WHERE slug = 'deda-inv-1001514985' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1001535062' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ B42' WHERE slug = 'deda-inv-1001549604' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1001626770' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок B-V10.4' WHERE slug = 'deda-inv-1001626772' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок B-V9.2' WHERE slug = 'deda-inv-1001626820' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1001641205' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора B-V57' WHERE slug = 'deda-inv-1001679009' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-1001696976' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки' WHERE slug = 'deda-inv-1001735292' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Крышка ГБЦ' WHERE slug = 'deda-inv-1001743939' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе' WHERE slug = 'deda-inv-1001757969' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец B32' WHERE slug = 'deda-inv-1001769469' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива' WHERE slug = 'deda-inv-1001771495' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива' WHERE slug = 'deda-inv-1001771497' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива' WHERE slug = 'deda-inv-1001771552' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-1001788294' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная сливная трубка в сборе B94' WHERE slug = 'deda-inv-1001817091' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-1001826421' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя V53' WHERE slug = 'deda-inv-1001853969' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок B-12.2' WHERE slug = 'deda-inv-1001902622' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки в сборе' WHERE slug = 'deda-inv-1001935459' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная сливная трубка в сборе' WHERE slug = 'deda-inv-1001977494' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе' WHERE slug = 'deda-inv-1001978332' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора B-V26.2' WHERE slug = 'deda-inv-1002025235' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе V-56' WHERE slug = 'deda-inv-1002139096' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе' WHERE slug = 'deda-inv-1002262629-39412-01612' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора' WHERE slug = 'deda-inv-1002267729' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора' WHERE slug = 'deda-inv-1002267730' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора в сборе' WHERE slug = 'deda-inv-1002267730-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-1002267731' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора в сборе' WHERE slug = 'deda-inv-1002267731-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-1002280048-v30-9' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора V13.6' WHERE slug = 'deda-inv-1002323427-4' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора B13.6' WHERE slug = 'deda-inv-1002328207-1' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора B13.6' WHERE slug = 'deda-inv-1002328713-1' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя V36.2' WHERE slug = 'deda-inv-1002516533-0714' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-1002553848' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя в сборе' WHERE slug = 'deda-inv-1002610714' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе' WHERE slug = 'deda-inv-1002843542' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-1002880645' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра V130' WHERE slug = 'deda-inv-1002916798' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра B142' WHERE slug = 'deda-inv-1003150194' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе V17.5' WHERE slug = 'deda-inv-1003202741' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора' WHERE slug = 'deda-inv-1003202741-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора V18.7' WHERE slug = 'deda-inv-1003202746' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора' WHERE slug = 'deda-inv-1003370376' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе B1100' WHERE slug = 'deda-inv-1003419259' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора' WHERE slug = 'deda-inv-1003420227' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе V54' WHERE slug = 'deda-inv-1003425772' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе V46' WHERE slug = 'deda-inv-1003425776' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе' WHERE slug = 'deda-inv-1003445981' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора V63.3' WHERE slug = 'deda-inv-1003445987' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора V48.9' WHERE slug = 'deda-inv-1003445989' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя в сборе V52-B' WHERE slug = 'deda-inv-1003467689' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя в сборе V74' WHERE slug = 'deda-inv-1003467691' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-1003493864' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора в сборе' WHERE slug = 'deda-inv-1003493864-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора' WHERE slug = 'deda-inv-1003542092' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора V-5' WHERE slug = 'deda-inv-1003549556-110005' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора V12.7' WHERE slug = 'deda-inv-1003570493' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-1003903463' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник B82.9' WHERE slug = 'deda-inv-1004016088' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора' WHERE slug = 'deda-inv-1004062124' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя' WHERE slug = 'deda-inv-1004090550' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя в сборе' WHERE slug = 'deda-inv-1004090556' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора в сборе' WHERE slug = 'deda-inv-1004143009' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе V36.2' WHERE slug = 'deda-inv-1004414406' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе' WHERE slug = 'deda-inv-1004501612-39412-62629' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная сливная трубка в сборе' WHERE slug = 'deda-inv-1004889443' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень B181' WHERE slug = 'deda-inv-1004961918' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя в сборе V98.9' WHERE slug = 'deda-inv-1005888297' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе' WHERE slug = 'deda-inv-1006101642' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе 156.5' WHERE slug = 'deda-inv-1006521226' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя V46.1' WHERE slug = 'deda-inv-1006644555' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора V7.9' WHERE slug = 'deda-inv-1006787555' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-1007053377' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора' WHERE slug = 'deda-inv-1008091531' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп 38CM' WHERE slug = 'deda-inv-12270444' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ' WHERE slug = 'deda-inv-13026701' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-13050495' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'deda-inv-200v03201-1143' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина клапана 3.831.7*70.97*8.5' WHERE slug = 'deda-inv-200v04102-0159' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-200v05703-5396' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-200v05805-5784' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-200v05805-5798' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна V2.63' WHERE slug = 'deda-inv-200v90490-0133' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Стопорное кольцо поршневого пальца' WHERE slug = 'deda-inv-200v90810-0038' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Уплотнительное кольцо гильзы цилиндра V15.27' WHERE slug = 'deda-inv-200v96501-0534' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика V1186.20' WHERE slug = 'deda-inv-201-01401-0327' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ' WHERE slug = 'deda-inv-201v03901-0402' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ' WHERE slug = 'deda-inv-201v03901-0403' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Натяжной ролик' WHERE slug = 'deda-inv-201v95800-7477' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-202v05805-0219' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора V29.8' WHERE slug = 'deda-inv-202v06303-5460' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора V4.11' WHERE slug = 'deda-inv-202v08901-0183' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-610800010055' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе' WHERE slug = 'deda-inv-610800010065' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе B-V38' WHERE slug = 'deda-inv-610800010371' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра V87' WHERE slug = 'deda-inv-610800010503' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна V8' WHERE slug = 'deda-inv-610800030004' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец V23.5' WHERE slug = 'deda-inv-610800030020' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Стопорное кольцо поршневого пальца' WHERE slug = 'deda-inv-610800030024' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна 11*1.25' WHERE slug = 'deda-inv-610800030025' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе V275' WHERE slug = 'deda-inv-610800030073' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна 12*1.5' WHERE slug = 'deda-inv-610800030075-pja0076' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень V131' WHERE slug = 'deda-inv-610800030080' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца V312' WHERE slug = 'deda-inv-610800030083-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ V184' WHERE slug = 'deda-inv-610800040023' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло выпускного клапана V32' WHERE slug = 'deda-inv-610800040108' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ V-40' WHERE slug = 'deda-inv-610800040229' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина клапана V3.5' WHERE slug = 'deda-inv-610800050030' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Клапанный мост' WHERE slug = 'deda-inv-610800050072' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коромысло клапана' WHERE slug = 'deda-inv-610800050153' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе' WHERE slug = 'deda-inv-610800060144' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе' WHERE slug = 'deda-inv-610800060284' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива V40' WHERE slug = 'deda-inv-610800081126' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива V41' WHERE slug = 'deda-inv-610800081128' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора V2.2' WHERE slug = 'deda-inv-610800110005-49556' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора V3' WHERE slug = 'deda-inv-610800110043-110324' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора V3.5' WHERE slug = 'deda-inv-610800110324-110043' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-610800110594' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя V85' WHERE slug = 'deda-inv-610800110787' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-610800111360' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя' WHERE slug = 'deda-inv-610800111363' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе B-V48' WHERE slug = 'deda-inv-610800130068' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе' WHERE slug = 'deda-inv-610800130089' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора B-29' WHERE slug = 'deda-inv-610800130154' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора в сборе B-V43.5' WHERE slug = 'deda-inv-610800130159' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора' WHERE slug = 'deda-inv-610800130197' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора B-V33' WHERE slug = 'deda-inv-610800130290' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора в сборе A146' WHERE slug = 'deda-inv-610800190352' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна B-V6.8' WHERE slug = 'deda-inv-611600030041' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'deda-inv-611600040004' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ V410' WHERE slug = 'deda-inv-611600040014' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник V100' WHERE slug = 'deda-inv-611600070123' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора' WHERE slug = 'deda-inv-611600110023' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика' WHERE slug = 'deda-inv-612600010575' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп' WHERE slug = 'deda-inv-612600010628' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика' WHERE slug = 'deda-inv-612600010956' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика' WHERE slug = 'deda-inv-612600011619' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика' WHERE slug = 'deda-inv-612600011701' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'deda-inv-612600030047' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Крышка ГБЦ WEVB' WHERE slug = 'deda-inv-612600040149' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ' WHERE slug = 'deda-inv-612600040355' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-612600040533' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ' WHERE slug = 'deda-inv-612600040646' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка' WHERE slug = 'deda-inv-612600040650' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'deda-inv-612600050025-41' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'deda-inv-612600050073' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Натяжной ролик' WHERE slug = 'deda-inv-612600060391' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе' WHERE slug = 'deda-inv-612600061288' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-612600070110' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-612600080349' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-612600080639' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-612600080640' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки' WHERE slug = 'deda-inv-612600080807' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра' WHERE slug = 'deda-inv-612600081294' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки EGR' WHERE slug = 'deda-inv-612600081329' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра в сборе 81334' WHERE slug = 'deda-inv-612600081333' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра' WHERE slug = 'deda-inv-612600081334' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра в сборе' WHERE slug = 'deda-inv-612600081493' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612600081880' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки' WHERE slug = 'deda-inv-612600081910' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубка подачи топлива в сборе' WHERE slug = 'deda-inv-612600082066' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки' WHERE slug = 'deda-inv-612600082308' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612600082651' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612600082652' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Задняя выпускная труба' WHERE slug = 'deda-inv-612600110178' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Задняя выпускная труба' WHERE slug = 'deda-inv-612600110835' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-612600110873' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора' WHERE slug = 'deda-inv-612600111113' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Задняя выпускная труба' WHERE slug = 'deda-inv-612600111280' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя' WHERE slug = 'deda-inv-6126001117233' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612600111969' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612600111991' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612600111992' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612600111993' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-612600112311' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя' WHERE slug = 'deda-inv-612600112705' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-612600112736' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Задняя выпускная труба EGR' WHERE slug = 'deda-inv-612600113067' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-612600113671' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя в сборе' WHERE slug = 'deda-inv-612600113779' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя' WHERE slug = 'deda-inv-612600113779-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-612600130292' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора EGR' WHERE slug = 'deda-inv-612600130316' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора EGR' WHERE slug = 'deda-inv-612600130316-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-612600130335' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-612600130457' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора' WHERE slug = 'deda-inv-612600130500' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-612600130533' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора' WHERE slug = 'deda-inv-612600130668' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-612600130788' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'deda-inv-612630010075' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика' WHERE slug = 'deda-inv-612630010199' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка' WHERE slug = 'deda-inv-612630010382' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник' WHERE slug = 'deda-inv-612630010425-1732112' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе F' WHERE slug = 'deda-inv-612630020017f' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе G' WHERE slug = 'deda-inv-612630020017g' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе H' WHERE slug = 'deda-inv-612630020017h' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе' WHERE slug = 'deda-inv-612630020017o' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе' WHERE slug = 'deda-inv-612630020017p' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе' WHERE slug = 'deda-inv-612630020017q' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'deda-inv-612630020024' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Стопорное кольцо поршневого пальца' WHERE slug = 'deda-inv-612630020029' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'deda-inv-612630020152' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'deda-inv-612630020244' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика P12' WHERE slug = 'deda-inv-612630030006' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Всасывающая трубка компрессора в сборе' WHERE slug = 'deda-inv-612630030033-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная водяная трубка компрессора' WHERE slug = 'deda-inv-612630030034' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора' WHERE slug = 'deda-inv-612630030037' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'deda-inv-612630030054' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Крышка ГБЦ' WHERE slug = 'deda-inv-612630040005' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ' WHERE slug = 'deda-inv-612630040006-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ' WHERE slug = 'deda-inv-612630040007' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ' WHERE slug = 'deda-inv-612630040007-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'deda-inv-612630040022' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Крышка ГБЦ' WHERE slug = 'deda-inv-612630040258' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ' WHERE slug = 'deda-inv-612630040265' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'deda-inv-612630050001' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'deda-inv-612630050002' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'deda-inv-612630050146' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса P12' WHERE slug = 'deda-inv-612630060034' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-612630060218' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-612630060351-608948' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-612630060355' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-612630060449' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-612630060478' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе' WHERE slug = 'deda-inv-612630061073' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе V1100' WHERE slug = 'deda-inv-612630061129' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-612630080004-1000101757' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-612630080005-1000101758' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612630080013' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612630080014' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612630080015' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612630080016' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра' WHERE slug = 'deda-inv-612630080087' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра' WHERE slug = 'deda-inv-612630080088' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612630080352' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612630110003' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612630110022' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612630110149' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора' WHERE slug = 'deda-inv-612630110716' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя' WHERE slug = 'deda-inv-612630110763' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора' WHERE slug = 'deda-inv-612630110942-1000580079' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора' WHERE slug = 'deda-inv-612630110983-0716' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора B-16' WHERE slug = 'deda-inv-612640030017' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса 1000615434' WHERE slug = 'deda-inv-612640060057' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок 10.5*6.5*4' WHERE slug = 'deda-inv-612640060246-7-1' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-612640080170' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-612640100001' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612640110379' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-612640110385' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Крышка ГБЦ' WHERE slug = 'deda-inv-612650040005' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ' WHERE slug = 'deda-inv-612650040011-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ' WHERE slug = 'deda-inv-612650040043' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник B-V35.6' WHERE slug = 'deda-inv-612700010118' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник B-V80' WHERE slug = 'deda-inv-612700010149' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора' WHERE slug = 'deda-inv-612700030022' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ V70' WHERE slug = 'deda-inv-612700040018' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Опорный блок' WHERE slug = 'deda-inv-612700110092' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба V97' WHERE slug = 'deda-inv-612700110109' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Натяжной ролик' WHERE slug = 'deda-inv-61400060161' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ' WHERE slug = 'deda-inv-614040021-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра' WHERE slug = 'deda-inv-614080739' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра' WHERE slug = 'deda-inv-614080740' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'deda-inv-61460060007' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'deda-inv-61500030077' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная трубка форсунки' WHERE slug = 'deda-inv-61500080095a' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'deda-inv-61560030055' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'deda-inv-61560050006' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Натяжной ролик' WHERE slug = 'deda-inv-61560060069' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора' WHERE slug = 'deda-inv-61560110210' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика' WHERE slug = 'deda-inv-615q0170003' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика' WHERE slug = 'deda-inv-615q0170037' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна' WHERE slug = 'deda-inv-61800030019-3' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе G' WHERE slug = 'deda-inv-61800030041g' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе H' WHERE slug = 'deda-inv-61800030041h' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатун в сборе K' WHERE slug = 'deda-inv-61800030041k' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник в сборе' WHERE slug = 'deda-inv-61800070051' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка EGR' WHERE slug = 'deda-inv-61800080062' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Картер маховика EGR' WHERE slug = 'deda-inv-az1557010012' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Патрубок водяного насоса' WHERE slug = 'deda-inv-d12-3' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Натяжной ролик' WHERE slug = 'deda-inv-d5010550335' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка турбокомпрессора' WHERE slug = 'deda-inv-dz91125540016' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляный щуп в сборе' WHERE slug = 'deda-inv-hg1242150021' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-vg1034080031' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-vg1034080032' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора' WHERE slug = 'deda-inv-vg1034130026' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяная трубка компрессора' WHERE slug = 'deda-inv-vg1034130028' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе' WHERE slug = 'deda-inv-vg1062060350' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе' WHERE slug = 'deda-inv-vg1062060351' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Задняя выпускная труба' WHERE slug = 'deda-inv-vg1095110037' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Задняя выпускная труба' WHERE slug = 'deda-inv-vg1095110049' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-vg1095110123' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-vg1096080321' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-vg1096080322' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-vg1099089098' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'deda-inv-vg1099089099' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'deda-inv-vg1246030010' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Болты шатуна' WHERE slug = 'deda-inv-vg1246030013' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка крышки ГБЦ' WHERE slug = 'deda-inv-vg1246040005' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коромысло клапана в сборе' WHERE slug = 'deda-inv-vg1246050008' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина впускного клапана 4.5*35*64.6*7.8' WHERE slug = 'deda-inv-vg1246050023' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина выпускного клапана 4.5*35*67*7.7' WHERE slug = 'deda-inv-vg1246050064' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник V52.2' WHERE slug = 'deda-inv-vg1246070011' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка V17.4' WHERE slug = 'deda-inv-vg1246080080' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка V14.9' WHERE slug = 'deda-inv-vg1246080082' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка V37.2' WHERE slug = 'deda-inv-vg1246080092' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка выпускного коллектора' WHERE slug = 'deda-inv-vg1246110028' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя V13.86' WHERE slug = 'deda-inv-vg1246110053' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Возвратная масляная трубка нагнетателя V17.48' WHERE slug = 'deda-inv-vg1246110055' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'deda-inv-vg1246110109' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Масляная трубка компрессора V14.32' WHERE slug = 'deda-inv-vg1246130006' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая водяная трубка компрессора в сборе V20.49' WHERE slug = 'deda-inv-vg1246130023' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра' WHERE slug = 'deda-inv-vg14080739a' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра' WHERE slug = 'deda-inv-vg14080740a' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Прокладка ГБЦ' WHERE slug = 'deda-inv-vg1500040065-2' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Крышка ГБЦ ENB' WHERE slug = 'deda-inv-vg1500040067' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Водяной насос в сборе' WHERE slug = 'deda-inv-vg1500060051' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Маслоприемник в сборе' WHERE slug = 'deda-inv-vg1500070082' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Натяжной ролик' WHERE slug = 'deda-inv-vg150060069' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'deda-inv-vg1540040008' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'deda-inv-vg1540050014' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'deda-inv-vg1540050015' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра PL420' WHERE slug = 'deda-inv-vg1540080311' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Подводящая масляная трубка нагнетателя EGR' WHERE slug = 'deda-inv-vg1540110204' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'deda-inv-vg1557080036' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Задняя выпускная труба EGR' WHERE slug = 'deda-inv-vg1557110012' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'deda-inv-vg1560040031' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Фильтроэлемент топливного фильтра 962/7' WHERE slug = 'deda-inv-vg1560080012' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'deda-inv-vg2600010990' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка V0.18' WHERE slug = 'deda-inv-vg9003080001' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка V0.25' WHERE slug = 'deda-inv-vg9003080002' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка V0.18' WHERE slug = 'deda-inv-vg9003080003' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка 0.3' WHERE slug = 'deda-inv-vg9003080004' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка V.3' WHERE slug = 'deda-inv-vg9003080005' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка V0.34' WHERE slug = 'deda-inv-vg9003080006' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка V0.35' WHERE slug = 'deda-inv-vg9003080007' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Композитная прокладка 0.45' WHERE slug = 'deda-inv-vg9003080008' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'deutz-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'deutz-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'deutz-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'deutz-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'deutz-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'deutz-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'deutz-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'deutz-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'deutz-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'deutz-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'deutz-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'deutz-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'deutz-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'doosan-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'doosan-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'doosan-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'doosan-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'doosan-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'doosan-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'doosan-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'doosan-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'doosan-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'doosan-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'doosan-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'doosan-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'doosan-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Тормозная камера' WHERE slug = 'gc-brake-chamber-t3d1my-w' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Трубопровод высокого давления' WHERE slug = 'high-pressure-fuel-line-022' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'hino-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'hino-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'hino-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'hino-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'hino-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'hino-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'hino-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'hino-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'hino-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'hino-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'hino-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'hino-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'hino-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'isuzu-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'isuzu-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'isuzu-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'isuzu-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'isuzu-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'isuzu-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'isuzu-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'isuzu-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'isuzu-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'isuzu-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'isuzu-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'isuzu-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'isuzu-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Тормозная камера' WHERE slug = 'kinglong-brake-chamber-wje4aa-3538000-w' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'komatsu-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'komatsu-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'komatsu-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'komatsu-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'komatsu-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'komatsu-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'komatsu-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'komatsu-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'komatsu-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'komatsu-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'komatsu-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'komatsu-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'komatsu-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка распределительного вала' WHERE slug = 'mazda-engine-camshaft-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Шатунные подшипники' WHERE slug = 'mazda-engine-connecting-rod-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Втулка верхней головки шатуна' WHERE slug = 'mazda-engine-connecting-rod-bush' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Гильза цилиндра' WHERE slug = 'mazda-engine-cylinder-liner' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускной клапан' WHERE slug = 'mazda-engine-exhaust-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Комплект прокладок двигателя' WHERE slug = 'mazda-engine-gasket-set' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Впускной клапан' WHERE slug = 'mazda-engine-intake-valve' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Коренные подшипники' WHERE slug = 'mazda-engine-main-bearing' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршень' WHERE slug = 'mazda-engine-piston' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневой палец' WHERE slug = 'mazda-engine-piston-pin' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Поршневые кольца' WHERE slug = 'mazda-engine-piston-ring' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Направляющая втулка клапана' WHERE slug = 'mazda-engine-valve-guide' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Седло клапана' WHERE slug = 'mazda-engine-valve-seat' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Выпускная труба' WHERE slug = 'pai-qi-guan-022' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Топливная трубка' WHERE slug = 'ran-you-guan-018' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Тормозная камера' WHERE slug = 'sinotruk-brake-chamber-14170300000d3-w' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Пружина клапана' WHERE slug = 'valve-spring-008' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Тормозная камера' WHERE slug = 'yutong-brake-chamber-wje4-24az-25300100-w' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Тормозная камера' WHERE slug = 'yutong-brake-chamber-y3519mpz-010-w' AND name_ru IS NULL;
UPDATE products SET name_ru = 'Тормозная камера' WHERE slug = 'yutong-brake-chamber-y35319092-010-w' AND name_ru IS NULL;
COMMIT;
