-- 第六批英文补全：2222 个件名 → name_en / description_en（幂等，可重复执行）
-- 匹配规则：name_zh 等于中文名、或中文名+空格+规格；规格后缀原样保留拼进英文名
UPDATE products p
SET name_en = t.en || substr(p.name_zh, length(t.zh) + 1),
    description_en = t.en || substr(p.name_zh, length(t.zh) + 1)
      || COALESCE(' for ' || p.truck_model, '')
      || '. DEDA stock item, OEM ' || COALESCE(p.oem_number, 'N/A') || '. Inquiry welcome.'
FROM (VALUES
('(4PK*1249)多挈带', '(4PK*1249) Poly-V Belt'),
('(4PK1251)多挈带', '(4PK1251) Poly-V Belt'),
('(80度）节温器', 'Thermostat (80℃)'),
('(MC11)曲轴前油封', '(MC11) Crankshaft Front Oil Seal'),
('(MC11)水泵密封垫', '(MC11) Water Pump Seal Gasket'),
('(MC11/13)曲轴后油封', '(MC11/13) Crankshaft Rear Oil Seal'),
('(MC11/13)油底壳垫', '(MC11/13) Oil Pan Gasket'),
('(天然气)排气门', '(Natural Gas) Exhaust Valve'),
('-0002低压滤芯', '-0002 Low Pressure Filter Element'),
('0013柴滤座', '0013 Diesel Filter Seat'),
('0042油滤支架', '0042 Oil Filter Bracket'),
('0047四配套', '0047 Four-Piece Kit'),
('0058轴', '0058 Shaft'),
('010四配套', '010 Four-Piece Kit'),
('0161涨紧轮总成', '0161 Tensioner Assembly'),
('0302中冷器管', '0302 Intercooler Pipe'),
('0311柴滤座', '0311 Diesel Filter Seat'),
('034四配套', '034 Four-Piece Kit'),
('0458盖板', '0458 Cover Plate'),
('047空压机缸盖', '047 Air Compressor Cylinder Head'),
('050053齿轮固定螺丝包', '050053 Gear Fixing Screw Kit'),
('0756冷盖法兰', '0756 Coolant Cover Flange'),
('0756冷盖法兰垫片', '0756 Coolant Cover Flange Gasket'),
('0756冷盖管接头', '0756 Coolant Cover Pipe Joint'),
('09款金王子涨紧轮支架', '09 Golden Prince Tensioner Bracket'),
('1', '1'),
('1.5KW 发电机', '1.5KW Alternator'),
('1.5KW发电机', '1.5KW Alternator'),
('1.7米套管', '1.7m Sleeve Pipe'),
('10*100六角头螺栓', '10*100 Hex Head Bolt'),
('10*105法兰面六角头螺栓', '10*105 Hex Flange Bolt'),
('10*10圆柱销', '10*10 Dowel Pin'),
('10*110六角头螺栓', '10*110 Hex Head Bolt'),
('10*110法兰面六角头螺栓', '10*110 Hex Flange Bolt'),
('10*25六角头螺栓', '10*25 Hex Head Bolt'),
('10*25双头螺栓', '10*25 Stud Bolt'),
('10*28六角法兰面螺栓', '10*28 Hex Flange Bolt'),
('10*30六角法兰面螺栓', '10*30 Hex Flange Bolt'),
('10*30双头螺栓', '10*30 Stud Bolt'),
('10*30法兰面螺栓', '10*30 Flange Bolt'),
('10*40内六角螺丝', '10*40 Socket Screw'),
('10*40双头螺栓', '10*40 Stud Bolt'),
('10*45六角头螺栓', '10*45 Hex Head Bolt'),
('10*60六角头螺栓', '10*60 Hex Head Bolt'),
('10*60双头螺栓', '10*60 Stud Bolt'),
('10*65六角头螺栓', '10*65 Hex Head Bolt'),
('10*65内六角螺栓', '10*65 Socket Bolt'),
('10*70内六角', '10*70 Socket Screw'),
('10*75带齿法兰面螺栓', '10*75 Toothed Flange Bolt'),
('10*80法兰面六角头螺栓', '10*80 Hex Flange Bolt'),
('10*85六角头', '10*85 Hex Head'),
('10*90带齿法兰面螺栓', '10*90 Toothed Flange Bolt'),
('10*90排气管螺栓', '10*90 Exhaust Pipe Bolt'),
('10*90法兰面六角头', '10*90 Hex Flange Head'),
('10*95法兰面六角头螺栓', '10*95 Hex Flange Bolt'),
('10-19水管卡子', '10-19 Water Pipe Clamp'),
('10.9-8*100法兰面六角头螺栓', '10.9-8*100 Hex Flange Bolt'),
('10.9六角头螺栓', 'Hex Head Bolt Grade 10.9'),
('10.9六角法兰面螺栓', 'Hex Flange Bolt Grade 10.9'),
('10.9内六角螺栓10*80', 'Socket Bolt Gr.10.9 10*80'),
('10.9级六角头螺栓', 'Hex Head Bolt Grade 10.9'),
('10175盖板垫片', '10175 Cover Plate Gasket'),
('1075多挈带', '1075 Poly-V Belt'),
('10E摇臂总成', '10E Rocker Arm Assembly'),
('10PK1887多挈带', '10PK1887 Poly-V Belt'),
('10PK涨紧轮', '10PK Tensioner'),
('10PK皮带轮', '10PK Pulley'),
('10PK自动涨紧轮', '10PK Auto Tensioner'),
('10升天然气活塞环', '10L Natural Gas Piston Ring'),
('10槽平槽惰轮120004', '10-Groove Flat Idler Pulley 120004'),
('10槽惰轮', '10-Groove Idler Pulley'),
('119.5机油尺套管', '119.5 Dipstick Sleeve'),
('11叶风扇叶', '11-Blade Fan Blade'),
('12*30双头螺栓', '12*30 Stud Bolt'),
('12*35法兰面六角头螺栓', '12*35 Hex Flange Bolt'),
('12*35联轴器螺栓', '12*35 Coupling Bolt'),
('12*45双头螺栓', '12*45 Stud Bolt'),
('12*50内六角螺栓', '12*50 Socket Bolt'),
('12*50联轴器螺栓', '12*50 Coupling Bolt'),
('12*90法兰面六角头螺栓', '12*90 Hex Flange Bolt'),
('12100法兰面六角头螺栓', '12100 Hex Flange Bolt'),
('12PK自动张紧轮', '12PK Auto Tensioner'),
('12升火花塞衬套', '12L Spark Plug Bushing'),
('14*50带肩飞轮螺栓', '14*50 Shoulder Flywheel Bolt'),
('14*55传动轴螺丝', '14*55 Drive Shaft Screw'),
('14*75飞轮螺栓', '14*75 Flywheel Bolt'),
('14*90法兰面六角头螺丝', '14*90 Hex Flange Screw'),
('1422堵口', '1422 Plug'),
('14PK*1134多挈带', '14PK*1134 Poly-V Belt'),
('14PK水泵泵头', '14PK Water Pump Head'),
('14传动轴螺母', '14 Drive Shaft Nut'),
('15.3*2.4密封圈', '15.3*2.4 Seal Ring'),
('15335盖（新式）', '15335 Cover (New Type)'),
('1540W交流发电机', '1540W Alternator'),
('15PK惰轮', '15PK Idler Pulley'),
('161涨紧轮固定螺栓', '161 Tensioner Fixing Bolt'),
('168空压机修理包', '168 Air Compressor Repair Kit'),
('168空压机活塞', '168 Air Compressor Piston'),
('168空压机缸体', '168 Air Compressor Cylinder Block'),
('168空压机缸盖总成', '168 Air Compressor Cylinder Head Assembly'),
('17水堵', '17 Water Core Plug'),
('18L齿轮油', '18L Gear Oil'),
('192309轴承', '192309 Bearing'),
('1KW发电机', '1KW Alternator'),
('2064机油尺套管', '2064 Dipstick Sleeve'),
('20水堵', '20 Water Core Plug'),
('22*3密封圈', '22*3 Seal Ring'),
('226B冷却液连接胶管', '226B Coolant Rubber Hose'),
('226B加机油口盖', '226B Oil Fill Cap'),
('226B曲轴前油封', '226B Crankshaft Front Oil Seal'),
('226B曲轴后油封', '226B Crankshaft Rear Oil Seal'),
('226B气缸盖罩', '226B Cylinder Head Cover'),
('226B气门推杆', '226B Valve Push Rod'),
('226B汽缸垫', '226B Cylinder Head Gasket'),
('226B活塞销卡簧', '226B Piston Pin Circlip'),
('226B缸盖螺栓', '226B Cylinder Head Bolt'),
('226B缸盖螺栓（全长170）', '226B Head Bolt (170mm)'),
('226B罩盖垫', '226B Cover Gasket'),
('226B连杆螺栓', '226B Connecting Rod Bolt'),
('226B阻水圈', '226B Water Seal Ring'),
('26转向泵空芯螺栓', '26 Steering Pump Hollow Bolt'),
('28*3密封圈', '28*3 Seal Ring'),
('2W发电机', '2W Alternator'),
('3055垫片', '3055 Washer'),
('3305轴承', '3305 Bearing'),
('35*3密封圈', '35*3 Seal Ring'),
('36D排气管', '36D Exhaust Pipe'),
('375高压油泵', '375 High Pressure Pump'),
('430推式离合器片', '430 Push-Type Clutch Disc'),
('430飞轮', '430 Flywheel'),
('4L曼机油', '4L MAN Engine Oil'),
('5*45内六角螺栓', '5*45 Socket Bolt'),
('50-70水管卡子', '50-70 Water Pipe Clamp'),
('50水堵(铜)', '50 Copper Core Plug'),
('590环形风扇', '590 Ring Fan'),
('590环形风扇叶', '590 Ring Fan Blade'),
('596环型风扇叶子', '596 Ring Fan Blade'),
('6*20法兰面六角头', '6*20 Hex Flange Head'),
('6*30内六角螺栓', '6*30 Socket Bolt'),
('6*45六角头螺栓', '6*45 Hex Head Bolt'),
('6*45内六角螺栓', '6*45 Socket Bolt'),
('6*50双头螺栓', '6*50 Stud Bolt'),
('6*65内六角螺栓', '6*65 Socket Bolt'),
('60*4密封圈', '60*4 Seal Ring'),
('615加粗连杆螺栓（不三包)', '615 Heavy-Duty Connecting Rod Bolt (No Warranty)'),
('615安全阀', '615 Safety Valve'),
('615摇臂座', '615 Rocker Arm Seat'),
('615标准连杆螺栓（不三包）', '615 Standard Connecting Rod Bolt (No Warranty)'),
('615气缸盖主螺栓', '615 Cylinder Head Main Bolt'),
('615气门弹簧', '615 Valve Spring'),
('615空压机阀板总成', '615 Air Compressor Valve Plate Assembly'),
('615进气管垫片', '615 Intake Pipe Gasket'),
('618/P10安全阀', '618/P10 Safety Valve'),
('618中缸螺丝', '618 Mid-Cylinder Screw'),
('618全车垫', '618 Complete Gasket Kit'),
('618冷却液连接胶管', '618 Coolant Rubber Hose'),
('618出气管接头', '618 Air Outlet Joint'),
('618出水管', '618 Water Outlet Pipe'),
('618出水管螺栓', '618 Water Outlet Bolt'),
('618加粗连杆螺栓(PJA002）', '618 Heavy-Duty Connecting Rod Bolt (PJA002)'),
('618发动机密封圈修理包', '618 Engine Seal Repair Kit'),
('618发电机支架螺丝', '618 Alternator Bracket Screw'),
('618喷油泵齿轮', '618 Injection Pump Gear'),
('618四配套', '618 Four-Piece Kit'),
('618四配套（不三包）', '618 Four-Piece Kit (No Warranty)'),
('618护风带', '618 Fan Shroud Strip'),
('618曲轴', '618 Crankshaft'),
('618机油冷却器盖螺丝', '618 Oil Cooler Cover Screw'),
('618机油泵', '618 Oil Pump'),
('618柴油滤芯托架', '618 Diesel Filter Element Bracket'),
('618标准连杆螺丝（不三包）', '618 Standard Connecting Rod Bolt (No Warranty)'),
('618气缸套', '618 Cylinder Liner'),
('618水泵体垫片', '618 Water Pump Body Gasket'),
('618水泵垫', '618 Water Pump Gasket'),
('618水泵销子', '618 Water Pump Pin'),
('618水泵风扇托架螺栓', '618 Water Pump Fan Bracket Bolt'),
('618汽缸体', '618 Cylinder Block'),
('618油气分离器', '618 Oil-Gas Separator'),
('618活塞环', '618 Piston Ring'),
('618涨紧轮螺丝', '618 Tensioner Screw'),
('618空压机密封圈', '618 Air Compressor Seal Ring'),
('618空压机阀板总成', '618 Air Compressor Valve Plate Assembly'),
('618进气管螺丝', '618 Intake Pipe Screw'),
('618连杆总成', '618 Connecting Rod Assembly'),
('618连杆瓦', '618 Connecting Rod Bearing'),
('640环形风扇', '640 Ring Fan'),
('640环形风扇叶子', '640 Ring Fan Blade'),
('67水泵总成', '67 Water Pump Assembly'),
('67进气门', '67 Intake Valve'),
('67风扇轮毂', '67 Fan Hub'),
('68A活塞', '68A Piston'),
('68B活塞', '68B Piston'),
('6槽平槽惰轮', '6-Groove Flat Idler Pulley'),
('71°工程节温器总成', '71℃ Construction Machinery Thermostat Assembly'),
('783多锲带（三元乙丙）', '783 Poly-V Belt (EPDM)'),
('783多锲带（碌丁胶）', '783 Poly-V Belt (Rubber)'),
('8*105内六角螺栓', '8*105 Socket Bolt'),
('8*110内六角螺栓', '8*110 Socket Bolt'),
('8*110法兰面六角头螺栓', '8*110 Hex Flange Bolt'),
('8*135法兰面六角头螺栓', '8*135 Hex Flange Bolt'),
('8*20六角头螺栓', '8*20 Hex Head Bolt'),
('8*25六角法兰面螺栓', '8*25 Hex Flange Bolt'),
('8*25内六角螺栓（10.9）', '8*25 Socket Bolt (Gr.10.9)'),
('8*25法兰面六角头螺栓', '8*25 Hex Flange Bolt'),
('8*30六角头螺栓', '8*30 Hex Head Bolt'),
('8*50法兰面六角头', '8*50 Hex Flange Head'),
('8*55带齿法兰面六角头', '8*55 Toothed Hex Flange Head'),
('8*60六角头螺栓', '8*60 Hex Head Bolt'),
('8*80内六角螺栓', '8*80 Socket Bolt'),
('8.8级六角头螺栓', 'Hex Head Bolt Grade 8.8'),
('8.8级六角头螺栓Q150B10100', 'Hex Head Bolt Gr.8.8 Q150B10100'),
('80041柴滤支架螺栓', '80041 Diesel Filter Bracket Bolt'),
('80554柴滤座', '80554 Diesel Filter Seat'),
('81334柴滤座', '81334 Diesel Filter Seat'),
('83-95度节温器芯', '83-95℃ Thermostat Element'),
('83B机油冷却器盖螺丝包', '83B Oil Cooler Cover Screw Kit'),
('83°节温器芯', '83℃ Thermostat Element'),
('A7发电机', 'A7 Alternator'),
('A类水管接头', 'Type-A Water Pipe Joint'),
('CNG空压机管接头', 'CNG Air Compressor Pipe Joint'),
('D10ECU螺栓', 'D10 ECU Bolt'),
('D10G增压器进油管', 'D10G Turbo Oil Feed Pipe'),
('D10六角螺塞', 'D10 Hex Plug'),
('D10共轨支架总成', 'D10 Common Rail Bracket Assembly'),
('D10出水管节温器固定螺栓', 'D10 Thermostat Fixing Bolt'),
('D10发电机螺栓包', 'D10 Alternator Bolt Kit'),
('D10吊环接块', 'D10 Lifting Eye Joint Block'),
('D10喷油器喷油泵固定螺栓', 'D10 Injector-Pump Fixing Bolt'),
('D10喷油器密封圈', 'D10 Injector Seal Ring'),
('D10增压器进油管总成', 'D10 Turbo Oil Feed Pipe Assembly'),
('D10安全阀总成', 'D10 Safety Valve Assembly'),
('D10柴滤支架螺栓', 'D10 Diesel Filter Bracket Bolt'),
('D10涨紧轮螺丝（三孔）', 'D10 Tensioner Screw (3-Hole)'),
('D10涨紧轮螺丝（四孔）', 'D10 Tensioner Screw (4-Hole)'),
('D10空滤支架', 'D10 Air Filter Bracket'),
('D10线束支架', 'D10 Wiring Harness Bracket'),
('D10进气管固定螺栓', 'D10 Intake Pipe Fixing Bolt'),
('D10高压油管', 'D10 High Pressure Pipe'),
('D10高压油管支撑架（一）', 'D10 HP Pipe Support Bracket (1)'),
('D10高压油管支撑架（三）', 'D10 HP Pipe Support Bracket (3)'),
('D10高压油管支撑架（二）', 'D10 HP Pipe Support Bracket (2)'),
('D10齿轮室前端盖', 'D10 Gear Housing Front Cover'),
('D10齿轮室端盖固定螺栓', 'D10 Gear Housing Cover Bolt'),
('D12主轴承螺栓', 'D12 Main Bearing Bolt'),
('D12共轨喷油泵回油管', 'D12 Common Rail Injection Pump Return Pipe'),
('D12共轨油泵机油进油管总成', 'D12 Common Rail Pump Oil Inlet Pipe Assembly'),
('D12共轨组件回油管', 'D12 Common Rail Module Return Pipe'),
('D12双级机油泵吸管', 'D12 Two-Stage Oil Pump Suction Pipe'),
('D12喷油器压紧块', 'D12 Injector Clamping Block'),
('D12喷油泵法兰', 'D12 Injection Pump Flange'),
('D12喷油泵齿轮', 'D12 Injection Pump Gear'),
('D12圆柱销修理包', 'D12 Dowel Pin Repair Kit'),
('D12增压器回油管', 'D12 Turbo Oil Return Pipe'),
('D12增压器螺栓10*30', 'D12 Turbo Bolt 10*30'),
('D12增压器螺栓10*45', 'D12 Turbo Bolt 10*45'),
('D12增压器进油管', 'D12 Turbo Oil Feed Pipe'),
('D12排气管垫', 'D12 Exhaust Gasket'),
('D12排气管密封环', 'D12 Exhaust Pipe Seal Ring'),
('D12摇臂轴', 'D12 Rocker Arm Shaft'),
('D12曲轴前油封', 'D12 Crankshaft Front Oil Seal'),
('D12曲轴前齿轮', 'D12 Crankshaft Front Gear'),
('D12曲轴后齿轮', 'D12 Crankshaft Rear Gear'),
('D12机油加油管座', 'D12 Oil Fill Pipe Seat'),
('D12机油喷嘴', 'D12 Oil Nozzle'),
('D12气缸盖', 'D12 Cylinder Head'),
('D12气门摇臂总成', 'D12 Valve Rocker Arm Assembly'),
('D12油泵机油进油管', 'D12 Oil Pump Oil Inlet Pipe'),
('D12油泵辅助支架', 'D12 Oil Pump Auxiliary Bracket'),
('D12活塞肖挡圈', 'D12 Piston Pin Circlip'),
('D12燃油管', 'D12 Fuel Pipe'),
('D12皮带轮螺栓', 'D12 Pulley Bolt'),
('D12硅油减震器挡板', 'D12 Viscous Damper Baffle'),
('D12空压机出水管接头', 'D12 Air Compressor Water Outlet Joint'),
('D12空压机润滑油管', 'D12 Air Compressor Lube Oil Pipe'),
('D12空压机螺母', 'D12 Air Compressor Nut'),
('D12空压机进水管总成', 'D12 Air Compressor Water Inlet Pipe Assembly'),
('D12空压机进水管接头', 'D12 Air Compressor Water Inlet Joint'),
('D12空压机齿轮', 'D12 Air Compressor Gear'),
('D12空气管', 'D12 Air Pipe'),
('D12粗滤固定支架', 'D12 Primary Filter Fixing Bracket'),
('D12精滤固定支架', 'D12 Fine Filter Fixing Bracket'),
('D12缸盖主螺栓', 'D12 Cylinder Head Main Bolt'),
('D12缸盖副螺栓', 'D12 Cylinder Head Auxiliary Bolt'),
('D12缸盖组装明细', 'D12 Cylinder Head Assembly List'),
('D12缸盖罩衬垫', 'D12 Cylinder Head Cover Gasket'),
('D12节温器芯', 'D12 Thermostat Element'),
('D12进气管垫', 'D12 Intake Pipe Gasket'),
('D12集滤器', 'D12 Oil Strainer'),
('DPF垫片275*300*1.8', 'DPF Gasket 275*300*1.8'),
('DPM回水管', 'DPM Water Return Pipe'),
('DPM回水管组件', 'DPM Water Return Pipe Module'),
('DPM回水管组件（P10H/国六）', 'DPM Water Return Pipe Module (P10H/China-VI)'),
('DPM进水管', 'DPM Water Inlet Pipe'),
('DPM进水管组件', 'DPM Water Inlet Pipe Module'),
('DPM进水管组件（P10H/国六）', 'DPM Water Inlet Pipe Module (P10H/China-VI)'),
('ECU总成', 'ECU Assembly'),
('ECU护罩', 'ECU Cover'),
('ECU控制总成', 'ECU Control Assembly'),
('ECU支撑块', 'ECU Support Block'),
('ECU支撑板', 'ECU Support Plate'),
('ECU支架', 'ECU Bracket'),
('ECU线束', 'ECU Wiring Harness'),
('ECU防护罩', 'ECU Protective Cover'),
('EGR冷却出水管', 'EGR Cooler Water Outlet Pipe'),
('EGR冷却出水管总成', 'EGR Cooling Outlet Pipe Assembly'),
('EGR冷却器出水管', 'EGR Cooler Water Outlet Pipe'),
('EGR冷却器出水管总成', 'EGR Cooler Water Outlet Pipe Assembly'),
('EGR冷却器壳', 'EGR Cooler Housing'),
('EGR冷却器水管', 'EGR Cooler Water Pipe'),
('EGR冷却器螺栓', 'EGR Cooler Bolt'),
('EGR冷却器进水管', 'EGR Cooler Water Inlet Pipe'),
('EGR冷却器阀连接法兰', 'EGR Cooler Valve Connecting Flange'),
('EGR冷却器阀连接法兰垫片', 'EGR Cooler Valve Flange Gasket'),
('EGR冷却水管', 'EGR Cooling Water Pipe'),
('EGR冷却水软管', 'EGR Cooling Water Hose'),
('EGR冷却管总成', 'EGR Cooling Pipe Assembly'),
('EGR出气管', 'EGR Outlet Pipe'),
('EGR出气管总成', 'EGR Outlet Pipe Assembly'),
('EGR出气胶管', 'EGR Outlet Rubber Hose'),
('EGR出水管总成', 'EGR Water Outlet Pipe Assembly'),
('EGR出水连接弯管', 'EGR Water Outlet Connecting Elbow'),
('EGR单向阀总成', 'EGR Check Valve Assembly'),
('EGR发电机', 'EGR Alternator'),
('EGR垫片', 'EGR Gasket'),
('EGR废气排气管', 'EGR Exhaust Pipe'),
('EGR废气管法兰垫', 'EGR Waste Pipe Flange Gasket'),
('EGR总成', 'EGR Assembly'),
('EGR总成支架', 'EGR Assembly Bracket'),
('EGR悬臂总成', 'EGR Cantilever Assembly'),
('EGR挡板', 'EGR Baffle Plate'),
('EGR排气管', 'EGR Exhaust Pipe'),
('EGR排气管法兰垫', 'EGR Exhaust Pipe Flange Gasket'),
('EGR排气阀门总成', 'EGR Exhaust Valve Assembly'),
('EGR气缸', 'EGR Cylinder'),
('EGR水管垫片', 'EGR Water Pipe Gasket'),
('EGR电磁阀', 'EGR Solenoid Valve'),
('EGR缸盖罩衬垫', 'EGR Cylinder Head Cover Gasket'),
('EGR输油泵', 'EGR Fuel Feed Pump'),
('EGR进气管', 'EGR Intake Pipe'),
('EGR进气管垫片', 'EGR Intake Pipe Gasket'),
('EGR进气管（一）', 'EGR Intake Pipe (1)'),
('EGR进气管（二）', 'EGR Intake Pipe (2)'),
('EGR进水管隔热罩', 'EGR Water Inlet Pipe Heat Shield'),
('EGR阀水管总成', 'EGR Valve Water Pipe Assembly'),
('ERG冷却水管', 'EGR Cooling Water Pipe'),
('EVB压板', 'EVB Press Plate'),
('EVB排气门摇臂', 'EVB Exhaust Valve Rocker Arm'),
('EVB摇臂座螺栓', 'EVB Rocker Seat Bolt'),
('EVB支撑臂总成', 'EVB Support Arm Assembly'),
('EVB支架总成', 'EVB Bracket Assembly'),
('EVB支架总成（拆机)', 'EVB Bracket Assembly (Dismantled)'),
('EVB气门桥', 'EVB Valve Bridge'),
('EVB汽缸体', 'EVB Cylinder Block'),
('EVB润滑油管总成', 'EVB Lube Oil Pipe Assembly'),
('EVB调整螺钉', 'EVB Adjusting Screw'),
('EVB调整螺钉螺母', 'EVB Adjusting Screw Nut'),
('EVB调节螺栓固定支架', 'EVB Adjusting Bolt Fixing Bracket'),
('EVB调节螺母', 'EVB Adjusting Nut'),
('EVB调节螺钉', 'EVB Adjusting Screw'),
('EVB进油管总成', 'EVB Oil Inlet Pipe Assembly'),
('F3000前大灯总成', 'F3000 Headlight Assembly'),
('FEF罩盖垫', 'FEF Cover Gasket'),
('FP9喷油泵托架', 'FP9 Injection Pump Bracket'),
('H09/10飞轮壳法兰面螺栓', 'H09/10 Flywheel Housing Flange Bolt'),
('H09机油尺', 'H09 Oil Dipstick'),
('H09机油尺总成', 'H09 Oil Dipstick Assembly'),
('H09机油尺管', 'H09 Dipstick Tube'),
('H09机油尺管总成', 'H09 Dipstick Tube Assembly'),
('H09飞轮螺栓', 'H09 Flywheel Bolt'),
('H10.5增压器进油管总成', 'H10.5 Turbo Oil Feed Pipe Assembly'),
('H10.5增压器隔热罩', 'H10.5 Turbo Heat Shield'),
('H10.5护风圈支架', 'H10.5 Fan Shroud Bracket'),
('H10.5暖风接头', 'H10.5 Heater Joint'),
('H10.5机油喷嘴总成', 'H10.5 Oil Nozzle Assembly'),
('H10.5机油尺', 'H10.5 Oil Dipstick'),
('H10.5机油尺套管总成', 'H10.5 Dipstick Sleeve Assembly'),
('H10.5水管接头', 'H10.5 Water Pipe Joint'),
('H10.5空压机出气接头', 'H10.5 Air Compressor Air Outlet Joint'),
('H10.5空压机气管接头', 'H10.5 Air Compressor Air Pipe Joint'),
('H10.5管接头组件', 'H10.5 Pipe Joint Assembly'),
('H10.5缸体接头', 'H10.5 Cylinder Block Joint'),
('H10.5阻水圈（红色）', 'H10.5 Water Seal Ring (Red)'),
('H10.5阻水圈（蓝色）', 'H10.5 Water Seal Ring (Blue)'),
('H10.5阻水圈（黑）', 'H10.5 Water Seal Ring (Black)'),
('H10.5集滤器支架', 'H10.5 Oil Strainer Bracket'),
('H10.5飞轮螺栓', 'H10.5 Flywheel Bolt'),
('H10/P7球面垫圈', 'H10/P7 Spherical Washer'),
('H10/节温器支撑块', 'H10/Thermostat Support Block'),
('H10NG增压器回油管', 'H10NG Turbo Oil Return Pipe'),
('H10NG增压器进油管', 'H10NG Turbo Oil Feed Pipe'),
('H10中间齿轮总成', 'H10 Idler Gear Assembly'),
('H10中间齿轮组件', 'H10 Idler Gear Module'),
('H10中间齿轮轴', 'H10 Idler Gear Shaft'),
('H10出水管垫片', 'H10 Water Outlet Gasket'),
('H10出水管盖板', 'H10 Water Outlet Cover Plate'),
('H10出水管管接头', 'H10 Water Outlet Pipe Joint'),
('H10出水管组件', 'H10 Water Outlet Pipe Module'),
('H10压气机进气管', 'H10 Compressor Intake Pipe'),
('H10后排气支管', 'H10 Rear Exhaust Manifold'),
('H10喷油器压板', 'H10 Injector Press Plate'),
('H10喷油器压板固定螺栓', 'H10 Injector Plate Fixing Bolt'),
('H10喷油泵润滑油管', 'H10 Injection Pump Lube Oil Pipe'),
('H10喷油泵齿轮', 'H10 Injection Pump Gear'),
('H10圆柱销修理包', 'H10 Dowel Pin Repair Kit'),
('H10增压器隔热罩', 'H10 Turbo Heat Shield'),
('H10排气管垫', 'H10 Exhaust Gasket'),
('H10排气管螺栓', 'H10 Exhaust Pipe Bolt'),
('H10排气管隔热罩', 'H10 Exhaust Heat Shield'),
('H10排气管（前）', 'H10 Exhaust Pipe (Front)'),
('H10排气门弹簧', 'H10 Exhaust Valve Spring'),
('H10支撑块', 'H10 Support Block'),
('H10放气管总成', 'H10 Air Bleed Pipe Assembly'),
('H10曲轴前油封', 'H10 Crankshaft Front Oil Seal'),
('H10曲轴后油封', 'H10 Crankshaft Rear Oil Seal'),
('H10曲轴齿轮', 'H10 Crankshaft Gear'),
('H10机油冷却器盖垫片', 'H10 Oil Cooler Cover Gasket'),
('H10机油尺', 'H10 Oil Dipstick'),
('H10机油尺下组件', 'H10 Dipstick Lower Module'),
('H10机油尺管', 'H10 Dipstick Tube'),
('H10机油尺管总成', 'H10 Dipstick Tube Assembly'),
('H10机油滤清器滤芯', 'H10 Oil Filter Element'),
('H10机滤芯', 'H10 Oil Filter Element'),
('H10模块支撑快', 'H10 Module Support Block'),
('H10气缸套', 'H10 Cylinder Liner'),
('H10气缸盖罩衬垫', 'H10 Cylinder Head Cover Gasket'),
('H10气门导管', 'H10 Valve Guide'),
('H10气门弹簧上座', 'H10 Valve Spring Upper Seat'),
('H10水泵总成', 'H10 Water Pump Assembly'),
('H10水泵接头', 'H10 Water Pump Joint'),
('H10水管接头', 'H10 Water Pipe Joint'),
('H10汽缸垫', 'H10 Cylinder Head Gasket'),
('H10油尺堵', 'H10 Dipstick Plug'),
('H10油气分离器橡胶管', 'H10 Oil-Gas Separator Rubber Pipe'),
('H10火花塞衬套密封圈', 'H10 Spark Plug Bushing Seal Ring'),
('H10燃油回油管总成', 'H10 Fuel Return Pipe Assembly'),
('H10燃油粗滤芯', 'H10 Fuel Primary Filter Element'),
('H10燃油精滤芯', 'H10 Fuel Fine Filter Element'),
('H10燃油进油管', 'H10 Fuel Feed Pipe'),
('H10燃油进油管总成', 'H10 Fuel Feed Pipe Assembly'),
('H10皮带轮', 'H10 Pulley'),
('H10空压机回水管总成', 'H10 Air Compressor Return Water Pipe Assembly'),
('H10空压机垫片', 'H10 Air Compressor Gasket'),
('H10空压机水管卡箍', 'H10 Air Compressor Water Hose Clamp'),
('H10空压机管接头', 'H10 Air Compressor Pipe Joint'),
('H10空压机管接头（V21）', 'H10 Air Compressor Pipe Joint (V21)'),
('H10空压机进气管', 'H10 Air Compressor Intake Pipe'),
('H10空压机进水管总成(带螺母)', 'H10 Air Compressor Water Inlet Pipe Assembly (with Nut)'),
('H10空压机齿轮', 'H10 Air Compressor Gear'),
('H10空调压缩支架', 'H10 AC Compressor Bracket'),
('H10空调压缩机支架', 'H10 AC Compressor Bracket'),
('H10管接头组件', 'H10 Pipe Joint Assembly'),
('H10缸盖出水管定位套', 'H10 Head Water Outlet Locating Sleeve'),
('H10自动张紧轮', 'H10 Auto Tensioner'),
('H10节温器支撑块', 'H10 Thermostat Support Block'),
('H10进气接管', 'H10 Intake Connection'),
('H10进气门弹簧', 'H10 Intake Valve Spring'),
('H10进气门挺住总成', 'H10 Intake Valve Tappet Assembly'),
('H10集滤器', 'H10 Oil Strainer'),
('H10集滤器支架', 'H10 Oil Strainer Bracket'),
('H10飞轮螺栓', 'H10 Flywheel Bolt'),
('H1凸轮轴止推片', 'H1 Camshaft Thrust Washer'),
('H1卡套', 'H1 Ferrule Sleeve'),
('H1卡箍', 'H1 Hose Clamp'),
('H1双管接头', 'H1 Double Pipe Joint'),
('H1喷油器衬套', 'H1 Injector Bushing'),
('H1回油管接头', 'H1 Oil Return Joint'),
('H1密封圈（B-V1）', 'H1 Seal Ring (B-V1)'),
('H1密封圈（B-V2.3）', 'H1 Seal Ring (B-V2.3)'),
('H1密封圈（B-V3）', 'H1 Seal Ring (B-V3)'),
('H1密封圈（B-V8.4）', 'H1 Seal Ring (B-V8.4)'),
('H1护风罩支架', 'H1 Fan Shroud Bracket'),
('H1挺住导向螺钉', 'H1 Tappet Guide Screw'),
('H1排气管垫', 'H1 Exhaust Gasket'),
('H1排气门桥组件', 'H1 Exhaust Valve Bridge Assembly'),
('H1接头体', 'H1 Joint Body'),
('H1摇臂座组件', 'H1 Rocker Seat Module'),
('H1摇臂轴组件', 'H1 Rocker Arm Shaft Module'),
('H1支撑块', 'H1 Support Block'),
('H1机油冷却器芯密封圈', 'H1 Oil Cooler Core Seal Ring'),
('H1机油喷嘴', 'H1 Oil Nozzle'),
('H1机油尺接头', 'H1 Dipstick Joint'),
('H1机油模块修理包', 'H1 Oil Module Repair Kit'),
('H1皮带轮螺栓', 'H1 Pulley Bolt'),
('H1空压机回水管', 'H1 Air Compressor Return Water Pipe'),
('H1空压机水管', 'H1 Air Compressor Water Pipe'),
('H1空压机水管总成', 'H1 Air Compressor Water Pipe Assembly'),
('H1空压机水管接头', 'H1 Air Compressor Water Pipe Joint'),
('H1空压机水管螺母', 'H1 Air Compressor Water Pipe Nut'),
('H1空压机进气管接头', 'H1 Air Compressor Intake Joint'),
('H1空压机进水管', 'H1 Air Compressor Water Inlet Pipe'),
('H1螺母', 'H1 Nut'),
('H1进气门摇臂', 'H1 Intake Valve Rocker Arm'),
('H1进气门桥', 'H1 Intake Valve Bridge'),
('H1连杆螺栓', 'H1 Connecting Rod Bolt'),
('H1阻水圈（B-V10）', 'H1 Water Seal Ring (B-V10)'),
('H1阻水圈（B-V9.3）', 'H1 Water Seal Ring (B-V9.3)'),
('H1集滤器总成', 'H1 Oil Strainer Assembly'),
('HOLSET废气涡轮增压器', 'HOLSET Turbocharger'),
('HQL增压器进油管', 'HQL Turbo Oil Feed Pipe'),
('H型减压阀', 'H-Type Pressure Reducing Valve'),
('H节温器支撑块', 'H Thermostat Support Block'),
('JQB缸盖主螺栓', 'JQB Cylinder Head Main Bolt'),
('L10后驱力润滑油管', 'L10 Rear Drive Lube Oil Pipe'),
('L10喷油器回油管', 'L10 Injector Return Pipe'),
('L10喷油器回油管总成', 'L10 Injector Return Pipe Assembly'),
('L10喷油泵润滑油管', 'L10 Injection Pump Lube Oil Pipe'),
('L10增压器回油管', 'L10 Turbo Oil Return Pipe'),
('L10增压器进水管', 'L10 Turbo Water Inlet Pipe'),
('L10护风圈支架', 'L10 Fan Shroud Bracket'),
('L10燃油回油管总成', 'L10 Fuel Return Pipe Assembly'),
('L10燃油进油管总成', 'L10 Fuel Feed Pipe Assembly'),
('L10空压机进气管', 'L10 Air Compressor Intake Pipe'),
('L10进气接管', 'L10 Intake Connection'),
('L级连杆总成', 'L-Grade Connecting Rod Assembly'),
('M10复合垫片', 'M10 Composite Washer'),
('M10平垫', 'M10 Flat Washer'),
('M10弹垫', 'M10 Spring Washer'),
('M10弹簧垫', 'M10 Spring Washer'),
('M10施必牢螺母', 'M10 Anti-Loosening Nut'),
('M10法兰面自锁螺母', 'M10 Flange Self-Locking Nut'),
('M10法兰面螺母', 'M10 Flange Nut'),
('M10空心螺栓', 'M10 Hollow Bolt'),
('M10组合密封垫圈', 'M10 Combined Seal Washer'),
('M10自锁垫片', 'M10 Self-Locking Washer'),
('M10自锁螺母', 'M10 Self-Locking Nut'),
('M10螺母', 'M10 Nut'),
('M11/13回油管', 'M11/13 Return Pipe'),
('M11/13燃油管(粗滤-输油泵)', 'M11/13 Fuel Pipe (Primary Filter-Feed Pump)'),
('M11/13燃油管（滤清器-高压油泵）', 'M11/13 Fuel Pipe (Filter-HP Pump)'),
('M11/13燃油管（输油泵-滤清器）', 'M11/13 Fuel Pipe (Feed Pump-Filter)'),
('M11手油泵进油管', 'M11 Hand Pump Oil Inlet Pipe'),
('M11气缸盖罩组件', 'M11 Cylinder Head Cover Module'),
('M11汽缸垫', 'M11 Cylinder Head Gasket'),
('M12复合垫片', 'M12 Composite Washer'),
('M12尼龙快速接头', 'M12 Nylon Quick Coupling'),
('M12平垫', 'M12 Flat Washer'),
('M12弹性垫圈', 'M12 Elastic Washer'),
('M12支撑块', 'M12 Support Block'),
('M12气路管接头（弯）', 'M12 Air Line Joint (Bent)'),
('M12螺母', 'M12 Nut'),
('M12镀锌螺母', 'M12 Galvanized Nut'),
('M13汽缸垫', 'M13 Cylinder Head Gasket'),
('M14复合垫片', 'M14 Composite Washer'),
('M14密封垫圈', 'M14 Seal Washer'),
('M14气路管接头（弯）', 'M14 Air Line Joint (Bent)'),
('M14法兰面螺母', 'M14 Flange Nut'),
('M14空心螺栓', 'M14 Hollow Bolt'),
('M14螺母', 'M14 Nut'),
('M16*1.5六角螺塞', 'M16*1.5 Hex Plug'),
('M16复合垫片', 'M16 Composite Washer'),
('M16气路管接头（弯）', 'M16 Air Line Joint (Bent)'),
('M16组合密封垫圈', 'M16 Combined Seal Washer'),
('M18复合垫片', 'M18 Composite Washer'),
('M20复合垫片', 'M20 Composite Washer'),
('M24*1.5六角薄螺母', 'M24*1.5 Hex Thin Nut'),
('M24*1.5薄螺母', 'M24*1.5 Thin Nut'),
('M26复合垫片', 'M26 Composite Washer'),
('M6复合垫片', 'M6 Composite Washer'),
('M8增压器螺母', 'M8 Turbo Nut'),
('M8复合垫片', 'M8 Composite Washer'),
('M8大垫圈', 'M8 Large Washer'),
('M8平垫', 'M8 Flat Washer'),
('M8弹簧垫', 'M8 Spring Washer'),
('M8油门球头', 'M8 Throttle Ball Joint'),
('M8法兰面自锁螺母', 'M8 Flange Self-Locking Nut'),
('M8法兰面螺母', 'M8 Flange Nut'),
('M8自锁螺母', 'M8 Self-Locking Nut'),
('M8螺母', 'M8 Nut'),
('MC05/07排气管密封环', 'MC05/07 Exhaust Seal Ring'),
('MC05/07排气管螺栓', 'MC05/07 Exhaust Bolt'),
('MC05/07排气管螺栓(8*40)', 'MC05/07 Exhaust Bolt (8*40)'),
('MC05/07气门弹簧', 'MC05/07 Valve Spring'),
('MC05/07油底壳托快', 'MC05/07 Oil Pan Support Block'),
('MC05/07油泵回油管', 'MC05/07 Oil Pump Return Pipe'),
('MC05/07滤清器回油管', 'MC05/07 Filter Return Pipe'),
('MC05/07滤清器进油管', 'MC05/07 Filter Inlet Pipe'),
('MC05/07缸盖主螺栓', 'MC05/07 Head Main Bolt'),
('MC05/07连杆螺栓', 'MC05/07 Connecting Rod Bolt'),
('MC05增压器双头螺栓', 'MC05 Turbo Stud Bolt'),
('MC07增压器双头螺栓', 'MC07 Turbo Stud Bolt'),
('MC07机油尺套管总成', 'MC07 Dipstick Sleeve Assembly'),
('MC11/13/T13增压器双头螺栓', 'MC11/13/T13 Turbo Stud Bolt'),
('MC11/13/T13排气管螺栓(10*95)', 'MC11/13/T13 Exhaust Bolt (10*95)'),
('MC11/13主轴承螺栓', 'MC11/13 Main Bearing Bolt'),
('MC11/13增压器垫片', 'MC11/13 Turbo Gasket'),
('MC11/13排气管密封环', 'MC11/13 Exhaust Seal Ring'),
('MC11/13排气管螺栓(10*50)', 'MC11/13 Exhaust Bolt (10*50)'),
('MC11/13机油尺', 'MC11/13 Oil Dipstick'),
('MC11/13气门弹簧', 'MC11/13 Valve Spring'),
('MC11/13活塞销卡簧', 'MC11/13 Piston Pin Circlip'),
('MC11/13空压机冷却回水管', 'MC11/13 Air Compressor Cooling Return Pipe'),
('MC11/13缸盖主螺栓', 'MC11/13 Head Main Bolt'),
('MC11/13飞轮螺栓', 'MC11/13 Flywheel Bolt'),
('MC11中冷后进气管', 'MC11 Post-Intercooler Intake Pipe'),
('MC11排气管垫片', 'MC11 Exhaust Gasket'),
('MC11排气管垫片 三层', 'MC11 Exhaust Gasket 3-Layer'),
('MC11机油尺', 'MC11 Oil Dipstick'),
('MC11气缸套密封圈', 'MC11 Cylinder Liner Seal Ring'),
('MC11油底壳托快', 'MC11 Oil Pan Support Block'),
('MC11油气分离器回油接管', 'MC11 Oil-Gas Separator Return Connection'),
('MC11油气分离器回油管', 'MC11 Oil-Gas Separator Return Pipe'),
('MC11活塞环组件', 'MC11 Piston Ring Set'),
('MC11缸盖组合件总成（带气门）', 'MC11 Head Combination Assembly (with Valves)'),
('MC11连杆螺栓', 'MC11 Connecting Rod Bolt'),
('MC11飞轮壳', 'MC11 Flywheel Housing'),
('MC曼机油', 'MC MAN Engine Oil'),
('MC油底壳托快', 'MC Oil Pan Support Block'),
('MP13增压器双头螺栓', 'MP13 Turbo Stud Bolt'),
('MT13国五气缸盖总成', 'MT13 China-V Cylinder Head Assembly'),
('MT13增压器双头螺栓(10*25)', 'MT13 Turbo Stud Bolt (10*25)'),
('MT13空压机回水管', 'MT13 Air Compressor Return Water Pipe'),
('MT曼机油', 'MT MAN Engine Oil'),
('NU2207轴承', 'NU2207 Bearing'),
('OM转向助力泵', 'OM Power Steering Pump'),
('O型密封圈（小）', 'O-Ring (Small)'),
('O型橡胶密封圈', 'O-Ring'),
('P10H.5气路连接胶管', 'P10H.5 Air Line Rubber Hose'),
('P10H曲轴前后油封（一套）', 'P10H Crankshaft Oil Seal Set'),
('P10H机油尺', 'P10H Oil Dipstick'),
('P10H机滤盖', 'P10H Oil Filter Cover'),
('P10H气门室盖', 'P10H Valve Chamber Cover'),
('P10H油气分离器总成', 'P10H Oil-Gas Separator Assembly'),
('P10H燃油回油管总成', 'P10H Fuel Return Pipe Assembly'),
('P10H燃油管总成/输油泵-精滤器', 'P10H Fuel Pipe / Feed Pump-Fine Filter'),
('P10H燃油进油管总成', 'P10H Fuel Feed Pipe Assembly'),
('P10H空压机回水管', 'P10H Air Compressor Return Water Pipe'),
('P10H空压机进气管', 'P10H Air Compressor Intake Pipe'),
('P10喷油器总成', 'P10 Injector Assembly'),
('P10喷油泵法兰', 'P10 Injection Pump Flange'),
('P10机滤座垫片', 'P10 Oil Filter Seat Gasket'),
('P10油底壳', 'P10 Oil Pan'),
('P10活塞', 'P10 Piston'),
('P10起动机', 'P10 Starter'),
('P10进气管固定螺栓包', 'P10 Intake Pipe Fixing Bolt Kit'),
('P10飞轮', 'P10 Flywheel'),
('P10飞轮壳', 'P10 Flywheel Housing'),
('P10高压油泵', 'P10 High Pressure Pump'),
('P10高压油泵计量单元', 'P10 High Pressure Pump Metering Unit'),
('P12(6305)飞轮轴承', 'P12 (6305) Flywheel Bearing'),
('P12/13ECU支架', 'P12/13 ECU Bracket'),
('P12/13增压器进油管', 'P12/13 Turbo Oil Feed Pipe'),
('P12/13增压器隔热罩', 'P12/13 Turbo Heat Shield'),
('P12/13水泵接头', 'P12/13 Water Pump Joint'),
('P12/13空压机进气管', 'P12/13 Air Compressor Intake Pipe'),
('P12/13管接头组件', 'P12/13 Pipe Joint Assembly'),
('P12/13缸盖主螺栓', 'P12/13 Head Main Bolt'),
('P12/P13增压器水管总成', 'P12/P13 Turbo Water Pipe Assembly'),
('P12ECU支架', 'P12 ECU Bracket'),
('P12EVB支架螺栓', 'P12 EVB Bracket Bolt'),
('P12EVB支架衬套密封圈', 'P12 EVB Bracket Bushing Seal Ring'),
('P12NG增压器进油管总成', 'P12NG Turbo Oil Feed Pipe Assembly'),
('P12中间齿轮轴', 'P12 Idler Gear Shaft'),
('P12主轴承螺栓', 'P12 Main Bearing Bolt'),
('P12全车水堵', 'P12 Water Core Plug Kit'),
('P12凸轮轴', 'P12 Camshaft'),
('P12凸轮轴止推片', 'P12 Camshaft Thrust Washer'),
('P12凸轮轴止推片（拆机）', 'P12 Camshaft Thrust Washer (Dismantled)'),
('P12凸轮轴衬套', 'P12 Camshaft Bushing'),
('P12凸轮轴齿轮', 'P12 Camshaft Gear'),
('P12加机油口盖', 'P12 Oil Fill Cap'),
('P12加紧块', 'P12 Clamping Block'),
('P12单层进气垫', 'P12 Single-Layer Intake Gasket'),
('P12发动机全套螺栓（唐西春）', 'P12 Engine Complete Bolt Kit (Tang Xichun)'),
('P12后驱力总成', 'P12 Rear Drive Assembly'),
('P12后驱力润滑油管', 'P12 Rear Drive Lube Oil Pipe'),
('P12喷嘴螺栓', 'P12 Nozzle Bolt'),
('P12喷油器压紧块', 'P12 Injector Clamping Block'),
('P12喷油器垫片', 'P12 Injector Gasket'),
('P12喷油器总成', 'P12 Injector Assembly'),
('P12增压器回油管', 'P12 Turbo Oil Return Pipe'),
('P12增压器垫片', 'P12 Turbo Gasket'),
('P12增压器垫片（方）', 'P12 Turbo Gasket (Square)'),
('P12增压器隔热罩', 'P12 Turbo Heat Shield'),
('P12多层排气管垫', 'P12 Multi-Layer Exhaust Gasket'),
('P12大泵全车螺栓', 'P12 Pump Complete Bolt Set'),
('P12夹紧块', 'P12 Clamping Block'),
('P12密封圈修理包', 'P12 Seal Ring Repair Kit'),
('P12惰轮轴挡板', 'P12 Idler Shaft Baffle'),
('P12排气制动螺栓', 'P12 Exhaust Brake Bolt'),
('P12排气垫', 'P12 Exhaust Gasket'),
('P12排气管', 'P12 Exhaust Pipe'),
('P12排气管支架', 'P12 Exhaust Pipe Bracket'),
('P12排气管螺丝', 'P12 Exhaust Pipe Screw'),
('P12排气门', 'P12 Exhaust Valve'),
('P12排气门座', 'P12 Exhaust Valve Seat'),
('P12摇臂结合组', 'P12 Rocker Arm Combination'),
('P12摇臂轴总成（2231）', 'P12 Rocker Arm Shaft Assembly (2231)'),
('P12摇臂轴螺丝', 'P12 Rocker Arm Shaft Screw'),
('P12支撑摇臂座', 'P12 Support Rocker Seat'),
('P12曲轴前油封', 'P12 Crankshaft Front Oil Seal'),
('P12曲轴后油封', 'P12 Crankshaft Rear Oil Seal'),
('P12曲轴止推片', 'P12 Crankshaft Thrust Washer'),
('P12曲轴齿轮', 'P12 Crankshaft Gear'),
('P12机油冷却器盖', 'P12 Oil Cooler Cover'),
('P12机油冷却器盖垫片', 'P12 Oil Cooler Cover Gasket'),
('P12机油喷嘴', 'P12 Oil Nozzle'),
('P12机油喷嘴空心螺栓', 'P12 Oil Nozzle Hollow Bolt'),
('P12机油滤芯', 'P12 Oil Filter Element'),
('P12机油管', 'P12 Oil Pipe'),
('P12机滤座垫片', 'P12 Oil Filter Seat Gasket'),
('P12气缸盖罩', 'P12 Cylinder Head Cover'),
('P12气门导管', 'P12 Valve Guide'),
('P12气门挺柱', 'P12 Valve Tappet'),
('P12气门推杆', 'P12 Valve Push Rod'),
('P12气门推杆衬套', 'P12 Valve Push Rod Bushing'),
('P12气门油封', 'P12 Valve Stem Seal'),
('P12气门调整螺栓', 'P12 Valve Adjustment Bolt'),
('P12水泵垫片', 'P12 Water Pump Gasket'),
('P12水泵总成', 'P12 Water Pump Assembly'),
('P12水泵接头', 'P12 Water Pump Joint'),
('P12水泵泵头(高)', 'P12 Water Pump Head (High)'),
('P12水管接头', 'P12 Water Pipe Joint'),
('P12汽缸垫', 'P12 Cylinder Head Gasket'),
('P12油气分离器', 'P12 Oil-Gas Separator'),
('P12油气分离器支架', 'P12 Oil-Gas Separator Bracket'),
('P12油轨限压阀', 'P12 Fuel Rail Pressure Relief Valve'),
('P12活塞', 'P12 Piston'),
('P12活塞环', 'P12 Piston Ring'),
('P12活塞肖', 'P12 Piston Pin'),
('P12活塞销卡簧', 'P12 Piston Pin Circlip'),
('P12润滑油管', 'P12 Lube Oil Pipe'),
('P12火花塞衬套密封圈', 'P12 Spark Plug Bushing Seal Ring'),
('P12燃油管', 'P12 Fuel Pipe'),
('P12皮带轮', 'P12 Pulley'),
('P12皮带轮螺栓', 'P12 Pulley Bolt'),
('P12硅油减震器挡板', 'P12 Viscous Damper Baffle'),
('P12空压机回水管', 'P12 Air Compressor Return Water Pipe'),
('P12空压机回水管总成', 'P12 Air Compressor Return Water Pipe Assembly'),
('P12空压机总成', 'P12 Air Compressor Assembly'),
('P12空压机润滑油管', 'P12 Air Compressor Lube Oil Pipe'),
('P12空压机进气接头', 'P12 Air Compressor Intake Joint'),
('P12空压机进水管', 'P12 Air Compressor Water Inlet Pipe'),
('P12空压机进水管总成', 'P12 Air Compressor Water Inlet Pipe Assembly'),
('P12空压机进水管（带螺母）', 'P12 Air Compressor Water Inlet Pipe (with Nut)'),
('P12空压机齿轮', 'P12 Air Compressor Gear'),
('P12管接头组件', 'P12 Pipe Joint Assembly'),
('P12缸盖副螺栓', 'P12 Cylinder Head Auxiliary Bolt'),
('P12缸盖圆柱销修理包', 'P12 Head Dowel Pin Repair Kit'),
('P12缸盖罩', 'P12 Cylinder Head Cover'),
('P12缸盖罩衬垫', 'P12 Cylinder Head Cover Gasket'),
('P12节温器芯', 'P12 Thermostat Element'),
('P12输出法兰', 'P12 Output Flange'),
('P12进气接管', 'P12 Intake Connection'),
('P12进气管', 'P12 Intake Pipe'),
('P12进气门', 'P12 Intake Valve'),
('P12连接板', 'P12 Connecting Plate'),
('P12连杆总成', 'P12 Connecting Rod Assembly'),
('P12连杆瓦', 'P12 Connecting Rod Bearing'),
('P12连杆瓦+0.03', 'P12 Connecting Rod Bearing +0.03'),
('P12连杆衬套', 'P12 Connecting Rod Bushing'),
('P12集滤器', 'P12 Oil Strainer'),
('P12飞轮', 'P12 Flywheel'),
('P12飞轮螺丝', 'P12 Flywheel Screw'),
('P12高压油管', 'P12 High Pressure Pipe'),
('P12高压油管螺母', 'P12 High Pressure Pipe Nut'),
('P13CNG增压器隔热罩', 'P13 CNG Turbo Heat Shield'),
('P13ECU支撑块', 'P13 ECU Support Block'),
('P13EGR冷却器支架', 'P13 EGR Cooler Bracket'),
('P13EGR冷却液胶管', 'P13 EGR Coolant Rubber Hose'),
('P13EGR固定支架', 'P13 EGR Fixing Bracket'),
('P13EGR支架', 'P13 EGR Bracket'),
('P13EGR水管接头', 'P13 EGR Water Pipe Joint'),
('P13EVB摇臂支架', 'P13 EVB Rocker Bracket'),
('P13EVB摇臂支架（拆机）', 'P13 EVB Rocker Bracket (Dismantled)'),
('P13EVB润滑油管', 'P13 EVB Lube Oil Pipe'),
('P13G后取利总成', 'P13G Rear PTO Assembly'),
('P13NG增压器进油管', 'P13NG Turbo Oil Feed Pipe'),
('P13NG支撑（缸盖罩）', 'P13NG Support (Head Cover)'),
('P13NG油气分离器进气管', 'P13NG Oil-Gas Separator Intake Pipe'),
('P13WEVB排气门摇臂', 'P13 WEVB Exhaust Valve Rocker Arm'),
('P13WEVB支架螺栓（法兰面)', 'P13 WEVB Bracket Bolt (Flange)'),
('P13中间齿轮总成', 'P13 Idler Gear Assembly'),
('P13冷却器连接胶管', 'P13 Cooler Connecting Rubber Hose'),
('P13冷却液连接胶管', 'P13 Coolant Rubber Hose'),
('P13凸轮轴齿轮', 'P13 Camshaft Gear'),
('P13卡箍', 'P13 Hose Clamp'),
('P13发动机前支架', 'P13 Engine Front Bracket'),
('P13后取利总成', 'P13 Rear PTO Assembly'),
('P13后驱力总成', 'P13 Rear Drive Assembly'),
('P13喷油器回油管', 'P13 Injector Return Pipe'),
('P13喷油泵齿轮', 'P13 Injection Pump Gear'),
('P13国六增压器隔热罩', 'P13 China-VI Turbo Heat Shield'),
('P13国六排气管密封环', 'P13 China-VI Exhaust Seal Ring'),
('P13增压器出水管总成', 'P13 Turbo Water Outlet Pipe Assembly'),
('P13增压器双头螺栓', 'P13 Turbo Stud Bolt'),
('P13增压器后排气管卡箍', 'P13 Turbo Rear Exhaust Pipe Clamp'),
('P13增压器回油管', 'P13 Turbo Oil Return Pipe'),
('P13增压器回油管总成', 'P13 Turbo Oil Return Pipe Assembly'),
('P13增压器垫片', 'P13 Turbo Gasket'),
('P13增压器放水阀', 'P13 Turbo Drain Valve'),
('P13增压器进油管总成', 'P13 Turbo Oil Feed Pipe Assembly'),
('P13增压器隔热罩', 'P13 Turbo Heat Shield'),
('P13密封圈', 'P13 Seal Ring'),
('P13废气旁通阀出气管', 'P13 Waste Gate Outlet Pipe'),
('P13排气制动支架', 'P13 Exhaust Brake Bracket'),
('P13排气尾管支架', 'P13 Exhaust Tail Pipe Bracket'),
('P13排气管', 'P13 Exhaust Pipe'),
('P13排气管垫', 'P13 Exhaust Gasket'),
('P13排气管总成（带隔热棉）', 'P13 Exhaust Pipe Assembly (with Heat Insulation)'),
('P13排气管螺栓', 'P13 Exhaust Pipe Bolt'),
('P13排气门座', 'P13 Exhaust Valve Seat'),
('P13排气门摇臂', 'P13 Exhaust Valve Rocker Arm'),
('P13摇臂座', 'P13 Rocker Seat'),
('P13摇臂座内六角螺栓', 'P13 Rocker Seat Socket Bolt'),
('P13摇臂轴', 'P13 Rocker Arm Shaft'),
('P13支撑块', 'P13 Support Block'),
('P13支撑块（燃油滤清器）', 'P13 Support Block (Fuel Filter)'),
('P13旁通阀废气出气管', 'P13 Bypass Exhaust Outlet Pipe'),
('P13旁通阀废气出气管V62', 'P13 Bypass Exhaust Outlet Pipe V62'),
('P13机油冷却器盖', 'P13 Oil Cooler Cover'),
('P13机油冷却器盖总成', 'P13 Oil Cooler Cover Assembly'),
('P13机油冷却器芯', 'P13 Oil Cooler Core'),
('P13机油喷嘴', 'P13 Oil Nozzle'),
('P13机油喷嘴总成', 'P13 Oil Nozzle Assembly'),
('P13机油喷嘴（拆机）', 'P13 Oil Nozzle (Dismantled)'),
('P13机油尺', 'P13 Oil Dipstick'),
('P13机油尺下组件', 'P13 Dipstick Lower Module'),
('P13机油尺总成', 'P13 Oil Dipstick Assembly'),
('P13机油泵齿轮', 'P13 Oil Pump Gear'),
('P13柴滤支架', 'P13 Diesel Filter Bracket'),
('P13气路连接胶管', 'P13 Air Line Rubber Hose'),
('P13水泵泵头', 'P13 Water Pump Head'),
('P13汽化路管接头', 'P13 Vaporizing Line Joint'),
('P13汽缸垫', 'P13 Cylinder Head Gasket'),
('P13油底壳垫', 'P13 Oil Pan Gasket'),
('P13油底壳托快', 'P13 Oil Pan Support Block'),
('P13油气分离器', 'P13 Oil-Gas Separator'),
('P13油气分离器出气管', 'P13 Oil-Gas Separator Outlet Pipe'),
('P13油气分离器出气管总成', 'P13 Oil-Gas Separator Outlet Pipe Assembly'),
('P13油气分离器出气胶管', 'P13 Oil-Gas Separator Outlet Rubber Hose'),
('P13油气分离器回油管', 'P13 Oil-Gas Separator Return Pipe'),
('P13油气分离器支架', 'P13 Oil-Gas Separator Bracket'),
('P13油气分离器润滑油管', 'P13 Oil-Gas Separator Lube Oil Pipe'),
('P13油气分离器管', 'P13 Oil-Gas Separator Pipe'),
('P13油气分离器管接头', 'P13 Oil-Gas Separator Pipe Joint'),
('P13油气分离器胶管', 'P13 Oil-Gas Separator Rubber Hose'),
('P13油气分离器隔热罩', 'P13 Oil-Gas Separator Heat Shield'),
('P13滤清器支架', 'P13 Filter Bracket'),
('P13火花塞衬套', 'P13 Spark Plug Bushing'),
('P13点火线圈衬套压板', 'P13 Ignition Coil Bushing Plate'),
('P13燃油进油管', 'P13 Fuel Feed Pipe'),
('P13燃油进油管总成', 'P13 Fuel Feed Pipe Assembly'),
('P13盖板', 'P13 Cover Plate'),
('P13空压机回水管', 'P13 Air Compressor Return Water Pipe'),
('P13空压机回水管总成', 'P13 Air Compressor Return Water Pipe Assembly'),
('P13空压机水管', 'P13 Air Compressor Water Pipe'),
('P13空压机水管总成', 'P13 Air Compressor Water Pipe Assembly'),
('P13空压机进气接头', 'P13 Air Compressor Intake Joint'),
('P13空压机进气管', 'P13 Air Compressor Intake Pipe'),
('P13管接头组件', 'P13 Pipe Joint Assembly'),
('P13线束支架', 'P13 Harness Bracket'),
('P13缸盖主螺栓', 'P13 Head Main Bolt'),
('P13缸盖副螺栓', 'P13 Head Auxiliary Bolt'),
('P13缸盖罩', 'P13 Cylinder Head Cover'),
('P13进气管垫', 'P13 Intake Gasket'),
('P13进气门座', 'P13 Intake Valve Seat'),
('P13连接板', 'P13 Connecting Plate'),
('P13连杆螺栓', 'P13 Connecting Rod Bolt'),
('P13连杆螺栓（14*1.25）', 'P13 Connecting Rod Bolt (14*1.25)'),
('P13连杆螺栓（14*1.5）', 'P13 Connecting Rod Bolt (14*1.5)'),
('P13隔热罩螺栓', 'P13 Heat Shield Bolt'),
('P13集滤器', 'P13 Oil Strainer'),
('P13集滤器支架', 'P13 Oil Strainer Bracket'),
('P13高压油管', 'P13 High Pressure Pipe'),
('P13高压油管（泵-轨）', 'P13 High Pressure Pipe (Pump-Rail)'),
('P6凸轮轴止推片（拆机）', 'P6 Camshaft Thrust Washer (Dismantled)'),
('P6机油喷嘴密封圈', 'P6 Oil Nozzle Seal Ring'),
('P6机油尺总成', 'P6 Oil Dipstick Assembly'),
('P6气门弹簧上座', 'P6 Valve Spring Upper Seat'),
('P6气门调整螺栓', 'P6 Valve Adjustment Bolt'),
('P6油底壳垫', 'P6 Oil Pan Gasket'),
('P6连杆总成（涨段）', 'P6 Connecting Rod Assembly (Stretch Section)'),
('P7/P8发动机支架', 'P7/P8 Engine Mount Bracket'),
('P7/P8支撑块', 'P7/P8 Support Block'),
('P7EVB排气门桥总成', 'P7 EVB Exhaust Valve Bridge Assembly'),
('P7EVB支架', 'P7 EVB Bracket'),
('P7凸轮轴止推片(拆机)', 'P7 Camshaft Thrust Washer (Dismantled)'),
('P7加机油口盖', 'P7 Oil Fill Cap'),
('P7发电机支架', 'P7 Alternator Bracket'),
('P7喷油器衬套', 'P7 Injector Bushing'),
('P7喷油泵机油管', 'P7 Injection Pump Oil Pipe'),
('P7回油管接头', 'P7 Oil Return Joint'),
('P7增压器双头螺栓', 'P7 Turbo Stud Bolt'),
('P7增压器回油管', 'P7 Turbo Oil Return Pipe'),
('P7增压器垫片', 'P7 Turbo Gasket'),
('P7增压器方垫', 'P7 Turbo Square Gasket'),
('P7增压器进油管', 'P7 Turbo Oil Feed Pipe'),
('P7排气管垫', 'P7 Exhaust Pipe Gasket'),
('P7排气门座圈', 'P7 Exhaust Valve Seat'),
('P7曲轴止推片', 'P7 Crankshaft Thrust Washer'),
('P7机油喷嘴', 'P7 Oil Nozzle'),
('P7机油喷嘴-35.4', 'P7 Oil Nozzle -35.4'),
('P7机油尺下组件', 'P7 Dipstick Lower Module'),
('P7机油尺总成', 'P7 Oil Dipstick Assembly'),
('P7气缸套', 'P7 Cylinder Liner'),
('P7气门弹簧上座', 'P7 Valve Spring Upper Seat'),
('P7气门挺住', 'P7 Valve Tappet'),
('P7气门推杆', 'P7 Valve Push Rod'),
('P7气门摇臂', 'P7 Valve Rocker Arm'),
('P7气门油封', 'P7 Valve Stem Seal'),
('P7气门调整螺栓', 'P7 Valve Adjustment Bolt'),
('P7气门锁夹', 'P7 Valve Lock Clamp'),
('P7水泵垫', 'P7 Water Pump Gasket'),
('P7水管接头', 'P7 Water Pipe Joint'),
('P7汽缸垫', 'P7 Cylinder Head Gasket'),
('P7汽缸盖分总成', 'P7 Cylinder Head Sub-Assembly'),
('P7油底壳', 'P7 Oil Pan'),
('P7油底壳垫', 'P7 Oil Pan Gasket'),
('P7活塞', 'P7 Piston'),
('P7活塞环装机', 'P7 Piston Ring (Assembly Line)'),
('P7活塞销', 'P7 Piston Pin'),
('P7活塞销卡簧', 'P7 Piston Pin Circlip'),
('P7活塞（装机）', 'P7 Piston (Assembly Line)'),
('P7点火线圈衬套', 'P7 Ignition Coil Bushing'),
('P7燃油回油管', 'P7 Fuel Return Pipe'),
('P7燃油管管接头', 'P7 Fuel Pipe Joint'),
('P7燃油进油管', 'P7 Fuel Feed Pipe'),
('P7燃油进油管总成', 'P7 Fuel Feed Pipe Assembly'),
('P7空压机水管总成', 'P7 Air Compressor Water Pipe Assembly'),
('P7空压机润滑油管', 'P7 Air Compressor Lube Oil Pipe'),
('P7管接头组件', 'P7 Pipe Joint Assembly'),
('P7紧扣螺母', 'P7 Lock Nut'),
('P7缸盖主螺栓（全长185）', 'P7 Cylinder Head Main Bolt (185mm)'),
('P7缸盖罩六角头螺栓', 'P7 Head Cover Hex Bolt'),
('P7缸盖罩衬垫', 'P7 Head Cover Gasket'),
('P7缸盖罩（天然气）', 'P7 Head Cover (Natural Gas)'),
('P7缸盖螺座', 'P7 Head Threaded Seat'),
('P7缸盖螺栓（全长130）', 'P7 Cylinder Head Bolt (130mm)'),
('P7节温器芯', 'P7 Thermostat Element'),
('P7进气管垫', 'P7 Intake Gasket'),
('P7连杆总成', 'P7 Connecting Rod Assembly'),
('P7连杆螺栓', 'P7 Connecting Rod Bolt'),
('P7阻水圈', 'P7 Water Seal Ring'),
('P7阻水圈（113*3.05）', 'P7 Water Seal Ring (113*3.05)'),
('P7飞轮螺栓', 'P7 Flywheel Bolt'),
('P7飞轮螺栓（客车）', 'P7 Flywheel Bolt (Coach)'),
('P8后排气管卡箍', 'P8 Rear Exhaust Pipe Clamp'),
('P8后驱力盖密封圈', 'P8 Rear Drive Cover Seal Ring'),
('P8垫片', 'P8 Washer'),
('P8增压器回油管总成', 'P8 Turbo Oil Return Pipe Assembly'),
('P8增压器进油管', 'P8 Turbo Oil Feed Pipe'),
('P8增压器隔热罩', 'P8 Turbo Heat Shield'),
('P8排气管垫', 'P8 Exhaust Pipe Gasket'),
('P8支撑快', 'P8 Support Block'),
('P8机油冷却器盖板', 'P8 Oil Cooler Cover Plate'),
('P8机油尺下组件', 'P8 Dipstick Lower Module'),
('P8机油模块支撑快', 'P8 Oil Module Support Block'),
('P8机油滤清器盖', 'P8 Oil Filter Cover'),
('P8模块密封圈', 'P8 Module Seal Ring'),
('P8模块密封圈修理包', 'P8 Module Seal Ring Repair Kit'),
('P8气缸套', 'P8 Cylinder Liner'),
('P8水管接头', 'P8 Water Pipe Joint'),
('P8汽缸垫', 'P8 Cylinder Head Gasket'),
('P8活塞', 'P8 Piston'),
('P8活塞环组件', 'P8 Piston Ring Set'),
('P8活塞销', 'P8 Piston Pin'),
('P8液压泵支架', 'P8 Hydraulic Pump Bracket'),
('P8空压机密封圈', 'P8 Air Compressor Seal Ring'),
('P8缸盖罩衬垫', 'P8 Head Cover Gasket'),
('P8进气管垫', 'P8 Intake Gasket'),
('P8连杆瓦上瓦', 'P8 Connecting Rod Upper Bearing'),
('P8连杆瓦下瓦', 'P8 Connecting Rod Lower Bearing'),
('P8阻水圈', 'P8 Water Seal Ring'),
('P8集滤器', 'P8 Oil Strainer'),
('P型管夹', 'P-Type Pipe Clamp'),
('Q1860法兰面六角头螺栓', 'Q1860 Hex Flange Bolt'),
('STR挡把簧', 'STR Gear Lever Spring'),
('S喷油器压板', 'S Injector Press Plate'),
('S气门调整螺栓', 'S Valve Adjustment Bolt'),
('S进油管总成', 'S Oil Inlet Pipe Assembly'),
('T7机油尺（154.5）', 'T7 Oil Dipstick (154.5)'),
('TX中冷器出气胶管', 'TX Intercooler Outlet Rubber Hose'),
('TX中冷器进气胶管', 'TX Intercooler Inlet Rubber Hose'),
('TX冷却模块拉杆', 'TX Cooling Module Tie Rod'),
('TX发动机右后支撑', 'TX Engine Right Rear Support'),
('TX发动机左后支撑', 'TX Engine Left Rear Support'),
('TX国三全功能发动机线束总成', 'TX China-III Full Engine Harness Assembly'),
('TX散热器出水胶管', 'TX Radiator Outlet Rubber Hose'),
('V型卡箍', 'V-Band Clamp'),
('V型沟槽卡箍φ104', 'V-Groove Clamp φ104'),
('V推螺栓', 'V-Push Bolt'),
('WD618飞轮壳', 'WD618 Flywheel Housing'),
('WEVB接头', 'WEVB Joint'),
('WEVB摇臂座', 'WEVB Rocker Seat'),
('WEVB摇臂总成', 'WEVB Rocker Arm Assembly'),
('WEVB支撑臂', 'WEVB Support Arm'),
('WEVB气门桥(2231)', 'WEVB Valve Bridge (2231)'),
('WEVB气门桥（1751）', 'WEVB Valve Bridge (1751)'),
('WEVB润滑油管总成', 'WEVB Lube Oil Pipe Assembly'),
('WEVB缸盖螺栓包', 'WEVB Cylinder Head Bolt Kit'),
('WEVB进油管总成', 'WEVB Oil Inlet Pipe Assembly'),
('WEVB进油管总成（短）', 'WEVB Oil Inlet Pipe Assembly (Short)'),
('WEVB进油管接头总成', 'WEVB Oil Inlet Joint Assembly'),
('WP10/618端盖齿轮室螺丝包', 'WP10/618 Gear Housing Screw Kit'),
('WP10EGR发动机密封圈修理包', 'WP10 EGR Engine Seal Repair Kit'),
('WP10EGR燃油管', 'WP10 EGR Fuel Pipe'),
('WP10H主轴瓦', 'WP10H Main Bearing'),
('WP10H全车垫', 'WP10H Complete Gasket Kit'),
('WP10H心组件', 'WP10H Core Module'),
('WP10H曲轴总成', 'WP10H Crankshaft Assembly'),
('WP10H机油滤芯', 'WP10H Oil Filter Element'),
('WP10H连杆瓦', 'WP10H Connecting Rod Bearing'),
('WP10排气管增压器螺栓包', 'WP10 Exhaust-Turbo Bolt Kit'),
('WP10油泵固定螺栓包', 'WP10 Oil Pump Fixing Bolt Kit'),
('WP10电喷发动机密封圈修理包', 'WP10 EFI Engine Seal Repair Kit'),
('WP10空压机螺丝包', 'WP10 Air Compressor Screw Kit'),
('WP10空心螺栓包', 'WP10 Hollow Bolt Kit'),
('WP10缸盖出水管螺栓', 'WP10 Cylinder Head Water Outlet Bolt'),
('WP12中缸螺栓', 'WP12 Mid-Cylinder Bolt'),
('WP12中间齿轮轴止推片', 'WP12 Idler Gear Shaft Thrust Washer'),
('WP12凸轮轴齿轮固定螺栓', 'WP12 Camshaft Gear Fixing Bolt'),
('WP12前支架螺栓', 'WP12 Front Bracket Bolt'),
('WP12前端盖螺栓', 'WP12 Front Cover Bolt'),
('WP12双管接头', 'WP12 Double Pipe Joint'),
('WP12发电机螺栓', 'WP12 Alternator Bolt'),
('WP12喷油器回油管', 'WP12 Injector Return Pipe'),
('WP12喷油泵法兰', 'WP12 Injection Pump Flange'),
('WP12圆柱销修理包', 'WP12 Dowel Pin Repair Kit'),
('WP12增压器排气管', 'WP12 Turbo Exhaust Pipe'),
('WP12增压器支架', 'WP12 Turbo Bracket'),
('WP12整套螺栓', 'WP12 Complete Bolt Set'),
('WP12机冷盖螺栓', 'WP12 Oil Cooler Cover Bolt'),
('WP12机油泵油底壳螺栓', 'WP12 Oil Pump Oil Pan Bolt'),
('WP12水泵风扇托架螺栓', 'WP12 Water Pump Fan Bracket Bolt'),
('WP12油泵部分螺栓', 'WP12 Oil Pump Section Bolts'),
('WP12空压机螺栓', 'WP12 Air Compressor Bolt'),
('WP12缸体螺栓', 'WP12 Cylinder Block Bolt'),
('WP12缸盖组装明细', 'WP12 Cylinder Head Assembly List'),
('WP12缸盖螺栓', 'WP12 Cylinder Head Bolt'),
('WP12进气管螺栓', 'WP12 Intake Pipe Bolt'),
('WP12连接板螺栓', 'WP12 Connecting Plate Bolt'),
('WP12飞轮壳螺栓', 'WP12 Flywheel Housing Bolt'),
('WP12飞轮皮带轮螺栓', 'WP12 Flywheel Pulley Bolt'),
('WP13分体缸盖罩定位套', 'WP13 Split Head Cover Locating Sleeve'),
('WP13增压器双头螺栓', 'WP13 Turbo Stud Bolt'),
('WP13增压器回油管总成', 'WP13 Turbo Oil Return Pipe Assembly'),
('WP13增压器水管总成', 'WP13 Turbo Water Pipe Assembly'),
('WP13增压器进油管', 'WP13 Turbo Oil Feed Pipe'),
('WP13增压器进油管（带卡套螺母）', 'WP13 Turbo Oil Feed Pipe (with Ferrule Nut)'),
('WP13摇臂支架定位套', 'WP13 Rocker Bracket Locating Sleeve'),
('WP13机油冷却器盖垫', 'WP13 Oil Cooler Cover Gasket'),
('WP13气路连接胶管', 'WP13 Air Line Rubber Hose'),
('WP13燃油回油管总成', 'WP13 Fuel Return Pipe Assembly'),
('WP13燃油管进油管总成', 'WP13 Fuel Feed Pipe Assembly'),
('WP13燃油进油管总成', 'WP13 Fuel Feed Pipe Assembly'),
('WP13空压机水管', 'WP13 Air Compressor Water Pipe'),
('WP13飞轮螺栓', 'WP13 Flywheel Bolt'),
('WP13齿轮润滑油管总成', 'WP13 Gear Lube Oil Pipe Assembly'),
('WP17空压机润滑油管', 'WP17 Air Compressor Lube Oil Pipe'),
('WP6机油尺', 'WP6 Oil Dipstick'),
('WP6机油尺总成', 'WP6 Oil Dipstick Assembly'),
('WP6气门弹簧', 'WP6 Valve Spring'),
('WP7发电机支架', 'WP7 Alternator Bracket'),
('WP7增压器回油管', 'WP7 Turbo Oil Return Pipe'),
('WP7增压器进油管', 'WP7 Turbo Oil Feed Pipe'),
('WP7整体式摇臂轴总成', 'WP7 Integral Rocker Arm Shaft Assembly'),
('WP7曲轴前油封', 'WP7 Crankshaft Front Oil Seal'),
('WP7曲轴后油封', 'WP7 Crankshaft Rear Oil Seal'),
('WP7机油尺', 'WP7 Oil Dipstick'),
('WP7机油尺总成', 'WP7 Oil Dipstick Assembly'),
('WP7气门弹簧', 'WP7 Valve Spring'),
('WP7气门桥', 'WP7 Valve Bridge'),
('WP7水泵总成', 'WP7 Water Pump Assembly'),
('WP7油底壳', 'WP7 Oil Pan'),
('WP7油底壳垫', 'WP7 Oil Pan Gasket'),
('WP7连杆螺栓', 'WP7 Connecting Rod Bolt'),
('W型接头', 'W-Type Joint'),
('p12喷油器总成', 'P12 Injector Assembly'),
('p12机油滤芯', 'P12 Oil Filter Element'),
('φ10复合垫片', 'φ10 Composite Washer'),
('φ10平垫圈', 'φ10 Flat Washer'),
('φ10球面垫圈', 'φ10 Spherical Washer'),
('φ12复合垫片', 'φ12 Composite Washer'),
('φ14复合垫片', 'φ14 Composite Washer'),
('φ14柴滤座', 'φ14 Diesel Filter Seat'),
('φ16复合垫片', 'φ16 Composite Washer'),
('φ16柴滤座', 'φ16 Diesel Filter Seat'),
('φ18复合垫片', 'φ18 Composite Washer'),
('φ18柴滤座', 'φ18 Diesel Filter Seat'),
('φ26复合垫片', 'φ26 Composite Washer'),
('φ282平卡', 'φ282 Flat Clamp'),
('φ30复合垫片', 'φ30 Composite Washer'),
('φ38复合垫片', 'φ38 Composite Washer'),
('φ48曲轴法兰', 'φ48 Crankshaft Flange'),
('φ50曲轴法兰', 'φ50 Crankshaft Flange'),
('φ52.4曲轴法兰', 'φ52.4 Crankshaft Flange'),
('φ590 环形风扇', 'φ590 Ring Fan'),
('φ640环形风扇', 'φ640 Ring Fan'),
('φ6复合垫片', 'φ6 Composite Washer'),
('φ6空心螺栓', 'φ6 Hollow Bolt'),
('φ8复合垫片', 'φ8 Composite Washer'),
('φ8球面垫圈', 'φ8 Spherical Washer'),
('一体隔热罩', 'Integrated Heat Shield'),
('一道滤芯', 'First Stage Filter Element'),
('三、四排气管', 'No.3-4 Exhaust Pipe'),
('三、四缸排气管', 'No.3-4 Cylinder Exhaust Pipe'),
('三四缸排气管', 'No.3-4 Cylinder Exhaust Pipe'),
('三角盖板', 'Triangle Cover Plate'),
('三角盖板螺栓', 'Triangle Cover Plate Bolt'),
('三通管接头', 'Three-Way Pipe Joint'),
('三通阀', 'Three-Way Valve'),
('上进油管(后取力)', 'Upper Oil Inlet Pipe (Rear PTO)'),
('中冷管', 'Intercooler Pipe'),
('中冷管(后取力)', 'Intercooler Pipe (Rear PTO)'),
('中冷管总成', 'Intercooler Pipe Assembly'),
('中冷管支撑板', 'Intercooler Pipe Support Plate'),
('中冷进气管', 'Intercooler Intake Pipe'),
('中冷进气管下组件', 'Intercooler Intake Pipe Lower Module'),
('中排气管', 'Middle Exhaust Pipe'),
('中置增压器回油管', 'Mid-Mounted Turbo Oil Return Pipe'),
('中置增压器进油管', 'Mid-Mounted Turbo Oil Feed Pipe'),
('中间接头', 'Intermediate Joint'),
('中间法兰', 'Intermediate Flange'),
('中间隔圈', 'Intermediate Spacer Ring'),
('中间齿轮', 'Idler Gear'),
('中间齿轮分总成', 'Idler Gear Sub-Assembly'),
('中间齿轮垫片', 'Idler Gear Washer'),
('中间齿轮总成', 'Idler Gear Assembly'),
('中间齿轮盖板', 'Idler Gear Cover Plate'),
('中间齿轮组件', 'Idler Gear Module'),
('中间齿轮轴', 'Idler Gear Shaft'),
('中间齿轮轴挡板', 'Idler Gear Shaft Baffle'),
('中间齿轮轴盖板（后驱力）', 'Idler Gear Shaft Cover Plate (Rear Drive Unit)'),
('中间齿轮轴螺栓', 'Idler Gear Shaft Bolt'),
('中间齿轮轴（2231)', 'Idler Gear Shaft (2231)'),
('中间齿轮轴（E056）', 'Idler Gear Shaft (E056)'),
('中间齿轮轴（后驱力）', 'Idler Gear Shaft (Rear Drive Unit)'),
('中间齿轮（后驱力）', 'Idler Gear (Rear Drive Unit)'),
('中驱力附件', 'Middle Drive Unit Accessory'),
('主动齿轮总成', 'Drive Gear Assembly'),
('主油道后螺塞', 'Main Oil Gallery Rear Plug'),
('主油道限压阀', 'Main Oil Gallery Relief Valve'),
('主轴承螺栓', 'Main Bearing Bolt'),
('主轴承螺栓（带孔）', 'Main Bearing Bolt (with Hole)'),
('交流发电机', 'Alternator'),
('传动轴挡板', 'Drive Shaft Baffle'),
('传动轴盖板', 'Drive Shaft Cover Plate'),
('传动轴罗丝', 'Drive Shaft Screw'),
('传动轴螺丝', 'Drive Shaft Screw'),
('传动轴螺丝母', 'Propeller Shaft Nut'),
('传动轴螺母', 'Drive Shaft Nut'),
('低压油管管接头', 'Low Pressure Fuel Pipe Joint'),
('低压过滤器滤芯', 'Low Pressure Filter Element'),
('供油泵', 'Fuel Supply Pump'),
('信号盘', 'Signal Disc'),
('停油缸', 'Fuel Cut-Off Cylinder'),
('停油缸总成', 'Fuel Cut-Off Cylinder Assembly'),
('停油缸螺杆', 'Fuel Cut-Off Cylinder Screw'),
('全车垫', 'Complete Gasket Kit'),
('全车水堵', 'Water Core Plug Kit'),
('全车稳丁', 'Complete Vehicle Dowel Pin'),
('全钢排气管垫', 'All-Steel Exhaust Gasket'),
('全铁全车水堵', 'All-Iron Water Core Plug Kit'),
('全铜水堵', 'All-Copper Water Core Plug'),
('六角头法兰面带突齿螺栓', 'Hex Flange Bolt with Serration'),
('六角头法兰面螺栓', 'Hex Flange Bolt'),
('六角头螺丝', 'Hex Head Screw'),
('六角头螺塞', 'Hex Head Plug'),
('六角头螺母', 'Hex Head Nut'),
('六角法兰带突齿螺栓', 'Hex Flange Serrated Bolt'),
('六角法兰带齿螺栓', 'Hex Flange Toothed Bolt'),
('六角法兰面带突齿螺栓', 'Hex Flange Serrated Bolt'),
('六角薄螺母', 'Hex Thin Nut'),
('六角螺塞', 'Hex Plug'),
('六角螺母', 'Hex Nut'),
('六角螺母（20*1.5）', 'Hex Nut (20*1.5)'),
('六角螺母（发电机用)', 'Hex Nut (for Alternator)'),
('六角螺母（天力)', 'Hex Nut (Tianli)'),
('六角锁紧螺母(110040用)', 'Hex Lock Nut (for 110040)'),
('共轨喷油泵', 'Common Rail Injection Pump'),
('共轨喷油管', 'Common Rail Injection Pipe'),
('共轨支架', 'Common Rail Bracket'),
('共轨管', 'Common Rail'),
('共轨组件', 'Common Rail Module'),
('共轨组件回油管', 'Common Rail Module Return Pipe'),
('内六角圆头螺栓', 'Socket Round Head Bolt'),
('内六角圆柱头螺栓', 'Socket Head Cap Bolt'),
('内六角圆柱头螺钉', 'Socket Head Cap Screw'),
('内六角圆柱螺栓', 'Socket Head Bolt'),
('内六角头螺栓', 'Socket Head Bolt'),
('内六角螺丝', 'Hex Socket Screw'),
('内六角螺塞', 'Socket Hex Plug'),
('内六角螺钉', 'Socket Screw'),
('内六角螺钉Q218B0835TF2', 'Socket Screw Q218B0835TF2'),
('内螺纹圆柱销', 'Internally Threaded Dowel Pin'),
('冲差价', 'Price Difference Adjustment'),
('冷却器盖防水罗塞', 'Cooler Cover Water Plug'),
('冷却器连接胶管', 'Cooler Connecting Rubber Hose'),
('冷却模块总成', 'Cooling Module Assembly'),
('冷却水软管', 'Cooling Water Hose'),
('冷却液弯管（MC11）', 'Coolant Elbow Pipe (MC11)'),
('冷却液管', 'Coolant Pipe'),
('冷却液连接管', 'Coolant Connecting Pipe'),
('冷却液连接胶管', 'Coolant Rubber Hose'),
('减速型起动机', 'Gear-Reduction Starter'),
('减震器', 'Damper'),
('出水接头', 'Water Outlet Joint'),
('出水管', 'Water Outlet Pipe'),
('出水管垫', 'Water Outlet Gasket'),
('出水管垫片', 'Water Outlet Gasket'),
('出水管接头', 'Water Outlet Joint'),
('出水管接管垫片', 'Water Outlet Connection Gasket'),
('出水管法兰', 'Water Outlet Flange'),
('分配壳', 'Distribution Housing'),
('前排气歧管', 'Front Exhaust Manifold'),
('前排气管', 'Front Exhaust Pipe'),
('前排起歧管', 'Front Exhaust Manifold'),
('前支撑板', 'Front Support Plate'),
('前油封', 'Front Oil Seal'),
('前油封垫片', 'Front Oil Seal Gasket'),
('前油封座垫片', 'Front Oil Seal Seat Gasket'),
('前油气分离器', 'Front Oil-Gas Separator'),
('前端盖', 'Front Cover'),
('前脸', 'Front Fascia'),
('前轴承盖', 'Front Bearing Cover'),
('前轴承盖衬垫', 'Front Bearing Cover Gasket'),
('前隔热罩', 'Front Heat Shield'),
('副厂P12排气管密封环', 'Aftermarket P12 Exhaust Seal Ring'),
('副厂排气管密封环', 'Aftermarket Exhaust Pipe Seal Ring'),
('副厂油门球头', 'Aftermarket Throttle Ball Joint'),
('副螺栓丝堵', 'Auxiliary Bolt Plug'),
('加宽曲轴止推片', 'Wide Crankshaft Thrust Washer'),
('加宽机油泵', 'Wide Oil Pump'),
('加机油口盖', 'Oil Fill Cap'),
('加机油短管', 'Oil Fill Short Pipe'),
('加机油短管总成', 'Oil Fill Short Pipe Assembly'),
('加机油短管组件', 'Oil Fill Short Pipe Assembly'),
('加机油管固定螺栓', 'Oil Fill Pipe Fixing Bolt'),
('加机油管垫片', 'Oil Fill Pipe Gasket'),
('加机油管法兰', 'Oil Fill Pipe Flange'),
('加机油管组件', 'Oil Fill Pipe Assembly'),
('加油短管垫片', 'Oil Fill Short Pipe Gasket'),
('加油短管组件', 'Oil Fill Short Pipe Assembly'),
('加油管盖总成', 'Oil Fill Pipe Cap Assembly'),
('加油管组件', 'Oil Fill Pipe Assembly'),
('加热器', 'Heater'),
('加热器垫片', 'Heater Gasket'),
('加重排气管', 'Heavy-Duty Exhaust Pipe'),
('包装箱', 'Packing Box'),
('半圆键', 'Woodruff Key'),
('单向阀', 'Check Valve'),
('单管卡子总成', 'Single Pipe Clamp Assembly'),
('单管管夹总成', 'Single Pipe Clamp Assembly'),
('单缸空压机（带节能系统）', 'Single-Cylinder Air Compressor (with Energy Saving)'),
('卡套', 'Ferrule Sleeve'),
('卡套式直通体', 'Ferrule Type Straight Body'),
('卡套式直通接头', 'Ferrule Type Straight Joint'),
('卡套式端直通接头体', 'Ferrule Type Straight Connector Body'),
('卡套式管接头用螺母', 'Nut for Ferrule Type Joint'),
('卡箍', 'Hose Clamp'),
('卡箍(110-118)', 'Hose Clamp (110-118)'),
('卡箍21-43', 'Hose Clamp 21-43'),
('卡箍带（短）', 'Clamp Band (Short)'),
('卡箍带（长）', 'Clamp Band (Long)'),
('压力传感器', 'Pressure Sensor'),
('压力传感器（带报警）', 'Pressure Sensor (with Alarm)'),
('压套', 'Press Sleeve'),
('压板', 'Press Plate'),
('压气机出气管', 'Compressor Air Outlet Pipe'),
('压气机气管', 'Compressor Air Pipe'),
('压气机进气管', 'Compressor Intake Pipe'),
('压气机进气管组件', 'Compressor Intake Pipe Module'),
('压紧块', 'Pressing Block'),
('压缩机支架(H10.5)', 'AC Compressor Bracket (H10.5)'),
('压缩机支架固定螺栓', 'Compressor Bracket Fixing Bolt'),
('厚垫片', 'Thick Washer'),
('原厂H10机油尺管', 'OEM H10 Dipstick Tube'),
('原厂排气管密封环', 'OEM Exhaust Pipe Seal Ring'),
('原厂排气门', 'OEM Exhaust Valve'),
('原厂机油尺套管总成', 'OEM Dipstick Sleeve Assembly'),
('原厂样件机油尺管总成', 'OEM Sample Dipstick Tube Assembly'),
('原厂气门弹簧上座', 'OEM Valve Spring Upper Seat'),
('原厂气门弹簧下座', 'OEM Valve Spring Lower Seat'),
('原厂油底壳托快', 'OEM Oil Pan Support Block'),
('原厂进气门弹簧下座', 'OEM Intake Valve Spring Lower Seat'),
('原装P12曲轴后油封', 'Genuine P12 Crankshaft Rear Oil Seal'),
('双唇曲轴油封', 'Double-Lip Crankshaft Oil Seal'),
('双头螺柱', 'Double-End Stud'),
('双杆空压机联轴器', 'Double-Rod Air Compressor Coupling'),
('双温控开关', 'Dual Thermostatic Switch'),
('双管夹（φ18）', 'Double Pipe Clamp (φ18)'),
('双管接头', 'Double Pipe Joint'),
('双管管夹', 'Double Pipe Clamp'),
('双级机油泵', 'Two-Stage Oil Pump'),
('双缸空压机', 'Two-Cylinder Air Compressor'),
('双缸空压机修理包', 'Two-Cylinder Air Compressor Repair Kit'),
('双缸空压机出气接头', 'Two-Cylinder Air Compressor Air Outlet Joint'),
('双缸空压机缸盖', 'Two-Cylinder Air Compressor Cylinder Head'),
('双缸空压机缸盖垫片', 'Two-Cylinder Air Compressor Cylinder Head Gasket'),
('双缸空压机阀板总成', 'Two-Cylinder Air Compressor Valve Plate Assembly'),
('双缸空压机阀片', 'Two-Cylinder Air Compressor Valve Plate'),
('双联轴承', 'Double-Row Bearing'),
('发动机全套螺栓', 'Engine Complete Bolt Kit'),
('发动机前右支架', 'Engine Front Right Bracket'),
('发动机前吊板', 'Engine Front Lifting Plate'),
('发动机前吊环', 'Engine Front Lifting Eye'),
('发动机前左支架', 'Engine Front Left Bracket'),
('发动机前支撑', 'Engine Front Support'),
('发动机吊板', 'Engine Lifting Plate'),
('发动机后吊板', 'Engine Rear Lifting Plate'),
('发动机后吊环', 'Engine Rear Lifting Eye'),
('发动机后托架', 'Engine Rear Bracket'),
('发动机后支撑', 'Engine Rear Support'),
('发动机后支撑六角头螺栓', 'Engine Rear Support Hex Bolt'),
('发动机后支撑螺栓', 'Engine Rear Support Bolt'),
('发动机固定支腿', 'Engine Fixing Leg'),
('发动机垫片修理包', 'Engine Gasket Repair Kit'),
('发动机密封圈', 'Engine Seal Ring'),
('发动机密封圈修理包(潍柴）', 'Engine Seal Repair Kit (Weichai)'),
('发动机密封圈修理包（全车）', 'Engine Seal Repair Kit (Complete)'),
('发动机拉紧块', 'Engine Tensioning Block'),
('发动机支架', 'Engine Mount Bracket'),
('发动机支架（右）', 'Engine Mount Bracket (Right)'),
('发动机支架（左）', 'Engine Mount Bracket (Left)'),
('发动机线束密封圈', 'Engine Harness Seal Ring'),
('发动机进气管', 'Engine Intake Pipe'),
('发动机隔热罩', 'Engine Heat Shield'),
('取水接头', 'Water Draw Joint'),
('变径卡箍总成', 'Step-Down Clamp Assembly'),
('变径螺栓', 'Step Bolt'),
('变速箱管夹', 'Gearbox Pipe Clamp'),
('右发动机后支架', 'Right Engine Rear Bracket'),
('右支撑托架总成', 'Right Support Bracket Assembly'),
('右支架', 'Right Bracket'),
('右支架总成', 'Right Bracket Assembly'),
('右橡胶支撑', 'Right Rubber Mount'),
('右油底壳托块', 'Right Oil Pan Support Block'),
('右油底壳托快', 'Right Oil Pan Support Block'),
('右驱力附件', 'Right Drive Unit Accessory'),
('吊板', 'Lifting Plate'),
('吊环夹紧块', 'Lifting Eye Clamping Block'),
('吊环接块', 'Lifting Eye Joint Block'),
('吊环螺钉', 'Lifting Eye Screw'),
('后取力器油封(原厂)', 'Rear PTO Oil Seal (OEM)'),
('后取力总成', 'Rear PTO Assembly'),
('后取力油封', 'Rear PTO Oil Seal'),
('后取力油封(普通)', 'Rear PTO Oil Seal (Standard)'),
('后取力输出轴组件', 'Rear PTO Output Shaft Module'),
('后取力飞轮壳螺栓', 'Rear PTO Flywheel Housing Bolt'),
('后排气歧管', 'Rear Exhaust Manifold'),
('后支撑托架', 'Rear Support Bracket'),
('后支撑支架', 'Rear Support Bracket'),
('后轴承盖', 'Rear Bearing Cover'),
('后轴承盖衬垫', 'Rear Bearing Cover Gasket'),
('后隔热罩', 'Rear Heat Shield'),
('后驱力增压器进油管（后）', 'Rear Drive Turbo Oil Feed Pipe (Rear)'),
('后驱力总成', 'Rear Drive Assembly'),
('后驱力曲轴齿轮', 'Rear Drive Crankshaft Gear'),
('后驱力泵总成', 'Rear Drive Pump Assembly'),
('后驱力润滑油管', 'Rear Drive Lube Oil Pipe'),
('后驱力润滑油管（96厘米）', 'Rear Drive Lube Oil Pipe (96cm)'),
('后驱力盖板', 'Rear Drive Cover Plate'),
('后驱力螺栓', 'Rear Drive Bolt'),
('后驱力输出轴组件', 'Rear Drive Output Shaft Module'),
('后驱力飞轮壳', 'Rear Drive Flywheel Housing'),
('后驱力飞轮螺丝', 'Rear Drive Flywheel Screw'),
('向心球轴承', 'Deep Groove Ball Bearing'),
('吸油管O型圈（28*3）', 'Suction Pipe O-Ring (28*3)'),
('吸油管总成', 'Oil Suction Pipe Assembly'),
('吸油管法兰', 'Oil Suction Pipe Flange'),
('喷嘴组件', 'Nozzle Assembly'),
('喷射阀', 'Injection Valve'),
('喷油嘴', 'Injection Nozzle'),
('回水接头', 'Water Return Joint'),
('回水管', 'Water Return Pipe'),
('回水管接头', 'Water Return Pipe Joint'),
('回油短管', 'Return Short Pipe'),
('回油管', 'Oil Return Pipe'),
('回油管总成', 'Oil Return Pipe Assembly'),
('回油管接头', 'Oil Return Pipe Joint'),
('回油管法兰', 'Return Pipe Flange'),
('回油管法兰垫片', 'Oil Return Pipe Flange Gasket'),
('回油管（限压阀-异径管接头）', 'Return Pipe (Relief Valve-Reducer Joint)'),
('回油连接座', 'Return Oil Connecting Seat'),
('固定支架', 'Fixing Bracket'),
('固定板', 'Fixing Plate'),
('固定起动机螺栓', 'Starter Fixing Bolt'),
('国V排气门座圈MT13', 'China-V Exhaust Valve Seat MT13'),
('国V进气门座圈MT13', 'China-V Intake Valve Seat MT13'),
('国五火花塞', 'China-V Spark Plug'),
('国五点火线圈总成', 'China-V Ignition Coil Assembly'),
('国六EGR出气管总成', 'China-VI EGR Outlet Pipe Assembly'),
('国六火花塞', 'China-VI Spark Plug'),
('国六点火线圈总成', 'China-VI Ignition Coil Assembly'),
('国六节温器芯', 'China-VI Thermostat Element'),
('国四D10发动机螺栓', 'China-IV D10 Engine Bolt'),
('国四ECU支撑板', 'China-IV ECU Support Plate'),
('国四排气管', 'China-IV Exhaust Pipe'),
('国四燃油管', 'China-IV Fuel Pipe'),
('国四空压机密封圈', 'China-IV Air Compressor Seal Ring'),
('国四空压机接头', 'China-IV Air Compressor Joint'),
('国四空压机进气管', 'China-IV Air Compressor Intake Pipe'),
('国四缸盖罩衬垫', 'China-IV Cylinder Head Cover Gasket'),
('国四节温器芯', 'China-IV Thermostat Element'),
('圆柱滚子轴承', 'Cylindrical Roller Bearing'),
('圆柱滚子轴承NJ208', 'Cylindrical Roller Bearing NJ208'),
('圆柱销', 'Dowel Pin'),
('圆柱销(Q5210820)', 'Dowel Pin (Q5210820)'),
('垫块', 'Pad Block'),
('堵塞', 'Plug'),
('堵头', 'Plug Head'),
('堵盖', 'Plug Cover'),
('复合垫片', 'Composite Washer'),
('多契带', 'Poly-V Belt'),
('多楔带', 'Poly-V Belt'),
('多軔带', 'Poly-V Belt'),
('多韧带', 'Poly-V Belt'),
('大卡环（拉式）6爪', 'Large Circlip (Pull Type) 6-Claw'),
('大口油气分离器组件', 'Large-Inlet Oil-Gas Separator Assembly'),
('大圆连接片', 'Large Round Connecting Plate'),
('大垫圈', 'Large Washer'),
('天方地圆', 'Round-to-Square Adapter'),
('天然气气门油封', 'Natural Gas Valve Stem Seal'),
('天然气滤芯', 'Natural Gas Filter Element'),
('天然气盖板', 'Natural Gas Cover Plate'),
('天然气缸盖罩密封圈', 'Natural Gas Cylinder Head Cover Seal Ring'),
('夹紧块', 'Clamping Block'),
('套筒', 'Sleeve'),
('奥威排气管', 'Aowei Exhaust Pipe'),
('孔用弹性挡圈', 'Circlip for Hole'),
('孔用弹性挡圈62*2', 'Circlip for Hole 62*2'),
('安全阀', 'Safety Valve'),
('安全阀弹簧', 'Safety Valve Spring'),
('安全阀螺塞', 'Safety Valve Plug'),
('定位套', 'Locating Sleeve'),
('定位销', 'Locating Pin'),
('客车出水管', 'Coach Water Outlet Pipe'),
('客车机滤器垫片', 'Coach Oil Filter Gasket'),
('客车水泵总成', 'Coach Water Pump Assembly'),
('客车空压机进水管', 'Coach Air Compressor Water Inlet Pipe'),
('客车缸盖出水管', 'Coach Head Water Outlet Pipe'),
('客车节温器芯', 'Coach Thermostat Element'),
('客车飞轮壳螺栓', 'Coach Flywheel Housing Bolt'),
('小圆连接片', 'Small Round Connecting Plate'),
('小底盘气门油封', 'Small Chassis Valve Stem Seal'),
('尿素喷嘴支撑块', 'Urea Nozzle Support Block'),
('尿素管接头', 'Urea Pipe Joint'),
('尿素箱回水管接头', 'Urea Tank Water Return Joint'),
('尿素箱拉紧带', 'Urea Tank Tensioning Strap'),
('尿素调节螺栓', 'Urea Adjusting Bolt'),
('工程机械增压器回油管', 'Construction Machinery Turbo Oil Return Pipe'),
('工程机械接管', 'Construction Machinery Connecting Pipe'),
('工程机械支撑块', 'Construction Machinery Support Block'),
('工程机械曲轴法兰', 'Construction Machinery Crankshaft Flange'),
('工程机械柴滤支架', 'Machinery Diesel Filter Bracket'),
('工程机械燃油管', 'Construction Machinery Fuel Pipe'),
('工程机械空压机水管', 'Machinery Air Compressor Water Pipe'),
('工程机械节温器壳', 'Machinery Thermostat Housing'),
('工程机械进气接管', 'Construction Machinery Intake Connection'),
('左发动机后支架', 'Left Engine Rear Bracket'),
('左支撑托架总成', 'Left Support Bracket Assembly'),
('左支架', 'Left Bracket'),
('左支架总成', 'Left Bracket Assembly'),
('左橡胶支撑', 'Left Rubber Mount'),
('左油底壳托块', 'Left Oil Pan Support Block'),
('左油底壳托快', 'Left Oil Pan Support Block'),
('差速器壳（0166）', 'Differential Housing (0166)'),
('差速器总成', 'Differential Assembly'),
('带凸齿的孔用挡圈', 'Toothed Circlip for Hole'),
('带泵柴滤座', 'Diesel Filter Seat with Pump'),
('带纤维夹层橡胶软管', 'Rubber Hose with Fabric Insert'),
('带纤维夹层的橡胶软管', 'Rubber Hose with Fabric Insert'),
('带肩六角头螺栓', 'Shoulder Hex Bolt'),
('带肩空心螺栓', 'Shoulder Hollow Bolt'),
('带肩螺母', 'Shoulder Nut'),
('带肩飞轮螺栓', 'Shoulder Flywheel Bolt'),
('平槽惰轮120022', 'Flat Groove Idler Pulley 120022'),
('平衡轴螺丝', 'Balance Shaft Screw'),
('平键', 'Parallel Key'),
('废气制动停油缸', 'Exhaust Brake Fuel Cut-Off Cylinder'),
('废气控制阀管', 'Exhaust Control Valve Pipe'),
('废气放气控制阀', 'Exhaust Waste Gate Control Valve'),
('废气旁通阀出气管', 'Waste Gate Outlet Pipe'),
('废气旁通阀进气管', 'Waste Gate Intake Pipe'),
('废气涡轮增压器', 'Exhaust Gas Turbocharger'),
('异型接头', 'Special-Shaped Joint'),
('张紧板', 'Tensioning Plate'),
('张紧轮', 'Tensioner'),
('张紧轮座（三孔）', 'Tensioner Seat (3-Hole)'),
('张紧轮支撑板', 'Tensioner Support Plate'),
('弯管', 'Elbow Pipe'),
('弹性圆柱销', 'Spring Dowel Pin'),
('弹性圆柱销-直槽重型', 'Spring Dowel Pin - Straight Slot Heavy Duty'),
('弹性挡圈（后驱力）', 'Circlip (Rear Drive Unit)'),
('弹性波形垫圈', 'Elastic Wave Washer'),
('弹性连接片', 'Elastic Connecting Plate'),
('心组件20152', 'Core Module 20152'),
('心组件四配套', 'Core Module Four-Piece Kit'),
('快插接头体', 'Quick Plug Joint Body'),
('悬臂总成', 'Cantilever Assembly'),
('惰性齿轮（42齿）', 'Idler Gear (42 Teeth)'),
('惰性齿轮（45齿）', 'Idler Gear (45 Teeth)'),
('惰轮', 'Idler Pulley'),
('惰轮120049', 'Idler Pulley 120049'),
('惰轮总成', 'Idler Pulley Assembly'),
('惰轮支架', 'Idler Pulley Bracket'),
('惰轮螺栓', 'Idler Pulley Bolt'),
('惰轮轴', 'Idler Pulley Shaft'),
('惰齿轮总成', 'Idler Gear Assembly'),
('惰齿轮支架', 'Idler Gear Bracket'),
('成型胶管', 'Molded Rubber Hose'),
('手油泵', 'Hand Fuel Pump'),
('扎带', 'Cable Tie'),
('托架总成', 'Bracket Assembly'),
('护风圈支架', 'Fan Shroud Bracket'),
('护风带总成', 'Fan Shroud Strip Assembly'),
('护风帽', 'Fan Shroud Cap'),
('护风罩', 'Fan Shroud'),
('护风罩总成', 'Fan Shroud Assembly'),
('护风罩支架', 'Fan Shroud Bracket'),
('拉紧块', 'Tensioning Block'),
('拉紧垫块', 'Tensioning Pad Block'),
('拉紧螺栓', 'Tensioning Bolt'),
('拉进螺栓', 'Tensioning Bolt'),
('拉铆钉', 'Blind Rivet'),
('挡板', 'Baffle Plate'),
('挡油盘', 'Oil Baffle Plate'),
('排气制动', 'Exhaust Brake'),
('排气制动卡箍', 'Exhaust Brake Clamp'),
('排气尾管总成', 'Exhaust Tail Pipe Assembly'),
('排气弯管', 'Exhaust Elbow Pipe'),
('排气接头', 'Exhaust Joint'),
('排气接管', 'Exhaust Connection Pipe'),
('排气摇臂组件', 'Exhaust Rocker Module'),
('排气过渡弯管', 'Exhaust Transition Elbow'),
('排气门', 'Exhaust Valve'),
('排气门MT13', 'Exhaust Valve MT13'),
('排气门座', 'Exhaust Valve Seat'),
('排气门弹簧', 'Exhaust Valve Spring'),
('排气门弹簧下座', 'Exhaust Valve Spring Lower Seat'),
('排气门挺住总成', 'Exhaust Valve Tappet Assembly'),
('排气门摇臂', 'Exhaust Valve Rocker Arm'),
('排气门摇臂总成', 'Exhaust Valve Rocker Arm Assembly'),
('排气门桥', 'Exhaust Valve Bridge'),
('排气门桥组件', 'Exhaust Valve Bridge Assembly'),
('排气门油封', 'Exhaust Valve Stem Seal'),
('摇臂座', 'Rocker Arm Seat'),
('摇臂座组件', 'Rocker Seat Module'),
('摇臂弹簧螺丝', 'Rocker Arm Spring Screw'),
('摇臂总成', 'Rocker Arm Assembly'),
('摇臂支架', 'Rocker Arm Bracket'),
('摇臂电磁阀总成', 'Rocker Arm Solenoid Assembly'),
('摇臂短螺丝', 'Rocker Arm Short Screw'),
('摇臂罩上罩', 'Rocker Cover Upper Shield'),
('摇臂罩下罩', 'Rocker Cover Lower Shield'),
('摇臂罩下罩总成', 'Rocker Cover Lower Shield Assembly'),
('摇臂罩下罩衬垫', 'Rocker Cover Lower Shield Gasket'),
('摇臂罩支撑块', 'Rocker Cover Support Block'),
('摇臂罩衬垫', 'Rocker Cover Gasket'),
('摇臂轴', 'Rocker Arm Shaft'),
('摇臂轴座总成', 'Rocker Arm Shaft Seat Assembly'),
('摇臂轴支架', 'Rocker Arm Shaft Bracket'),
('支撑快（P7缸盖罩）', 'Support Block (P7 Head Cover)'),
('支撑杆总成', 'Support Rod Assembly'),
('支撑板', 'Support Plate'),
('支撑架（一）', 'Support Bracket (1)'),
('支撑架（三）', 'Support Bracket (3)'),
('支撑架（二）', 'Support Bracket (2)'),
('支撑架（四）', 'Support Bracket (4)'),
('支撑环', 'Support Ring'),
('支撑臂', 'Support Arm'),
('改装15335', 'Modification 15335'),
('放气管', 'Air Bleed Pipe'),
('放气管总成', 'Air Bleed Pipe Assembly'),
('放气阀增压器', 'Turbocharger with Bleed Valve'),
('放水阀', 'Drain Valve'),
('放水阀总成', 'Water Drain Valve Assembly'),
('新式节温器总成80℃', 'New Type Thermostat Assembly 80℃'),
('方向盘', 'Steering Wheel'),
('方形錐螺塞Q614B06', 'Square Taper Plug Q614B06'),
('施必牢螺母', 'Anti-Loosening Nut (SPILock)'),
('旁通阀出气管', 'Bypass Outlet Pipe'),
('旋入接头', 'Screw-In Joint'),
('旋装式燃油粗滤器虑座', 'Spin-on Fuel Primary Filter Seat'),
('旋装式燃油精滤器', 'Spin-on Fuel Fine Filter'),
('旋装式燃油精滤清器总成', 'Spin-on Fuel Fine Filter Assembly'),
('旋转式机油滤芯总成', 'Spin-on Oil Filter Assembly'),
('旋转式燃油粗滤器总成', 'Spin-on Fuel Primary Filter Assembly'),
('无纤维夹层橡胶软管', 'Rubber Hose without Fabric Insert'),
('无纤维夹层的橡胶软管', 'Rubber Hose without Fabric Insert'),
('暖风减压阀出水胶管', 'Heater PRV Outlet Rubber Hose'),
('暖风出水钢管', 'Heater Water Outlet Steel Pipe'),
('暖风发动机出水管', 'Heater Engine Water Outlet Pipe'),
('暖风发动机回水钢管', 'Heater Engine Return Steel Pipe'),
('暖风回水管接头', 'Heater Water Return Joint'),
('暖风开关', 'Heater Switch'),
('暖风接口', 'Heater Port'),
('暖风接头', 'Heater Joint'),
('暖风接头（丝24）', 'Heater Joint (Thread 24)'),
('暖风水管支架', 'Heater Water Pipe Bracket'),
('暖风过渡接头', 'Heater Adapter Joint'),
('暖风驾驶室回水胶管', 'Heater Cab Water Return Rubber Hose'),
('暖风驾驶室进水胶管', 'Heater Cab Water Inlet Rubber Hose'),
('曼11/13集滤器总成', 'MAN 11/13 Oil Strainer Assembly'),
('曼MC11机滤芯', 'MAN MC11 Oil Filter Element'),
('曼MC11柴滤芯', 'MAN MC11 Diesel Filter Element'),
('曼增压器回油管', 'MAN Turbo Oil Return Pipe'),
('曼惰轮', 'MAN Idler Pulley'),
('曼机油尺上头', 'MAN Dipstick Upper Head'),
('曼水堵（φ25）', 'MAN Water Core Plug (φ25)'),
('曼水堵（φ32）', 'MAN Water Core Plug (φ32)'),
('曼水堵（φ45）', 'MAN Water Core Plug (φ45)'),
('机油冷却器', 'Oil Cooler'),
('机油冷却器(8片)', 'Oil Cooler (8-Plate)'),
('机油冷却器垫', 'Oil Cooler Gasket'),
('机油冷却器垫片', 'Oil Cooler Gasket'),
('机油冷却器总成', 'Oil Cooler Assembly'),
('机油冷却器盖', 'Oil Cooler Cover'),
('机油冷却器盖垫片', 'Oil Cooler Cover Gasket'),
('机油冷却器盖接头', 'Oil Cooler Cover Joint'),
('机油冷却器芯', 'Oil Cooler Core'),
('机油冷却器（8片）', 'Oil Cooler (8-Plate)'),
('机油冷却汽器盖片', 'Oil Cooler Cover Plate'),
('机油加油管', 'Oil Fill Pipe'),
('机油压力传感器', 'Oil Pressure Sensor'),
('机油压力传感器座', 'Oil Pressure Sensor Bracket'),
('机油压力传感器接头', 'Oil Pressure Sensor Joint'),
('机油压力感应塞', 'Oil Pressure Sensor'),
('机油压力温度传感器', 'Oil Pressure & Temperature Sensor'),
('机油喷嘴', 'Oil Nozzle'),
('机油喷嘴组件', 'Oil Nozzle Assembly'),
('机油喷嘴铜垫', 'Oil Nozzle Copper Washer'),
('机油散热器', 'Oil Radiator'),
('机油标尺橡胶软管', 'Oil Dipstick Rubber Hose'),
('机油模块', 'Oil Module'),
('机油模块密封垫', 'Oil Module Gasket'),
('机油模块改装修理包', 'Oil Module Modification Repair Kit'),
('机滤器', 'Oil Filter'),
('机滤器总成', 'Oil Filter Assembly'),
('机滤器托架', 'Oil Filter Bracket'),
('机滤座', 'Oil Filter Bracket'),
('机滤座固定螺栓', 'Oil Filter Bracket Fixing Bolt'),
('机滤座总成', 'Oil Filter Seat Assembly'),
('机电式机油压力传感器', 'Electromechanical Oil Pressure Sensor'),
('柴机油（18L）', 'Diesel Engine Oil (18L)'),
('柴油温度传感器', 'Diesel Temperature Sensor'),
('柴油滤杯', 'Diesel Filter Bowl'),
('柴油滤清器盖', 'Diesel Filter Cover'),
('柴油滤芯', 'Diesel Filter Element'),
('柴油滤芯总成', 'Diesel Filter Element Assembly'),
('柴油滤芯（粗）', 'Diesel Filter Element (Primary)'),
('柴油滤芯（细）', 'Diesel Filter Element (Fine)'),
('柴虑溢油阀', 'Diesel Filter Overflow Valve'),
('桥壳双头栓', 'Axle Housing Stud'),
('桥壳双头螺栓', 'Axle Housing Stud'),
('桥壳磁性螺塞', 'Axle Housing Magnetic Plug'),
('模块转子', 'Module Rotor'),
('橡胶块', 'Rubber Block'),
('橡胶套', 'Rubber Sleeve'),
('橡胶支座总成', 'Rubber Mount Assembly'),
('橡胶管', 'Rubber Hose'),
('橡胶软管', 'Rubber Hose'),
('橡胶软管（耐低温）', 'Rubber Hose (Low Temperature Resistant)'),
('欧II/P10/618油底壳机油泵螺丝包', 'Euro-II/P10/618 Oil Pan Pump Screw Kit'),
('欧II全套圆柱销', 'Euro-II Complete Dowel Pin Set'),
('欧II发动机密封圈修理包', 'Euro-II Engine Seal Repair Kit'),
('欧II曲轴前油封', 'Euro-II Crankshaft Front Oil Seal'),
('欧II曲轴后油封', 'Euro-II Crankshaft Rear Oil Seal'),
('欧II柴滤支架螺栓', 'Euro-II Diesel Filter Bracket Bolt'),
('欧II缸盖组装明细', 'Euro-II Head Assembly List'),
('欧II缸盖螺栓', 'Euro-II Cylinder Head Bolt'),
('欧II进气管固定螺栓', 'Euro-II Intake Pipe Fixing Bolt'),
('欧II齿轮室固定螺栓', 'Euro-II Gear Housing Fixing Bolt'),
('止推垫圈', 'Thrust Washer'),
('正时齿轮室', 'Timing Gear Housing'),
('气制动总阀', 'Air Brake Master Valve'),
('气泵螺旋管（09款)', 'Air Pump Spiral Pipe (09 Model)'),
('气泵轴垫片', 'Air Pump Shaft Washer'),
('气泵轴承206', 'Air Pump Bearing 206'),
('气泵轴承6306', 'Air Pump Bearing 6306'),
('气泵轴承（2207）', 'Air Pump Bearing (2207)'),
('气泵轴承（7207B）', 'Air Pump Bearing (7207B)'),
('气泵轴螺母（头）', 'Air Pump Shaft Nut (Front)'),
('气泵铁管（电喷）', 'Air Pump Steel Pipe (EFI)'),
('气泵齿轮支承环', 'Air Pump Gear Support Ring'),
('气泵齿轮（小）', 'Air Pump Gear (Small)'),
('气管帽', 'Air Pipe Cap'),
('气管总成', 'Air Pipe Assembly'),
('气管接头', 'Air Pipe Joint'),
('气缸垫', 'Cylinder Head Gasket'),
('气罐手动放水阀', 'Air Tank Manual Drain Valve'),
('气路接头', 'Air Line Joint'),
('气路连接管', 'Air Line Connecting Pipe'),
('气路连接胶管', 'Air Line Rubber Hose'),
('氧传感器', 'Oxygen Sensor'),
('水冷增压器进水管', 'Water-Cooled Turbo Water Inlet Pipe'),
('水冷空压机', 'Water-Cooled Air Compressor'),
('水堵', 'Water Core Plug'),
('水堵17', 'Water Core Plug 17'),
('水堵22', 'Water Core Plug 22'),
('水堵25', 'Water Core Plug 25'),
('水堵30', 'Water Core Plug 30'),
('水堵40', 'Water Core Plug 40'),
('水堵45', 'Water Core Plug 45'),
('水堵60', 'Water Core Plug 60'),
('水堵75', 'Water Core Plug 75'),
('水堵（18*7.3）', 'Water Core Plug (18*7.3)'),
('水寒宝', 'Fuel Water Separator'),
('水封', 'Water Seal'),
('水温传感器', 'Water Temperature Sensor'),
('水温传感器（大）', 'Water Temperature Sensor (Large)'),
('水温传感器（小）', 'Water Temperature Sensor (Small)'),
('水温表', 'Water Temperature Gauge'),
('水温表传感器（带报警）', 'Water Temperature Gauge Sensor (with Alarm)'),
('汽缸体', 'Cylinder Block'),
('汽缸垫', 'Cylinder Head Gasket'),
('汽缸垫（两气门）', 'Cylinder Head Gasket (2-Valve)'),
('汽缸套', 'Cylinder Liner'),
('汽缸盖', 'Cylinder Head'),
('汽缸盖主螺栓', 'Cylinder Head Main Bolt'),
('汽缸盖总成', 'Cylinder Head Assembly'),
('汽缸盖罩盖板', 'Cylinder Head Cover Plate'),
('汽缸盖（P12）', 'Cylinder Head (P12)'),
('沉头螺栓（V1.94）', 'Countersunk Bolt (V1.94)'),
('油嘴', 'Oil Nozzle'),
('油孔堵塞', 'Oil Hole Plug'),
('油尺管上组件', 'Dipstick Tube Upper Assembly'),
('油尺管下组件', 'Dipstick Tube Lower Assembly'),
('油尺管头', 'Dipstick Tube Head'),
('油尺芯', 'Dipstick Core'),
('油标尺', 'Oil Dipstick'),
('油气预分离器', 'Oil-Gas Pre-Separator'),
('油泵回油管', 'Oil Pump Return Pipe'),
('油泵托架', 'Oil Pump Bracket'),
('油泵法兰密封圈', 'Oil Pump Flange Seal Ring'),
('油箱盖（原厂）', 'Fuel Tank Cap (OEM)'),
('油箱盖（普通）', 'Fuel Tank Cap (Standard)'),
('油路连接胶管', 'Oil Line Rubber Hose'),
('油门位置传感器', 'Throttle Position Sensor'),
('油门卡簧', 'Throttle Circlip'),
('油门弹簧', 'Throttle Spring'),
('油门悬臂', 'Throttle Bellcrank'),
('油门悬臂总成', 'Throttle Bellcrank Assembly'),
('油门杠杆', 'Throttle Lever'),
('油门杠杆总成', 'Throttle Lever Assembly'),
('油门杠杆螺母', 'Throttle Lever Nut'),
('油门杠杆衬套', 'Throttle Lever Bushing'),
('油门杠杆限位螺钉', 'Throttle Lever Limit Screw'),
('油门球头', 'Throttle Ball Joint'),
('油门踏板', 'Throttle Pedal'),
('波形弹性垫圈', 'Wave Elastic Washer'),
('波浪轴卡簧', 'Wave Shaft Circlip'),
('波浪轴挡圈', 'Wave Shaft Retaining Ring'),
('波纹管', 'Bellows'),
('波许喷油泵托架', 'Bosch Injection Pump Bracket'),
('消声器支架', 'Muffler Bracket'),
('润滑油回油管总成', 'Lube Oil Return Pipe Assembly'),
('润滑油回油管组件', 'Lube Oil Return Pipe Module'),
('润滑油管', 'Lube Oil Pipe'),
('润滑油管(带弯)', 'Lube Oil Pipe (Bent)'),
('润滑油管(带弯）', 'Lube Oil Pipe (Bent)'),
('润滑油管总成', 'Lube Oil Pipe Assembly'),
('润滑油管（后驱力）', 'Lube Oil Pipe (Rear Drive Unit)'),
('润滑油管（带弯）', 'Lube Oil Pipe (Bent)'),
('润滑油进油管组件', 'Lube Oil Inlet Pipe Module'),
('涨紧轮', 'Tensioner Pulley'),
('涨紧轮座', 'Tensioner Seat'),
('涨紧轮座（四孔）', 'Tensioner Seat (4-Hole)'),
('涨紧轮支座', 'Tensioner Bracket Seat'),
('涨紧轮支架', 'Tensioner Bracket'),
('涨紧轮螺丝包', 'Tensioner Screw Kit'),
('液压泵', 'Hydraulic Pump'),
('液压泵盖板', 'Hydraulic Pump Cover Plate'),
('混合器接头', 'Mixer Joint'),
('混合器支架', 'Mixer Bracket'),
('温度传感器', 'Temperature Sensor'),
('温度压力传感器', 'Temperature & Pressure Sensor'),
('温控开关', 'Thermostatic Switch'),
('滚轮总成', 'Roller Assembly'),
('潍柴615排气管增压器螺栓', 'Weichai 615 Exhaust-Turbo Bolt'),
('潍柴615油泵固定螺栓', 'Weichai 615 Oil Pump Fixing Bolt'),
('潍柴615空压机螺栓', 'Weichai 615 Air Compressor Bolt'),
('潍柴615空心螺栓', 'Weichai 615 Hollow Bolt'),
('潍柴WEVB缸盖明细表', 'Weichai WEVB Head Detail List'),
('潍柴中缸螺丝', 'Weichai Mid-Cylinder Screw'),
('潍柴后驱力螺栓包', 'Weichai Rear Drive Bolt Kit'),
('潍柴欧2全机螺栓', 'Weichai Euro-2 Complete Engine Bolt Kit'),
('潍柴欧II发电机螺栓', 'Weichai Euro-II Alternator Bolt'),
('潍柴欧II燃油管(直)', 'Weichai Euro-II Fuel Pipe (Straight)'),
('潍柴欧II燃油管（弯）', 'Weichai Euro-II Fuel Pipe (Bent)'),
('潍柴欧II空压机盖涨紧轮', 'Weichai Euro-II Air Compressor Cover Tensioner'),
('火焰预热电热塞', 'Flame Preheating Glow Plug'),
('火焰预热电磁阀', 'Flame Preheating Solenoid Valve'),
('火花塞衬套', 'Spark Plug Bushing'),
('点火线圈垫块', 'Ignition Coil Pad Block'),
('点火线圈总成', 'Ignition Coil Assembly'),
('点火线圈衬套压板', 'Ignition Coil Bushing Plate'),
('热交换器出水管', 'Heat Exchanger Water Outlet Pipe'),
('热交换器到节温器水管', 'Heat Exchanger-to-Thermostat Water Pipe'),
('热交换器取水管', 'Heat Exchanger Water Draw Pipe'),
('热交换器回水管', 'Heat Exchanger Water Return Pipe'),
('热交换器水管接座', 'Heat Exchanger Water Pipe Seat'),
('燃气接头', 'Gas Joint'),
('燃气管', 'Gas Pipe'),
('燃油压力传感器', 'Fuel Pressure Sensor'),
('燃油回油管总成', 'Fuel Return Pipe Assembly'),
('燃油回油管总成(10.5)', 'Fuel Return Pipe Assembly (10.5)'),
('燃油水寒宝', 'Fuel Water Separator'),
('燃油温度传感器座', 'Fuel Temperature Sensor Seat'),
('燃油滤总成', 'Fuel Filter Assembly'),
('燃油滤托架', 'Fuel Filter Bracket'),
('燃油滤托架总成', 'Fuel Filter Bracket Assembly'),
('燃油滤清器总成', 'Fuel Filter Assembly'),
('燃油滤清器支架', 'Fuel Filter Bracket'),
('燃油滤清器盖', 'Fuel Filter Cover'),
('燃油滤清器（无手油泵升级滤芯）', 'Fuel Filter (Upgrade Element without Hand Pump)'),
('燃油粗滤器', 'Fuel Primary Filter'),
('燃油粗滤器总成', 'Fuel Primary Filter Assembly'),
('燃油粗滤器护套', 'Fuel Primary Filter Protective Cover'),
('燃油粗滤器滤芯', 'Fuel Primary Filter Element'),
('燃油粗滤芯', 'Fuel Primary Filter Element'),
('燃油精滤器总成', 'Fuel Fine Filter Assembly'),
('燃油精滤器虑座', 'Fuel Fine Filter Seat'),
('燃油精滤芯', 'Fuel Fine Filter Element'),
('燃油细滤器支架总成', 'Fuel Fine Filter Bracket Assembly'),
('燃油进油管', 'Fuel Feed Pipe'),
('燃油进油管总成', 'Fuel Feed Pipe Assembly'),
('燃油进油管总成/粗滤-喷油泵', 'Fuel Feed Pipe / Primary Filter-Injection Pump'),
('燃油进油管总成/粗滤-输油泵', 'Fuel Feed Pipe / Primary Filter-Feed Pump'),
('燃油进油管（H10.5）', 'Fuel Feed Pipe (H10.5)'),
('环形风扇叶', 'Ring Fan Blade'),
('环状弹簧内圈', 'Ring Spring Inner Ring'),
('环状弹簧外圈', 'Ring Spring Outer Ring'),
('球面垫圈', 'Spherical Washer'),
('电子式机油压力传感器', 'Electronic Oil Pressure Sensor'),
('电子油门踏板', 'Electronic Throttle Pedal'),
('电子节气门', 'Electronic Throttle'),
('电控EGR气缸', 'Electronic EGR Cylinder'),
('电控EGR气缸总成', 'Electronic EGR Cylinder Assembly'),
('电控单元组件', 'Electronic Control Unit Module'),
('电控硅油风扇', 'Electronically Controlled Viscous Fan'),
('电控硅油风扇离合器', 'Electronically Controlled Viscous Fan Clutch'),
('电磁硅油离合器', 'Electromagnetic Viscous Clutch'),
('电磁离合器线束', 'Electromagnetic Clutch Wiring Harness'),
('电磁阀', 'Solenoid Valve'),
('盖板', 'Cover Plate'),
('盖片', 'Cover Plate'),
('相位传感器', 'Phase Sensor'),
('石棉排气管垫', 'Asbestos Exhaust Gasket'),
('硅油减振器', 'Viscous Damper'),
('硅油减震器', 'Viscous Damper'),
('硅油离合器风扇', 'Viscous Clutch Fan'),
('硅油风扇离合器', 'Viscous Fan Clutch'),
('碗型堵塞', 'Bowl-Type Core Plug'),
('碗行塞17×7.3', 'Core Plug 17×7.3'),
('碗行环', 'Core Plug Ring'),
('磁性螺塞', 'Magnetic Plug'),
('磁性螺塞总成', 'Magnetic Plug Assembly'),
('离合器液压油管', 'Clutch Hydraulic Pipe'),
('离心式滤清器滤芯', 'Centrifugal Filter Element'),
('空压机', 'Air Compressor'),
('空压机上水管', 'Air Compressor Water Feed Pipe'),
('空压机传动轴', 'Air Compressor Drive Shaft'),
('空压机传动轴螺母', 'Air Compressor Drive Shaft Nut'),
('空压机传动轴螺母（中）', 'Air Compressor Drive Shaft Nut (Middle)'),
('空压机修理包', 'Air Compressor Repair Kit'),
('空压机冷却回水管', 'Air Compressor Cooling Return Pipe'),
('空压机冷却水管', 'Air Compressor Cooling Water Pipe'),
('空压机出气接头', 'Air Compressor Air Outlet Joint'),
('空压机出气管接头', 'Air Compressor Air Outlet Joint'),
('空压机出水管', 'Air Compressor Water Outlet Pipe'),
('空压机出水管接头', 'Air Compressor Water Outlet Joint'),
('空压机出水管（带螺母）', 'Air Compressor Water Outlet Pipe (with Nut)'),
('空压机压紧圈', 'Air Compressor Pressing Ring'),
('空压机压紧块', 'Air Compressor Pressing Block'),
('空压机回水管', 'Air Compressor Return Water Pipe'),
('空压机回水管总成', 'Air Compressor Return Water Pipe Assembly'),
('空压机回水管（带卡套螺母）', 'Air Compressor Return Water Pipe (with Ferrule Nut)'),
('空压机回水管（新式）', 'Air Compressor Return Water Pipe (New Type)'),
('空压机垫片', 'Air Compressor Gasket'),
('空压机总成', 'Air Compressor Assembly'),
('空压机排气接头', 'Air Compressor Exhaust Joint'),
('空压机接头', 'Air Compressor Joint'),
('空压机接头螺母', 'Air Compressor Joint Nut'),
('空压机支架', 'Air Compressor Bracket'),
('空压机水管', 'Air Compressor Water Pipe'),
('空压机水管总成', 'Air Compressor Water Pipe Assembly'),
('空压机水管接头(弯）', 'Air Compressor Water Pipe Joint (Bent)'),
('空压机水管（带卡套螺母）', 'Air Compressor Water Pipe (with Ferrule Nut)'),
('空压机油封座', 'Air Compressor Oil Seal Seat'),
('空压机活塞', 'Air Compressor Piston'),
('空压机活塞环', 'Air Compressor Piston Ring'),
('空压机活塞环（75）', 'Air Compressor Piston Ring (75)'),
('空压机活塞肖', 'Air Compressor Piston Pin'),
('空压机活塞肖卡簧', 'Air Compressor Piston Pin Circlip'),
('空压机润滑油管', 'Air Compressor Lube Oil Pipe'),
('空压机盖体', 'Air Compressor Cover Body'),
('空压机盖涨紧轮固定螺栓', 'Air Compressor Cover Tensioner Fixing Bolt'),
('空压机管接头', 'Air Compressor Pipe Joint'),
('空压机缸体', 'Air Compressor Cylinder Block'),
('空压机缸盖', 'Air Compressor Cylinder Head'),
('空压机缸盖总成', 'Air Compressor Cylinder Head Assembly'),
('空压机胶管', 'Air Compressor Rubber Hose'),
('空压机轴油封', 'Air Compressor Shaft Oil Seal'),
('空压机轴油封（双缸）', 'Air Compressor Shaft Oil Seal (Two-Cylinder)'),
('空压机轴油封（小）', 'Air Compressor Shaft Oil Seal (Small)'),
('空压机进气接头', 'Air Compressor Intake Joint'),
('空压机进气管', 'Air Compressor Intake Pipe'),
('空压机进气管总成', 'Air Compressor Intake Pipe Assembly'),
('空压机进气管接头', 'Air Compressor Intake Joint'),
('空压机进水管', 'Air Compressor Water Inlet Pipe'),
('空压机进水管总成', 'Air Compressor Water Inlet Pipe Assembly'),
('空压机进水管接头', 'Air Compressor Water Inlet Joint'),
('空压机进水管接头（带螺母）', 'Air Compressor Water Inlet Joint (with Nut)'),
('空压机进水管组件', 'Air Compressor Water Inlet Pipe Module'),
('空压机进水管（带螺母）', 'Air Compressor Water Inlet Pipe (with Nut)'),
('空压机进油管', 'Air Compressor Oil Inlet Pipe'),
('空压机阀板', 'Air Compressor Valve Plate'),
('空压机齿轮', 'Air Compressor Gear'),
('空压机齿轮(小）', 'Air Compressor Gear (Small)'),
('空压机齿轮/28齿', 'Air Compressor Gear / 28 Teeth'),
('空压机齿轮盖', 'Air Compressor Gear Cover'),
('空压机齿轮盖垫片', 'Air Compressor Gear Cover Gasket'),
('空压机齿轮（小）', 'Air Compressor Gear (Small)'),
('空压机（老式）', 'Air Compressor (Old Type)'),
('空气管', 'Air Pipe'),
('空气管接头', 'Air Pipe Joint'),
('空气软管', 'Air Hose'),
('空气过渡接管', 'Air Transition Pipe'),
('空芯接头', 'Hollow Joint'),
('空芯螺栓(A6.3)', 'Hollow Bolt (A6.3)'),
('空调压缩机支架', 'AC Compressor Bracket'),
('端盖', 'End Cover'),
('第1缸高压油管', 'No.1 Cylinder High Pressure Pipe'),
('第2缸高压油管', 'No.2 Cylinder High Pressure Pipe'),
('第3缸高压油管', 'No.3 Cylinder High Pressure Pipe'),
('第4缸高压油管', 'No.4 Cylinder High Pressure Pipe'),
('第5缸高压油管', 'No.5 Cylinder High Pressure Pipe'),
('第6缸高压油管', 'No.6 Cylinder High Pressure Pipe'),
('管夹', 'Pipe Clamp'),
('管夹总成', 'Pipe Clamp Assembly'),
('管夹总成(96830管)', 'Pipe Clamp Assembly (96830 Pipe)'),
('管子总成', 'Pipe Assembly'),
('管接螺母', 'Pipe Joint Nut'),
('粗滤器', 'Primary Filter'),
('粗滤器-输油泵燃油管总成', 'Primary Filter-Feed Pump Fuel Pipe Assembly'),
('粗滤支架', 'Primary Filter Bracket'),
('精滤-喷油泵燃油管总成', 'Fine Filter-to-Injection Pump Fuel Pipe Assembly'),
('精滤出油管', 'Fine Filter Outlet Pipe'),
('精滤器', 'Fine Filter'),
('精滤器-喷油泵燃油管', 'Fine Filter-to-Injection Pump Fuel Pipe'),
('精滤器-喷油泵燃油进油管总成', 'Fine Filter-to-Injection Pump Fuel Pipe Assembly'),
('精滤固定板', 'Fine Filter Fixing Plate'),
('精滤支架', 'Fine Filter Bracket'),
('紧固带拉紧肖', 'Fastening Belt Tensioning Pin'),
('紧固螺母', 'Fastening Nut'),
('紧固螺钉', 'Fastening Screw'),
('紧定螺钉', 'Set Screw'),
('纯铜空心螺栓', 'Pure Copper Hollow Bolt'),
('组合仪表', 'Combination Instrument'),
('组合垫片', 'Combined Washer'),
('组合密封垫圈', 'Combined Seal Washer'),
('绝缘双头螺栓', 'Insulated Stud Bolt'),
('继电器', 'Relay'),
('缓冲块', 'Buffer Block'),
('缸台加0.10气缸套', 'Oversized +0.10 Cylinder Liner'),
('缸盖串水管', 'Head Crossover Water Pipe'),
('缸盖主螺丝', 'Cylinder Head Main Screw'),
('缸盖主螺栓', 'Cylinder Head Main Bolt'),
('缸盖副栓', 'Cylinder Head Auxiliary Bolt'),
('缸盖副螺栓', 'Cylinder Head Auxiliary Bolt'),
('缸盖加紧块', 'Cylinder Head Clamping Block'),
('缸盖夹紧块', 'Cylinder Head Clamping Block'),
('缸盖罩', 'Cylinder Head Cover'),
('缸盖罩 上罩', 'Cylinder Head Cover Upper Shield'),
('缸盖罩P13支撑块', 'Head Cover P13 Support Block'),
('缸盖罩密封圈', 'Cylinder Head Cover Seal Ring'),
('缸盖罩密封垫', 'Cylinder Head Cover Seal'),
('缸盖罩支撑块', 'Cylinder Head Cover Support Block'),
('缸盖罩衬垫', 'Cylinder Head Cover Gasket'),
('缸盖罩（天然气）', 'Cylinder Head Cover (Natural Gas)'),
('缸盖罩（带加机油口）', 'Cylinder Head Cover (with Oil Filler)'),
('缸盖螺栓', 'Cylinder Head Bolt'),
('老四气门摇臂总成', 'Old 4-Valve Rocker Arm Assembly'),
('耐热六角螺栓', 'Heat-Resistant Hex Bolt'),
('耐热螺栓', 'Heat-Resistant Bolt'),
('联接弯管', 'Connecting Elbow Pipe'),
('联接螺栓', 'Connecting Bolt'),
('联接软管', 'Connecting Hose'),
('联管螺母', 'Union Nut'),
('联组带', 'Joined Belt'),
('联轴器', 'Coupling'),
('联轴器总成', 'Coupling Assembly'),
('联轴器法兰组件', 'Coupling Flange Assembly'),
('联轴器螺栓', 'Coupling Bolt'),
('胶管', 'Rubber Hose'),
('膨胀水箱总成', 'Expansion Tank Assembly'),
('膨胀管结合子组排气管', 'Expansion Pipe Combination Exhaust Pipe'),
('自动张紧轮', 'Auto Tensioner'),
('自动张紧轮110010', 'Auto Tensioner 110010'),
('自动张紧轮110012', 'Auto Tensioner 110012'),
('自动张紧轮110052', 'Auto Tensioner 110052'),
('自动张紧轮总成', 'Auto Tensioner Assembly'),
('自动张紧轮（110112）', 'Auto Tensioner (110112)'),
('自动放水阀', 'Automatic Drain Valve'),
('自动涨紧轮', 'Auto Tensioner'),
('自动涨紧轮110003', 'Auto Tensioner 110003'),
('自动涨紧轮110007', 'Auto Tensioner 110007'),
('自动涨紧轮110012', 'Auto Tensioner 110012'),
('自动涨紧轮110014', 'Auto Tensioner 110014'),
('自动涨紧轮110016', 'Auto Tensioner 110016'),
('自动涨紧轮110017', 'Auto Tensioner 110017'),
('自动涨紧轮（十槽惰轮）', 'Auto Tensioner (10-Groove Idler)'),
('自锁垫片', 'Self-Locking Washer'),
('自锁螺母', 'Self-Locking Nut'),
('船用节温器总成', 'Marine Thermostat Assembly'),
('节气门位置传感器', 'Throttle Position Sensor'),
('虑杯和水位传感器总成', 'Filter Bowl & Water Level Sensor Assembly'),
('蛙胶管', 'Rubber Hose'),
('螺塞', 'Plug'),
('螺座', 'Threaded Seat'),
('螺旋撑簧油环', 'Spiral Expander Oil Ring'),
('螺钉', 'Screw'),
('衬套', 'Bushing'),
('装机主轴瓦', 'Assembly Main Bearing'),
('装机排气门座', 'Assembly Exhaust Valve Seat'),
('装机曲轴前油封', 'Assembly Crankshaft Front Oil Seal'),
('装机进气门座', 'Assembly Intake Valve Seat'),
('观察孔盖', 'Inspection Hole Cover'),
('角度调整板', 'Angle Adjustment Plate'),
('角度调节板', 'Angle Adjusting Plate'),
('角度调节螺栓', 'Angle Adjusting Bolt'),
('角形法兰', 'Angle Flange'),
('角形法兰密封垫', 'Angle Flange Gasket'),
('角齿螺丝', 'Bevel Gear Screw'),
('解放涨紧轮', 'FAW Jiefang Tensioner'),
('调整螺母', 'Adjusting Nut'),
('调节螺钉', 'Adjusting Screw'),
('轨压传感器', 'Rail Pressure Sensor'),
('转向助力泵', 'Power Steering Pump'),
('转向巨力泵', 'Heavy-Duty Steering Pump'),
('转向机回油管', 'Steering Gear Return Pipe'),
('转向机进油管', 'Steering Gear Inlet Pipe'),
('转向泵垫片', 'Steering Pump Gasket'),
('转向液压泵齿轮', 'Steering Hydraulic Pump Gear'),
('转速传感器', 'Speed Sensor'),
('转速传感器(EGR)', 'Speed Sensor (EGR)'),
('轮毂', 'Wheel Hub'),
('轮边盖堵', 'Wheel End Cover Plug'),
('轮边行星齿轮轴', 'Wheel Planetary Gear Shaft'),
('软管', 'Hose'),
('软管接头', 'Hose Joint'),
('轴用钢丝挡圈', 'Wire Circlip for Shaft'),
('输出法兰', 'Output Flange'),
('输出法兰固定板', 'Output Flange Fixing Plate'),
('输出法兰（后驱力）', 'Output Flange (Rear Drive Unit)'),
('输出轴', 'Output Shaft'),
('输出齿轮', 'Output Gear'),
('输出齿轮前轴承', 'Output Gear Front Bearing'),
('输出齿轮后轴承', 'Output Gear Rear Bearing'),
('输出齿轮（后驱力0', 'Output Gear (Rear Drive Unit)'),
('输出齿轮（后驱力）', 'Output Gear (Rear Drive Unit)'),
('输油泵', 'Fuel Feed Pump'),
('输油泵-精滤器燃油管总成', 'Feed Pump-to-Fine Filter Fuel Pipe Assembly'),
('输油泵总成', 'Fuel Feed Pump Assembly'),
('输油泵手泵体', 'Feed Pump Hand Pump Body'),
('达克罗排气管螺栓', 'Dacromet Exhaust Pipe Bolt'),
('达克罗空心螺栓', 'Dacromet Hollow Bolt'),
('过度接头', 'Adapter Joint'),
('过桥钢管0245/1', 'Bridge Steel Pipe 0245/1'),
('过渡接头', 'Adapter Joint'),
('进气压力传感器', 'Intake Pressure Sensor'),
('进气弯管', 'Intake Elbow Pipe'),
('进气接管', 'Intake Connection Pipe'),
('进气摇臂组件', 'Intake Rocker Module'),
('进气法兰面六角头管螺栓', 'Intake Hex Flange Pipe Bolt'),
('进气温度传感器', 'Intake Air Temperature Sensor'),
('进气温度压力传感器', 'Intake Temperature & Pressure Sensor'),
('进气道总成', 'Intake Port Assembly'),
('进气门', 'Intake Valve'),
('进气门MT13', 'Intake Valve MT13'),
('进气门外弹簧', 'Intake Valve Outer Spring'),
('进气门座', 'Intake Valve Seat'),
('进气门座圈', 'Intake Valve Seat'),
('进气门弹簧', 'Intake Valve Spring'),
('进气门弹簧下座', 'Intake Valve Spring Lower Seat'),
('进气门挺住', 'Intake Valve Tappet'),
('进气门摇臂', 'Intake Valve Rocker Arm'),
('进气门摇臂总成', 'Intake Valve Rocker Arm Assembly'),
('进气门桥', 'Intake Valve Bridge'),
('进气门油封', 'Intake Valve Stem Seal'),
('进水管', 'Water Inlet Pipe'),
('进水管座', 'Water Inlet Seat'),
('进水管接头', 'Water Inlet Joint'),
('进油管', 'Oil Inlet Pipe'),
('进油管垫片', 'Oil Inlet Pipe Gasket'),
('进油管总成（短）', 'Oil Inlet Pipe Assembly (Short)'),
('进油管总成（长）', 'Oil Inlet Pipe Assembly (Long)'),
('进油管接头', 'Oil Inlet Pipe Joint'),
('进油管法兰', 'Oil Inlet Pipe Flange'),
('进油管螺丝', 'Oil Inlet Pipe Screw'),
('连体轮边油封', 'Integral Wheel End Oil Seal'),
('连接圈', 'Connecting Ring'),
('连接弯管', 'Connecting Elbow Pipe'),
('连接弯管(后取力)', 'Connecting Elbow (Rear PTO)'),
('连接弯管密封圈', 'Connecting Elbow Seal Ring'),
('连接板', 'Connecting Plate'),
('连接法兰', 'Connecting Flange'),
('连接片总成', 'Connecting Plate Assembly'),
('连接片螺丝(带衬套）', 'Connecting Plate Screw (with Bushing)'),
('连接片衬套', 'Connecting Plate Bushing'),
('连接盘', 'Coupling Disc'),
('连接短管', 'Connecting Short Pipe'),
('连杆上瓦', 'Connecting Rod Upper Bearing'),
('连杆下瓦', 'Connecting Rod Lower Bearing'),
('连杆总成', 'Connecting Rod Assembly'),
('连杆总成J', 'Connecting Rod Assembly J'),
('连杆总成L', 'Connecting Rod Assembly L'),
('连杆总成M', 'Connecting Rod Assembly M'),
('连杆瓦', 'Connecting Rod Bearing'),
('连杆瓦（B504）', 'Connecting Rod Bearing (B504)'),
('连杆瓦（V777.6）', 'Connecting Rod Bearing (V777.6)'),
('连杆螺丝', 'Connecting Rod Screw'),
('连杆螺栓', 'Connecting Rod Bolt'),
('连杆螺栓(不三包）', 'Connecting Rod Bolt (No Warranty)'),
('连杆螺栓（不三包)', 'Connecting Rod Bolt (No Warranty)'),
('连杆衬套', 'Connecting Rod Bushing'),
('连杆轴瓦(上瓦)', 'Connecting Rod Bearing (Upper)'),
('通风弯管', 'Ventilation Elbow Pipe'),
('重汽D10发动机全套螺栓', 'Sinotruk D10 Engine Complete Bolt Kit'),
('重汽D12水泵接头', 'Sinotruk D12 Water Pump Joint'),
('重汽EGR出水管螺栓', 'Sinotruk EGR Water Outlet Bolt'),
('重汽EGR高压油泵螺栓', 'Sinotruk EGR HP Pump Bolt'),
('重汽中缸螺丝', 'Sinotruk Mid-Cylinder Screw'),
('重汽中间轴螺栓', 'Sinotruk Intermediate Shaft Bolt'),
('重汽发电机螺栓包', 'Sinotruk Alternator Bolt Kit'),
('重汽后驱力螺栓包', 'Sinotruk Rear Drive Bolt Kit'),
('重汽四气门摇臂总成', 'Sinotruk 4-Valve Rocker Arm Assembly'),
('重汽排气管增压器螺栓', 'Sinotruk Exhaust-Turbo Bolt'),
('重汽机油冷却器盖螺栓', 'Sinotruk Oil Cooler Cover Bolt'),
('重汽欧II出水管节温器固定螺栓', 'Sinotruk Euro-II Thermostat Fixing Bolt'),
('重汽欧II油泵固定螺栓', 'Sinotruk Euro-II Oil Pump Fixing Bolt'),
('重汽油底壳机油泵螺栓', 'Sinotruk Oil Pan Pump Bolt'),
('重汽空压机螺丝', 'Sinotruk Air Compressor Screw'),
('重汽空心螺栓包', 'Sinotruk Hollow Bolt Kit'),
('金王子加机油口盖', 'Golden Prince Oil Fill Cap'),
('钢丝机油尺', 'Steel Wire Oil Dipstick'),
('钢管总成（20空压机）', 'Steel Pipe Assembly (20 Air Compressor)'),
('铁风圈', 'Iron Fan Shroud'),
('铁风圈支架', 'Iron Fan Shroud Bracket'),
('铜垫（φ10）', 'Copper Washer (φ10)'),
('铜垫（φ12）', 'Copper Washer (φ12)'),
('铜垫（φ14）', 'Copper Washer (φ14)'),
('铜垫（φ6）', 'Copper Washer (φ6)'),
('铜垫（φ8）', 'Copper Washer (φ8)'),
('铝前橡胶支撑总成', 'Aluminum-Front Rubber Mount Assembly'),
('铭牌', 'Name Plate'),
('铰接式管接头体', 'Articulated Joint Body'),
('铰链式管接头体', 'Hinge Type Joint Body'),
('铰链螺栓', 'Hinge Bolt'),
('销(电装压紧块下)', 'Pin (under Injector Clamping Block)'),
('销轴', 'Hinge Pin'),
('锐动力机油滤芯', 'Ruidongli Oil Filter Element'),
('镀铜10*90螺栓', 'Copper-Plated 10*90 Bolt'),
('镀铜排气管螺栓', 'Copper-Plated Exhaust Pipe Bolt'),
('镀锌40水堵', 'Galvanized 40 Core Plug'),
('镀锌水堵', 'Galvanized Water Core Plug'),
('镀锌空心螺栓', 'Galvanized Hollow Bolt'),
('间隔块', 'Spacer Block'),
('间隔快(发电机用）', 'Spacer Block (for Alternator)'),
('间隔板', 'Spacer Plate'),
('防护圈', 'Guard Ring'),
('限压阀', 'Pressure Relief Valve'),
('隔圈（搅拌车）', 'Spacer Ring (Mixer Truck)'),
('隔套', 'Spacer Sleeve'),
('隔热板', 'Heat Insulation Plate'),
('隔热罩', 'Heat Shield'),
('隔热罩下垫圈', 'Heat Shield Lower Washer'),
('隔环', 'Spacer Ring'),
('集滤器', 'Oil Suction Strainer'),
('集滤器压板', 'Oil Strainer Press Plate'),
('集滤器垫片', 'Oil Strainer Gasket'),
('集滤器小支架', 'Oil Strainer Small Bracket'),
('集滤器总成', 'Oil Suction Strainer Assembly'),
('集滤器法兰', 'Oil Strainer Flange'),
('非油道限压阀弹簧', 'Non-Oil-Gallery Relief Valve Spring'),
('非油道限压阀弹簧座', 'Non-Oil-Gallery Relief Valve Spring Seat'),
('预分离器回油管', 'Pre-Separator Return Pipe'),
('预热器', 'Preheater'),
('风扇', 'Fan'),
('风扇叶', 'Fan Blade'),
('风扇托架', 'Fan Bracket'),
('风扇托架总成', 'Fan Bracket Assembly'),
('风扇法兰', 'Fan Flange'),
('风扇离合器', 'Fan Clutch'),
('风扇离合器(装机)', 'Fan Clutch (Assembly Line)'),
('风扇离合器总成', 'Fan Clutch Assembly'),
('风扇离合器（装机）', 'Fan Clutch (Assembly Line)'),
('风扇罩总成', 'Fan Shroud Assembly'),
('风扇轮毂', 'Fan Hub'),
('风扇连接圈', 'Fan Connecting Ring'),
('风扇连接盘', 'Fan Coupling Disc'),
('风扇连驱动轴', 'Fan with Drive Shaft'),
('风扇驱动轴', 'Fan Drive Shaft'),
('驱动销', 'Drive Pin'),
('驾驶室举升铁管', 'Cab Lifting Steel Pipe'),
('驾驶室翻转胶垫', 'Cab Tilt Rubber Pad'),
('骨架油封', 'Skeleton Oil Seal'),
('高压油泵', 'High Pressure Pump'),
('高压油泵密封圈', 'High Pressure Pump Seal Ring'),
('高压油泵总成', 'High Pressure Pump Assembly'),
('高压油泵托架', 'High Pressure Pump Bracket'),
('高压油泵法兰盘', 'High Pressure Pump Flange Plate'),
('高压油泵润滑油管', 'High Pressure Pump Lube Oil Pipe'),
('高压油泵溢流阀', 'High Pressure Pump Overflow Valve'),
('高压线', 'High Voltage Wire'),
('高压连接器外套', 'HV Connector Outer Sleeve'),
('黄油杯座', 'Grease Cup Seat'),
('齿圈支架螺母', 'Ring Gear Bracket Nut'),
('齿形带', 'Timing Toothed Belt'),
('（B型）节温器盖垫片', '(Type B) Thermostat Cover Gasket'),
('（MC11）分配壳密封垫', '(MC11) Distribution Housing Gasket'),
('（MC11）前端盖密封垫', '(MC11) Front Cover Gasket'),
('（MC11）水管', '(MC11) Water Pipe'),
('（MC11）油气分离器出气管总成', '(MC11) Oil-Gas Separator Outlet Pipe Assembly'),
('（MC11）涡轮出口垫片', '(MC11) Turbine Outlet Gasket'),
('（Z镀铜）双头螺栓', '(Z Copper-Plated) Stud Bolt'),
('（不带标）隔热罩', 'Heat Shield (Unmarked)'),
('（工程机械）曲轴法兰', '(Construction Machinery) Crankshaft Flange'),
('（瑞驰）WP10齿轮室螺丝修理包', '(Ruichi) WP10 Gear Housing Screw Repair Kit'),
('（耐热钢）排气管螺栓', 'Exhaust Pipe Bolt (Heat-Resistant Steel)'),
('（黑）增压器双头螺栓', '(Black) Turbo Stud Bolt')
) AS t(zh, en)
WHERE p.slug LIKE 'deda-inv-%'
  AND (p.name_zh = t.zh OR p.name_zh LIKE t.zh || ' %');
