-- 批次A:9-19六小文件 20款(三鑫牵引座5/波纹板1/赛特蹄铁8/赛特盘片6) 2026-09-21
-- 康迈轮端OCR乱码未导;波纹板品牌照录BRAKFLINN待确认;4707尺寸两源冲突照录
-- 价格不入库(询价模式);幂等按slug。执行环境:Supabase SQL Editor

INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'sanxin-sx90s-b21-traction-seat', 'DD-TS-001', 'SANXIN Fifth Wheel SX90S-B21', '三鑫牵引座 SX90S-B21', '三鑫', NULL, 'chassis-suspension', 'SANXIN fifth wheel SX90S-B21: height 165mm, max towing 70T, D-value 200KN, Sinotruk OE refs.', '三鑫牵引座 SX90S-B21,高度165mm,最大牵引质量70T,D值200KN,重汽配套。', '{"高度": "165mm", "最大牵引质量": "70T", "牵引座面板厚度": "8mm", "D值": "200KN", "额定承载载荷": "30T", "重量": "130KG", "重汽配套图号": "WG9925939002 / WG9525930910"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sanxin-sx90s-b21-traction-seat');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'sanxin-sx50s-c21-traction-seat', 'DD-TS-002', 'SANXIN Fifth Wheel SX50S-C21', '三鑫牵引座 SX50S-C21', '三鑫', NULL, 'chassis-suspension', 'SANXIN fifth wheel SX50S-C21: height 185mm, max towing 50T.', '三鑫牵引座 SX50S-C21,高度185mm,最大牵引质量50T。', '{"高度": "185mm", "最大牵引质量": "50T", "牵引座面板厚度": "8mm", "重量": "115KG", "重汽配套图号": "WG9121935000 / WG9525930500"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sanxin-sx50s-c21-traction-seat');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'sanxin-sx50s-c32-traction-seat', 'DD-TS-003', 'SANXIN Fifth Wheel SX50S-C32', '三鑫牵引座 SX50S-C32', '三鑫', NULL, 'chassis-suspension', 'SANXIN fifth wheel SX50S-C32: height 158mm, max towing 50T.', '三鑫牵引座 SX50S-C32,高度158mm,最大牵引质量50T。', '{"高度": "158mm", "最大牵引质量": "50T", "牵引座面板厚度": "8mm", "重量": "117KG", "重汽配套图号": "WG9122935000"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sanxin-sx50s-c32-traction-seat');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'sanxin-sx90s-a61-traction-seat', 'DD-TS-004', 'SANXIN Fifth Wheel SX90S-A61', '三鑫牵引座 SX90S-A61', '三鑫', NULL, 'chassis-suspension', 'SANXIN fifth wheel SX90S-A61: height 200mm, max towing 120T, D-value 220KN, Shaanxi Auto OE ref.', '三鑫牵引座 SX90S-A61,高度200mm,最大牵引质量120T,D值220KN,陕汽配套。', '{"高度": "200mm", "最大牵引质量": "120T", "牵引座面板厚度": "10mm", "D值": "220KN", "额定垂直载荷": "35T", "重量": "185KG", "陕汽配套图号": "DZ912599300012"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sanxin-sx90s-a61-traction-seat');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'sanxin-sx90s-b41-traction-seat', 'DD-TS-005', 'SANXIN Fifth Wheel SX90S-B41', '三鑫牵引座 SX90S-B41', '三鑫', NULL, 'chassis-suspension', 'SANXIN fifth wheel SX90S-B41: height 173mm, max towing 70T, Shaanxi Auto OE ref.', '三鑫牵引座 SX90S-B41,高度173mm,最大牵引质量70T,陕汽配套。', '{"高度": "173mm", "最大牵引质量": "70T", "牵引座面板厚度": "8mm", "D值": "200KN", "额定承载载荷": "30T", "重量": "135KG", "陕汽配套图号": "SZ997000796"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sanxin-sx90s-b41-traction-seat');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'sx90s-b41-corrugated-plate', 'DD-WV-001', 'Corrugated Plate SX90S-B41', '波纹板 SX90S-B41', 'BRAKFLINN', NULL, 'other', 'Corrugated plate SX90S-B41, high-strength steel stamped, multiple heights, Sinotruk/Shaanxi OE refs.', '波纹板 SX90S-B41,高强钢冲压成型,多种高度可选,重汽/陕汽配套图号照录。', '{"材质": "高强钢冲压成型", "特点": "多种高度可选择", "重汽配套图号": "WG9525930256", "陕汽配套图号": "DZ951899A30023"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'sx90s-b41-corrugated-plate');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-4515-brake-shoe', 'DD-SHO-001', 'SAITE Brake Shoe 4515', '赛特蹄铁 4515', '赛特', NULL, 'brake-system', 'SAITE brake shoe 4515 for FUWA 13T axle, brake size 419x177.8mm.', '黄石赛特蹄铁 4515,配套富华FUWA 13T车桥,制动尺寸Φ419*177.8mm。', '{"OEM": "FUWA 13T", "制动尺寸": "Φ419*177.8mm", "配套": "Supply to FUWA", "参考尺寸": "R203 Φ27/Φ19.05 A1+A2=323.85 B=177.8 H1/H2=48.5/50.9"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-4515-brake-shoe');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-4515q-brake-shoe', 'DD-SHO-002', 'SAITE Brake Shoe 4515Q', '赛特蹄铁 4515Q', '赛特', NULL, 'brake-system', 'SAITE brake shoe 4515Q, OEM 152.05.533, brake size 419x177.8mm.', '黄石赛特蹄铁 4515Q,OEM 152.05.533,制动尺寸Φ419*177.8mm。', '{"OEM": "152.05.533", "制动尺寸": "Φ419*177.8mm", "参考尺寸": "R203 Φ25.6/Φ19.2 A1+A2=323.85 B=177.8 H1/H2=49/45", "对应刹车片": "4515 / 4515E"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-4515q-brake-shoe');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-4551-brake-shoe', 'DD-SHO-003', 'SAITE Brake Shoe 4551', '赛特蹄铁 4551', '赛特', NULL, 'brake-system', 'SAITE brake shoe 4551 for FUWA 16T axle, brake size 419x219mm.', '黄石赛特蹄铁 4551,配套富华FUWA 16T车桥,制动尺寸Φ419*219mm。', '{"OEM": "FUWA 16T", "制动尺寸": "Φ419*219mm", "配套": "Supply to FUWA", "参考尺寸": "R203 Φ27/Φ19.05 A1+A2=323.85 B=219 H1/H2=48.5/50.9", "WVA": "19369/0"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-4551-brake-shoe');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-4551-shoe-assembly', 'DD-SHO-004', 'SAITE Brake Shoe Assembly 4551', '赛特蹄铁总成 4551', '赛特', NULL, 'brake-system', 'SAITE brake shoe assembly 4551, based on shoe 4551.', '黄石赛特蹄铁总成 4551(含滚轮等附件),基础型号4551。', '{"类型": "蹄铁总成", "基础型号": "4551", "制动尺寸": "Φ419*219mm"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-4551-shoe-assembly');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-4707-brake-shoe', 'DD-SHO-005', 'SAITE Brake Shoe 4707', '赛特蹄铁 4707', '赛特', NULL, 'brake-system', 'SAITE brake shoe 4707, OEM 152.24.724, interchangeable with Meritor A3222D2006 / Spicer M16WS193X.', '黄石赛特蹄铁 4707,OEM 152.24.724,可互换 Meritor A3222D2006 / Spicer M16WS193X。', '{"OEM": "152.24.724", "制动尺寸": "419*177.8mm(产品页);交叉表 B=219 以原件为准", "互换": "ROCKWELL/MERITOR A3222D2006; SPICER OE M16WS193X", "参考尺寸": "R203 Φ25.6/Φ19 A1+A2=323.85 B=219 H1/H2=48.5/50.9"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-4707-brake-shoe');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-4707-shoe-assembly', 'DD-SHO-006', 'SAITE Brake Shoe Assembly 4707', '赛特蹄铁总成 4707', '赛特', NULL, 'brake-system', 'SAITE brake shoe assembly 4707.', '黄石赛特蹄铁总成 4707(含滚轮等附件)。', '{"类型": "蹄铁总成", "基础型号": "4707"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-4707-shoe-assembly');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-bpw200-brake-shoe', 'DD-SHO-007', 'SAITE German-type 200 Brake Shoe (BPW200 NEW)', '赛特德式200蹄铁 BPW200 NEW', '赛特', NULL, 'brake-system', 'SAITE German-type 200 brake shoe (BPW200 NEW), OEM 05.091.27.83.0, brake size 420x200mm.', '黄石赛特德式200蹄铁(BPW200 NEW),OEM 05.091.27.83.0,制动尺寸Φ420*200mm。', '{"OEM": "05.091.27.83.0", "制动尺寸": "Φ420*200mm", "WVA": "19094", "BMFC": "BC37/1", "参考尺寸": "R205 Φ26/Φ36 A1+A2=317.7 B=200 H1/H2=49.17/54.1"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-bpw200-brake-shoe');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-bpw200-shoe-assembly', 'DD-SHO-008', 'SAITE German-type 200 Shoe Assembly', '赛特德式200蹄铁总成', '赛特', NULL, 'brake-system', 'SAITE German-type 200 brake shoe assembly.', '黄石赛特德式200蹄铁总成(含滚轮等附件)。', '{"类型": "蹄铁总成", "基础型号": "BPW200 NEW"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-bpw200-shoe-assembly');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-60-brake-pad', 'DD-PAD-001', 'SAITE Engineering Brake Pad 60', '赛特工程机械刹车片 60', '赛特', '龙工6T; 临工6T', 'brake-system', 'SAITE engineering brake pad 60 for Lonking 6T / Lingong 6T loaders.', '黄石赛特工程机械刹车片 60,适用龙工6T/临工6T。', '{"适用": "龙工6T、临工6T装载机"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-60-brake-pad');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-3050-brake-pad', 'DD-PAD-002', 'SAITE Brake Pad 30.50 (XGMA)', '赛特刹车片 30.50(厦工)', '赛特', '龙工5T; 临工5T; 厦工5T/6T; 柳工5T', 'brake-system', 'SAITE brake pad 30.50 for Lonking/Lingong/XGMA/LiuGong 5T class.', '黄石赛特刹车片 30.50(厦工),适用龙工/临工/厦工/柳工5T级。', '{"适用": "龙工5T、临工5T、厦工5T/6T、柳工5T"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-3050-brake-pad');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-50c-brake-pad', 'DD-PAD-003', 'SAITE Brake Pad 50C (LiuGong)', '赛特刹车片 50C(柳工)', '赛特', '柳工老款', 'brake-system', 'SAITE brake pad 50C for LiuGong old models.', '黄石赛特刹车片 50C,适用柳工老款。', '{"适用": "柳工老款"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-50c-brake-pad');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-liugong-4050-brake-pad', 'DD-PAD-004', 'SAITE LiuGong 40/50 Brake Pad', '赛特柳工40/50刹车片', '赛特', '柳工老款', 'brake-system', 'SAITE brake pad for LiuGong 40/50 old models.', '黄石赛特柳工40/50刹车片,适用柳工老款。', '{"适用": "柳工老款"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-liugong-4050-brake-pad');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-chaoyue-trailer-disc-pad', 'DD-PAD-005', 'SAITE Premium Trailer Disc Pad', '赛特大盘片 超越款(挂车)', '赛特', '挂车', 'brake-system', 'SAITE premium trailer disc pad: low-metal/aramid-potassium titanate formulation, stable friction, long life.', '赛特大盘片超越款,挂车用,摩擦系数与制动力量稳定,低磨耗长寿命,适用平原及部分重载山区高速。', '{"配方材质": "低金属/芳纶与钛酸钾纤维增强", "外观": "深灰色/表面有颗粒石墨", "寿命": "平原6-12万公里(视路况载重)"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-chaoyue-trailer-disc-pad');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'saite-yinling-copper-disc-pad', 'DD-PAD-006', 'SAITE Copper-fiber Disc Pad', '赛特大盘片 引领款(铜基)', '赛特', '重型货车; 危化品运输车', 'brake-system', 'SAITE copper-fiber disc pad: high torque, heat resistant, disc-friendly, for heavy trucks and hazmat carriers.', '赛特大盘片引领款铜基,高制动扭矩耐高温,对刹车盘友好,适用重型货车及危化品运输车。', '{"配方材质": "有机钢背、铜纤维增强", "外观": "浅灰色、表面可见铜纤维", "寿命": "平原15-20万公里(视路况载重)"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'saite-yinling-copper-disc-pad');
