-- drivetrain 系列（来源：中配供应商目录文本，2026-09-18）
-- 共 17 条；价格不入库（询价模式）；幂等：按 slug 去重

INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-32-l93-bj130', 'DD-DRV-101', 'Universal Joint Cross Φ32*L93 / 外卡式', '传动轴十字轴 Φ32*L93 / 外卡式', NULL, 'BJ130', 'drivetrain', 'Universal Joint Cross Φ32*L93 / 外卡式 for BJ130.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ32*L93 / 外卡式，适用BJ130。济南德达供应，欢迎询价。', '{"规格": "Φ32*L93 / 外卡式", "适用车型": "BJ130"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-32-l93-bj130');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-30-l88-bj121', 'DD-DRV-102', 'Universal Joint Cross Φ30*L88 / 内卡式', '传动轴十字轴 Φ30*L88 / 内卡式', NULL, 'BJ121', 'drivetrain', 'Universal Joint Cross Φ30*L88 / 内卡式 for BJ121.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ30*L88 / 内卡式，适用BJ121。济南德达供应，欢迎询价。', '{"规格": "Φ30*L88 / 内卡式", "适用车型": "BJ121"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-30-l88-bj121');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-39-l118-ca141', 'DD-DRV-103', 'Universal Joint Cross Φ39*L118 / 锁片式', '传动轴十字轴 Φ39*L118 / 锁片式', NULL, 'CA141', 'drivetrain', 'Universal Joint Cross Φ39*L118 / 锁片式 for CA141.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ39*L118 / 锁片式，适用CA141。济南德达供应，欢迎询价。', '{"规格": "Φ39*L118 / 锁片式", "适用车型": "CA141"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-39-l118-ca141');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-48-l127-ca151-9', 'DD-DRV-104', 'Universal Joint Cross Φ48*L127 / 锁片式', '传动轴十字轴 Φ48*L127 / 锁片式', NULL, 'CA151/9', 'drivetrain', 'Universal Joint Cross Φ48*L127 / 锁片式 for CA151/9.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ48*L127 / 锁片式，适用CA151/9。济南德达供应，欢迎询价。', '{"规格": "Φ48*L127 / 锁片式", "适用车型": "CA151/9"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-48-l127-ca151-9');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-39-l118-eq140', 'DD-DRV-105', 'Universal Joint Cross Φ39*L118 / 锁片式', '传动轴十字轴 Φ39*L118 / 锁片式', NULL, 'EQ140', 'drivetrain', 'Universal Joint Cross Φ39*L118 / 锁片式 for EQ140.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ39*L118 / 锁片式，适用EQ140。济南德达供应，欢迎询价。', '{"规格": "Φ39*L118 / 锁片式", "适用车型": "EQ140"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-39-l118-eq140');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-47-l143-eq153', 'DD-DRV-106', 'Universal Joint Cross Φ47*L143 / 外卡式', '传动轴十字轴 Φ47*L143 / 外卡式', NULL, 'EQ153', 'drivetrain', 'Universal Joint Cross Φ47*L143 / 外卡式 for EQ153.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ47*L143 / 外卡式，适用EQ153。济南德达供应，欢迎询价。', '{"规格": "Φ47*L143 / 外卡式", "适用车型": "EQ153"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-47-l143-eq153');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-33-l93-hfc6700', 'DD-DRV-108', 'Universal Joint Cross Φ33*L93 / 外卡式', '传动轴十字轴 Φ33*L93 / 外卡式', NULL, 'HFC6700', 'drivetrain', 'Universal Joint Cross Φ33*L93 / 外卡式 for HFC6700.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ33*L93 / 外卡式，适用HFC6700。济南德达供应，欢迎询价。', '{"规格": "Φ33*L93 / 外卡式", "适用车型": "HFC6700"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-33-l93-hfc6700');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-35-l98-nj130', 'DD-DRV-109', 'Universal Joint Cross Φ35*L98 / 锁片式', '传动轴十字轴 Φ35*L98 / 锁片式', NULL, 'NJ130', 'drivetrain', 'Universal Joint Cross Φ35*L98 / 锁片式 for NJ130.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ35*L98 / 锁片式，适用NJ130。济南德达供应，欢迎询价。', '{"规格": "Φ35*L98 / 锁片式", "适用车型": "NJ130"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-35-l98-nj130');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-62-l170', 'DD-DRV-110', 'Universal Joint Cross Φ62*L170 / 外卡式', '传动轴十字轴 Φ62*L170 / 外卡式', NULL, '东风天龙', 'drivetrain', 'Universal Joint Cross Φ62*L170 / 外卡式 for 东风天龙.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ62*L170 / 外卡式，适用东风天龙。济南德达供应，欢迎询价。', '{"规格": "Φ62*L170 / 外卡式", "适用车型": "东风天龙"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-62-l170');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-62-l118', 'DD-DRV-111', 'Universal Joint Cross Φ62*L118 / 外卡式', '传动轴十字轴 Φ62*L118 / 外卡式', NULL, '红岩', 'drivetrain', 'Universal Joint Cross Φ62*L118 / 外卡式 for 红岩.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ62*L118 / 外卡式，适用红岩。济南德达供应，欢迎询价。', '{"规格": "Φ62*L118 / 外卡式", "适用车型": "红岩"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-62-l118');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-27-l82', 'DD-DRV-112', 'Universal Joint Cross Φ27*L82 / 外卡式', '传动轴十字轴 Φ27*L82 / 外卡式', NULL, '江苏瑞风', 'drivetrain', 'Universal Joint Cross Φ27*L82 / 外卡式 for 江苏瑞风.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ27*L82 / 外卡式，适用江苏瑞风。济南德达供应，欢迎询价。', '{"规格": "Φ27*L82 / 外卡式", "适用车型": "江苏瑞风"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-27-l82');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-27-l118', 'DD-DRV-113', 'Universal Joint Cross Φ27*L118 / 外卡式', '传动轴十字轴 Φ27*L118 / 外卡式', NULL, '金龙客车', 'drivetrain', 'Universal Joint Cross Φ27*L118 / 外卡式 for 金龙客车.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ27*L118 / 外卡式，适用金龙客车。济南德达供应，欢迎询价。', '{"规格": "Φ27*L118 / 外卡式", "适用车型": "金龙客车"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-27-l118');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-29-l77', 'DD-DRV-114', 'Universal Joint Cross Φ29*L77 / 内卡式', '传动轴十字轴 Φ29*L77 / 内卡式', NULL, '五十铃', 'drivetrain', 'Universal Joint Cross Φ29*L77 / 内卡式 for 五十铃.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ29*L77 / 内卡式，适用五十铃。济南德达供应，欢迎询价。', '{"规格": "Φ29*L77 / 内卡式", "适用车型": "五十铃"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-29-l77');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-66-l134-howo-t7h', 'DD-DRV-115', 'Universal Joint Cross Φ66*L134 / 内卡式', '传动轴十字轴 Φ66*L134 / 内卡式', NULL, 'HOWO T7H', 'drivetrain', 'Universal Joint Cross Φ66*L134 / 内卡式 for HOWO T7H.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ66*L134 / 内卡式，适用HOWO T7H。济南德达供应，欢迎询价。', '{"规格": "Φ66*L134 / 内卡式", "适用车型": "HOWO T7H"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-66-l134-howo-t7h');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-52-l133-str', 'DD-DRV-116', 'Universal Joint Cross Φ52*L133 / 外卡式', '传动轴十字轴 Φ52*L133 / 外卡式', NULL, '重汽STR', 'drivetrain', 'Universal Joint Cross Φ52*L133 / 外卡式 for 重汽STR.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ52*L133 / 外卡式，适用重汽STR。济南德达供应，欢迎询价。', '{"规格": "Φ52*L133 / 外卡式", "适用车型": "重汽STR"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-52-l133-str');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-57-l144-str', 'DD-DRV-117', 'Universal Joint Cross Φ57*L144 / 外卡式', '传动轴十字轴 Φ57*L144 / 外卡式', NULL, '重汽STR', 'drivetrain', 'Universal Joint Cross Φ57*L144 / 外卡式 for 重汽STR.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ57*L144 / 外卡式，适用重汽STR。济南德达供应，欢迎询价。', '{"规格": "Φ57*L144 / 外卡式", "适用车型": "重汽STR"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-57-l144-str');
INSERT INTO products (slug, sku, name_en, name_zh, brand, truck_model, category, description_en, description_zh, specs, status) SELECT 'universal-joint-cross-57-l152-str', 'DD-DRV-118', 'Universal Joint Cross Φ57*L152 / 外卡式', '传动轴十字轴 Φ57*L152 / 外卡式', NULL, '重汽STR', 'drivetrain', 'Universal Joint Cross Φ57*L152 / 外卡式 for 重汽STR.Heavy truck parts from DEDA, inquiry welcome.', '传动轴十字轴 Φ57*L152 / 外卡式，适用重汽STR。济南德达供应，欢迎询价。', '{"规格": "Φ57*L152 / 外卡式", "适用车型": "重汽STR"}'::jsonb, 'published' WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = 'universal-joint-cross-57-l152-str');
