# -*- coding: utf-8 -*-
"""批次6 英文名词典 chunk4（第 1351-1800 个漏网名称）"""
D4 = {
"燃油滤托架总成": "Fuel Filter Bracket Assembly", "P7缸盖螺栓（全长130）": "P7 Cylinder Head Bolt (130mm)",
"压缩机支架固定螺栓": "Compressor Bracket Fixing Bolt", "P13EVB润滑油管": "P13 EVB Lube Oil Pipe",
"原厂进气门弹簧下座": "OEM Intake Valve Spring Lower Seat", "A类水管接头": "Type-A Water Pipe Joint",
"14*90法兰面六角头螺丝": "14*90 Hex Flange Screw", "M10空心螺栓": "M10 Hollow Bolt",
"P13摇臂座内六角螺栓": "P13 Rocker Seat Socket Bolt", "H1双管接头": "H1 Double Pipe Joint",
"主轴承螺栓（带孔）": "Main Bearing Bolt (with Hole)", "WP13增压器进油管": "WP13 Turbo Oil Feed Pipe",
"WP13增压器进油管（带卡套螺母）": "WP13 Turbo Oil Feed Pipe (with Ferrule Nut)",
"6*50双头螺栓": "6*50 Stud Bolt", "10*30法兰面螺栓": "10*30 Flange Bolt",
"出水管垫": "Water Outlet Gasket", "P12增压器垫片": "P12 Turbo Gasket",
"10*45六角头螺栓": "10*45 Hex Head Bolt", "226B缸盖螺栓（全长170）": "226B Head Bolt (170mm)",
"油门杠杆限位螺钉": "Throttle Lever Limit Screw", "油门杠杆螺母": "Throttle Lever Nut",
"P13WEVB支架螺栓（法兰面)": "P13 WEVB Bracket Bolt (Flange)", "H10管接头组件": "H10 Pipe Joint Assembly",
"WP7气门桥": "WP7 Valve Bridge", "P12空压机进气接头": "P12 Air Compressor Intake Joint",
"WP12双管接头": "WP12 Double Pipe Joint", "10*90法兰面六角头": "10*90 Hex Flange Head",
"P12增压器隔热罩": "P12 Turbo Heat Shield", "P7增压器进油管": "P7 Turbo Oil Feed Pipe",
"H10机油滤清器滤芯": "H10 Oil Filter Element", "H10燃油精滤芯": "H10 Fuel Fine Filter Element",
"H10燃油粗滤芯": "H10 Fuel Primary Filter Element", "226B曲轴前油封": "226B Crankshaft Front Oil Seal",
"P7增压器回油管": "P7 Turbo Oil Return Pipe", "10.9内六角螺栓10*80": "Socket Bolt Gr.10.9 10*80",
"P12机油喷嘴": "P12 Oil Nozzle", "8*25法兰面六角头螺栓": "8*25 Hex Flange Bolt",
"WP13分体缸盖罩定位套": "WP13 Split Head Cover Locating Sleeve", "H1凸轮轴止推片": "H1 Camshaft Thrust Washer",
"WP7曲轴前油封": "WP7 Crankshaft Front Oil Seal", "226B曲轴后油封": "226B Crankshaft Rear Oil Seal",
"双唇曲轴油封": "Double-Lip Crankshaft Oil Seal", "H10气门弹簧上座": "H10 Valve Spring Upper Seat",
"P12机滤座垫片": "P12 Oil Filter Seat Gasket", "冲差价": "Price Difference Adjustment",
"H1卡箍": "H1 Hose Clamp", "H1空压机进水管": "H1 Air Compressor Water Inlet Pipe",
"H1螺母": "H1 Nut", "H1卡套": "H1 Ferrule Sleeve", "H1接头体": "H1 Joint Body",
"H1空压机水管接头": "H1 Air Compressor Water Pipe Joint", "MC11/13排气管密封环": "MC11/13 Exhaust Seal Ring",
"H10机油尺管总成": "H10 Dipstick Tube Assembly", "H10机油尺下组件": "H10 Dipstick Lower Module",
"H09机油尺管总成": "H09 Dipstick Tube Assembly", "WP7增压器进油管": "WP7 Turbo Oil Feed Pipe",
"H10油尺堵": "H10 Dipstick Plug", "H10空压机回水管总成": "H10 Air Compressor Return Water Pipe Assembly",
"H10空压机进水管总成(带螺母)": "H10 Air Compressor Water Inlet Pipe Assembly (with Nut)",
"H10出水管组件": "H10 Water Outlet Pipe Module", "WEVB润滑油管总成": "WEVB Lube Oil Pipe Assembly",
"H10放气管总成": "H10 Air Bleed Pipe Assembly", "H10缸盖出水管定位套": "H10 Head Water Outlet Locating Sleeve",
"WP13摇臂支架定位套": "WP13 Rocker Bracket Locating Sleeve", "WP7气门弹簧": "WP7 Valve Spring",
"H10进气门弹簧": "H10 Intake Valve Spring", "H10排气门弹簧": "H10 Exhaust Valve Spring",
"P12水泵泵头(高)": "P12 Water Pump Head (High)", "P12火花塞衬套密封圈": "P12 Spark Plug Bushing Seal Ring",
"P13WEVB排气门摇臂": "P13 WEVB Exhaust Valve Rocker Arm", "缸盖罩P13支撑块": "Head Cover P13 Support Block",
"10*75带齿法兰面螺栓": "10*75 Toothed Flange Bolt", "D12皮带轮螺栓": "D12 Pulley Bolt",
"空压机出水管（带螺母）": "Air Compressor Water Outlet Pipe (with Nut)",
"空压机进水管（带螺母）": "Air Compressor Water Inlet Pipe (with Nut)",
"MC11/13缸盖主螺栓": "MC11/13 Head Main Bolt", "MC11连杆螺栓": "MC11 Connecting Rod Bolt",
"WP6气门弹簧": "WP6 Valve Spring", "6*30内六角螺栓": "6*30 Socket Bolt", "6*45内六角螺栓": "6*45 Socket Bolt",
"6*65内六角螺栓": "6*65 Socket Bolt", "5*45内六角螺栓": "5*45 Socket Bolt", "67进气门": "67 Intake Valve",
"重汽D12水泵接头": "Sinotruk D12 Water Pump Joint", "P13支撑块": "P13 Support Block",
"国四燃油管": "China-IV Fuel Pipe", "H10机滤芯": "H10 Oil Filter Element",
"P12喷嘴螺栓": "P12 Nozzle Bolt", "L10后驱力润滑油管": "L10 Rear Drive Lube Oil Pipe",
"（B型）节温器盖垫片": "(Type B) Thermostat Cover Gasket", "(4PK*1249)多挈带": "(4PK*1249) Poly-V Belt",
"10PK1887多挈带": "10PK1887 Poly-V Belt", "WP12增压器支架": "WP12 Turbo Bracket",
"83°节温器芯": "83℃ Thermostat Element", "1422堵口": "1422 Plug", "50水堵(铜)": "50 Copper Core Plug",
"H10空压机进气管": "H10 Air Compressor Intake Pipe", "H10出水管垫片": "H10 Water Outlet Gasket",
"WP7整体式摇臂轴总成": "WP7 Integral Rocker Arm Shaft Assembly", "轴用钢丝挡圈": "Wire Circlip for Shaft",
"H09飞轮螺栓": "H09 Flywheel Bolt", "WP6机油尺总成": "WP6 Oil Dipstick Assembly",
"潍柴WEVB缸盖明细表": "Weichai WEVB Head Detail List", "欧II缸盖组装明细": "Euro-II Head Assembly List",
"副厂P12排气管密封环": "Aftermarket P12 Exhaust Seal Ring", "中间齿轮组件": "Idler Gear Module",
"镀锌40水堵": "Galvanized 40 Core Plug", "H1回油管接头": "H1 Oil Return Joint",
"MC05/07排气管密封环": "MC05/07 Exhaust Seal Ring", "8*25内六角螺栓（10.9）": "8*25 Socket Bolt (Gr.10.9)",
"P13进气管垫": "P13 Intake Gasket", "客车缸盖出水管": "Coach Head Water Outlet Pipe",
"8*20六角头螺栓": "8*20 Hex Head Bolt", "离心式滤清器滤芯": "Centrifugal Filter Element",
"集滤器法兰": "Oil Strainer Flange", "MC11机油尺": "MC11 Oil Dipstick",
"H1连杆螺栓": "H1 Connecting Rod Bolt", "尿素调节螺栓": "Urea Adjusting Bolt",
"绝缘双头螺栓": "Insulated Stud Bolt", "12*45双头螺栓": "12*45 Stud Bolt",
"单管管夹总成": "Single Pipe Clamp Assembly", "H10皮带轮": "H10 Pulley",
"P7气门弹簧上座": "P7 Valve Spring Upper Seat", "P12机油滤芯": "P12 Oil Filter Element",
"15PK惰轮": "15PK Idler Pulley", "空芯接头": "Hollow Joint",
"空压机出气管接头": "Air Compressor Air Outlet Joint", "曼MC11柴滤芯": "MAN MC11 Diesel Filter Element",
"曼MC11机滤芯": "MAN MC11 Oil Filter Element", "组合垫片": "Combined Washer",
"M8法兰面自锁螺母": "M8 Flange Self-Locking Nut", "H1密封圈（B-V2.3）": "H1 Seal Ring (B-V2.3)",
"H1密封圈（B-V3）": "H1 Seal Ring (B-V3)", "H1密封圈（B-V8.4）": "H1 Seal Ring (B-V8.4)",
"H1阻水圈（B-V9.3）": "H1 Water Seal Ring (B-V9.3)", "H1阻水圈（B-V10）": "H1 Water Seal Ring (B-V10)",
"H1密封圈（B-V1）": "H1 Seal Ring (B-V1)", "发动机密封圈修理包(潍柴）": "Engine Seal Repair Kit (Weichai)",
"发动机密封圈修理包（全车）": "Engine Seal Repair Kit (Complete)", "P13机油喷嘴": "P13 Oil Nozzle",
"H1机油喷嘴": "H1 Oil Nozzle", "L10喷油泵润滑油管": "L10 Injection Pump Lube Oil Pipe",
"12PK自动张紧轮": "12PK Auto Tensioner", "油尺芯": "Dipstick Core",
"P7机油尺总成": "P7 Oil Dipstick Assembly", "排气门挺住总成": "Exhaust Valve Tappet Assembly",
"H10进气门挺住总成": "H10 Intake Valve Tappet Assembly", "10.9-8*100法兰面六角头螺栓": "10.9-8*100 Hex Flange Bolt",
"(4PK1251)多挈带": "(4PK1251) Poly-V Belt", "天然气盖板": "Natural Gas Cover Plate",
"国四D10发动机螺栓": "China-IV D10 Engine Bolt", "10*95法兰面六角头螺栓": "10*95 Hex Flange Bolt",
"10*105法兰面六角头螺栓": "10*105 Hex Flange Bolt", "10*80法兰面六角头螺栓": "10*80 Hex Flange Bolt",
"10*65内六角螺栓": "10*65 Socket Bolt", "P6气门弹簧上座": "P6 Valve Spring Upper Seat",
"角度调节螺栓": "Angle Adjusting Bolt", "MC05/07排气管螺栓(8*40)": "MC05/07 Exhaust Bolt (8*40)",
"MC05/07排气管螺栓": "MC05/07 Exhaust Bolt", "MC11/13排气管螺栓(10*50)": "MC11/13 Exhaust Bolt (10*50)",
"MC11/13/T13排气管螺栓(10*95)": "MC11/13/T13 Exhaust Bolt (10*95)", "M8增压器螺母": "M8 Turbo Nut",
"MC11/13/T13增压器双头螺栓": "MC11/13/T13 Turbo Stud Bolt", "M10法兰面自锁螺母": "M10 Flange Self-Locking Nut",
"MC07增压器双头螺栓": "MC07 Turbo Stud Bolt", "MT13增压器双头螺栓(10*25)": "MT13 Turbo Stud Bolt (10*25)",
"D12增压器螺栓10*30": "D12 Turbo Bolt 10*30", "D12增压器螺栓10*45": "D12 Turbo Bolt 10*45",
"精滤器-喷油泵燃油管": "Fine Filter-to-Injection Pump Fuel Pipe", "H09机油尺": "H09 Oil Dipstick",
"P12输出法兰": "P12 Output Flange", "M10自锁螺母": "M10 Self-Locking Nut",
"MC05增压器双头螺栓": "MC05 Turbo Stud Bolt", "15335盖（新式）": "15335 Cover (New Type)",
"缸盖罩（天然气）": "Cylinder Head Cover (Natural Gas)", "进水管座": "Water Inlet Seat",
"10*100六角头螺栓": "10*100 Hex Head Bolt", "12*90法兰面六角头螺栓": "12*90 Hex Flange Bolt",
"12100法兰面六角头螺栓": "12100 Hex Flange Bolt", "8*50法兰面六角头": "8*50 Hex Flange Head",
"6*20法兰面六角头": "6*20 Hex Flange Head", "M8大垫圈": "M8 Large Washer",
"8*110法兰面六角头螺栓": "8*110 Hex Flange Bolt", "8*135法兰面六角头螺栓": "8*135 Hex Flange Bolt",
"H10燃油进油管": "H10 Fuel Feed Pipe", "M12平垫": "M12 Flat Washer", "M12镀锌螺母": "M12 Galvanized Nut",
"8*55带齿法兰面六角头": "8*55 Toothed Hex Flange Head",
"P12/P13增压器水管总成": "P12/P13 Turbo Water Pipe Assembly", "汽缸盖罩盖板": "Cylinder Head Cover Plate",
"连杆螺丝": "Connecting Rod Screw", "副厂油门球头": "Aftermarket Throttle Ball Joint",
"缸盖罩 上罩": "Cylinder Head Cover Upper Shield", "前油气分离器": "Front Oil-Gas Separator",
"H10自动张紧轮": "H10 Auto Tensioner", "空气过渡接管": "Air Transition Pipe",
"M14法兰面螺母": "M14 Flange Nut", "P13水泵泵头": "P13 Water Pump Head",
"φ18复合垫片": "φ18 Composite Washer", "H1空压机水管螺母": "H1 Air Compressor Water Pipe Nut",
"六角头法兰面带突齿螺栓": "Hex Flange Bolt with Serration", "H10排气管隔热罩": "H10 Exhaust Heat Shield",
"摇臂罩支撑块": "Rocker Cover Support Block", "H10气缸盖罩衬垫": "H10 Cylinder Head Cover Gasket",
"H1挺住导向螺钉": "H1 Tappet Guide Screw", "过桥钢管0245/1": "Bridge Steel Pipe 0245/1",
"80554柴滤座": "80554 Diesel Filter Seat", "H1机油冷却器芯密封圈": "H1 Oil Cooler Core Seal Ring",
"P12NG增压器进油管总成": "P12NG Turbo Oil Feed Pipe Assembly", "P13EVB摇臂支架": "P13 EVB Rocker Bracket",
"P13EVB摇臂支架（拆机）": "P13 EVB Rocker Bracket (Dismantled)",
"EVB支架总成（拆机)": "EVB Bracket Assembly (Dismantled)", "输出齿轮（后驱力0": "Output Gear (Rear Drive Unit)",
"中间齿轮（后驱力）": "Idler Gear (Rear Drive Unit)", "P7喷油器衬套": "P7 Injector Bushing",
"MC11/13活塞销卡簧": "MC11/13 Piston Pin Circlip", "曼水堵（φ45）": "MAN Water Core Plug (φ45)",
"进气门油封": "Intake Valve Stem Seal", "MC11/13气门弹簧": "MC11/13 Valve Spring",
"排气门油封": "Exhaust Valve Stem Seal", "14传动轴螺母": "14 Drive Shaft Nut",
"MC11/13主轴承螺栓": "MC11/13 Main Bearing Bolt", "H1机油模块修理包": "H1 Oil Module Repair Kit",
"14PK水泵泵头": "14PK Water Pump Head", "P7燃油回油管": "P7 Fuel Return Pipe",
"客车空压机进水管": "Coach Air Compressor Water Inlet Pipe", "L10增压器回油管": "L10 Turbo Oil Return Pipe",
"气泵螺旋管（09款)": "Air Pump Spiral Pipe (09 Model)", "空压机进气管总成": "Air Compressor Intake Pipe Assembly",
"六角螺母（发电机用)": "Hex Nut (for Alternator)", "间隔快(发电机用）": "Spacer Block (for Alternator)",
"P7紧扣螺母": "P7 Lock Nut", "国四空压机密封圈": "China-IV Air Compressor Seal Ring",
"高压油泵密封圈": "High Pressure Pump Seal Ring", "油泵法兰密封圈": "Oil Pump Flange Seal Ring",
"张紧轮座（三孔）": "Tensioner Seat (3-Hole)", "MC05/07气门弹簧": "MC05/07 Valve Spring",
"手油泵": "Hand Fuel Pump", "L10进气接管": "L10 Intake Connection", "P12进气接管": "P12 Intake Connection",
"H1喷油器衬套": "H1 Injector Bushing", "M10法兰面螺母": "M10 Flange Nut",
"水堵17": "Water Core Plug 17", "水堵25": "Water Core Plug 25", "水堵22": "Water Core Plug 22",
"水堵30": "Water Core Plug 30", "水堵40": "Water Core Plug 40", "水堵60": "Water Core Plug 60",
"水堵75": "Water Core Plug 75", "H10机油冷却器盖垫片": "H10 Oil Cooler Cover Gasket",
"-0002低压滤芯": "-0002 Low Pressure Filter Element", "卡套式直通体": "Ferrule Type Straight Body",
"H09机油尺管": "H09 Dipstick Tube", "H10曲轴前油封": "H10 Crankshaft Front Oil Seal",
"H10曲轴后油封": "H10 Crankshaft Rear Oil Seal", "P12机油喷嘴空心螺栓": "P12 Oil Nozzle Hollow Bolt",
"P12EVB支架衬套密封圈": "P12 EVB Bracket Bushing Seal Ring", "226B加机油口盖": "226B Oil Fill Cap",
"P12大泵全车螺栓": "P12 Pump Complete Bolt Set", "MC05/07连杆螺栓": "MC05/07 Connecting Rod Bolt",
"MC05/07缸盖主螺栓": "MC05/07 Head Main Bolt", "MC11/13飞轮螺栓": "MC11/13 Flywheel Bolt",
"MC05/07油底壳托快": "MC05/07 Oil Pan Support Block", "H10中间齿轮组件": "H10 Idler Gear Module",
"H10喷油泵齿轮": "H10 Injection Pump Gear", "H10空压机齿轮": "H10 Air Compressor Gear",
"H10曲轴齿轮": "H10 Crankshaft Gear", "P13凸轮轴齿轮": "P13 Camshaft Gear",
"P13机油泵齿轮": "P13 Oil Pump Gear", "P13喷油泵齿轮": "P13 Injection Pump Gear",
"国五火花塞": "China-V Spark Plug", "国六火花塞": "China-VI Spark Plug",
"国五点火线圈总成": "China-V Ignition Coil Assembly", "国六点火线圈总成": "China-VI Ignition Coil Assembly",
"石棉排气管垫": "Asbestos Exhaust Gasket", "M14螺母": "M14 Nut",
"燃油进油管总成/粗滤-输油泵": "Fuel Feed Pipe / Primary Filter-Feed Pump",
"燃油进油管总成/粗滤-喷油泵": "Fuel Feed Pipe / Primary Filter-Injection Pump",
"H10后排气支管": "H10 Rear Exhaust Manifold", "M8螺母": "M8 Nut", "H1排气管垫": "H1 Exhaust Gasket",
"P12空压机齿轮": "P12 Air Compressor Gear", "废气控制阀管": "Exhaust Control Valve Pipe",
"左油底壳托快": "Left Oil Pan Support Block", "右油底壳托快": "Right Oil Pan Support Block",
"工程机械节温器壳": "Machinery Thermostat Housing", "P10H空压机进气管": "P10H Air Compressor Intake Pipe",
"MC11排气管垫片": "MC11 Exhaust Gasket", "MC11/13增压器垫片": "MC11/13 Turbo Gasket",
"H10排气管螺栓": "H10 Exhaust Pipe Bolt", "内六角圆柱头螺栓": "Socket Head Cap Bolt",
"10*30六角法兰面螺栓": "10*30 Hex Flange Bolt", "D10共轨支架总成": "D10 Common Rail Bracket Assembly",
"D10线束支架": "D10 Wiring Harness Bracket", "D10六角螺塞": "D10 Hex Plug",
"D10高压油管支撑架（一）": "D10 HP Pipe Support Bracket (1)",
"D10高压油管支撑架（二）": "D10 HP Pipe Support Bracket (2)",
"D10高压油管支撑架（三）": "D10 HP Pipe Support Bracket (3)",
"6*45六角头螺栓": "6*45 Hex Head Bolt", "H1机油尺接头": "H1 Dipstick Joint",
"4L曼机油": "4L MAN Engine Oil", "H1皮带轮螺栓": "H1 Pulley Bolt",
"橡胶支座总成": "Rubber Mount Assembly", "H1摇臂轴组件": "H1 Rocker Arm Shaft Module",
"H1进气门摇臂": "H1 Intake Valve Rocker Arm", "26转向泵空芯螺栓": "26 Steering Pump Hollow Bolt",
"φ26复合垫片": "φ26 Composite Washer", "H10.5增压器隔热罩": "H10.5 Turbo Heat Shield",
"10.9六角头螺栓": "Hex Head Bolt Grade 10.9", "8*25六角法兰面螺栓": "8*25 Hex Flange Bolt",
"国四ECU支撑板": "China-IV ECU Support Plate", "达克罗排气管螺栓": "Dacromet Exhaust Pipe Bolt",
"P13火花塞衬套": "P13 Spark Plug Bushing", "原厂H10机油尺管": "OEM H10 Dipstick Tube",
"P13油气分离器支架": "P13 Oil-Gas Separator Bracket", "ECU护罩": "ECU Cover",
"ECU支撑块": "ECU Support Block", "P12/13管接头组件": "P12/13 Pipe Joint Assembly",
"点火线圈垫块": "Ignition Coil Pad Block", "尿素喷嘴支撑块": "Urea Nozzle Support Block",
"模块转子": "Module Rotor", "空压机排气接头": "Air Compressor Exhaust Joint",
"空压机管接头": "Air Compressor Pipe Joint", "P6气门调整螺栓": "P6 Valve Adjustment Bolt",
"P12硅油减震器挡板": "P12 Viscous Damper Baffle", "沉头螺栓（V1.94）": "Countersunk Bolt (V1.94)",
"10*110法兰面六角头螺栓": "10*110 Hex Flange Bolt", "带肩六角头螺栓": "Shoulder Hex Bolt",
"P13点火线圈衬套压板": "P13 Ignition Coil Bushing Plate", "摇臂短螺丝": "Rocker Arm Short Screw",
"空芯螺栓(A6.3)": "Hollow Bolt (A6.3)", "P13废气旁通阀出气管": "P13 Waste Gate Outlet Pipe",
"P13油气分离器管": "P13 Oil-Gas Separator Pipe",
"P13旁通阀废气出气管V62": "P13 Bypass Exhaust Outlet Pipe V62",
"P13旁通阀废气出气管": "P13 Bypass Exhaust Outlet Pipe", "P13盖板": "P13 Cover Plate",
"气管接头": "Air Pipe Joint", "废气旁通阀进气管": "Waste Gate Intake Pipe",
"国四空压机接头": "China-IV Air Compressor Joint",
"空压机回水管（带卡套螺母）": "Air Compressor Return Water Pipe (with Ferrule Nut)",
"WEVB接头": "WEVB Joint", "H10进气接管": "H10 Intake Connection",
"发动机线束密封圈": "Engine Harness Seal Ring", "水冷增压器进水管": "Water-Cooled Turbo Water Inlet Pipe",
"P13燃油进油管总成": "P13 Fuel Feed Pipe Assembly", "WP13增压器水管总成": "WP13 Turbo Water Pipe Assembly",
"P13排气门摇臂": "P13 Exhaust Valve Rocker Arm", "P13连杆螺栓": "P13 Connecting Rod Bolt",
"P12/13缸盖主螺栓": "P12/13 Head Main Bolt", "涨紧轮座（四孔）": "Tensioner Seat (4-Hole)",
"P7气门调整螺栓": "P7 Valve Adjustment Bolt", "H10火花塞衬套密封圈": "H10 Spark Plug Bushing Seal Ring",
"H10圆柱销修理包": "H10 Dowel Pin Repair Kit", "12*50内六角螺栓": "12*50 Socket Bolt",
"8*110内六角螺栓": "8*110 Socket Bolt", "8*80内六角螺栓": "8*80 Socket Bolt",
"8*105内六角螺栓": "8*105 Socket Bolt", "缸盖串水管": "Head Crossover Water Pipe",
"六角螺母（20*1.5）": "Hex Nut (20*1.5)", "机油冷却器盖接头": "Oil Cooler Cover Joint",
"卡箍(110-118)": "Hose Clamp (110-118)", "旁通阀出气管": "Bypass Outlet Pipe",
"P7机油喷嘴-35.4": "P7 Oil Nozzle -35.4", "P7机油喷嘴": "P7 Oil Nozzle",
"中间齿轮盖板": "Idler Gear Cover Plate", "WP7发电机支架": "WP7 Alternator Bracket",
"P10H燃油回油管总成": "P10H Fuel Return Pipe Assembly", "50-70水管卡子": "50-70 Water Pipe Clamp",
"10-19水管卡子": "10-19 Water Pipe Clamp", "心组件20152": "Core Module 20152",
"尿素箱拉紧带": "Urea Tank Tensioning Strap", "D12空气管": "D12 Air Pipe",
"H10空调压缩机支架": "H10 AC Compressor Bracket", "联轴器螺栓": "Coupling Bolt",
"P13增压器出水管总成": "P13 Turbo Water Outlet Pipe Assembly", "P12/13ECU支架": "P12/13 ECU Bracket",
"P12ECU支架": "P12 ECU Bracket", "套筒": "Sleeve", "H09机油尺总成": "H09 Oil Dipstick Assembly",
"P13滤清器支架": "P13 Filter Bracket", "P7回油管接头": "P7 Oil Return Joint",
"P12排气管支架": "P12 Exhaust Pipe Bracket",
"P12发动机全套螺栓（唐西春）": "P12 Engine Complete Bolt Kit (Tang Xichun)",
"H1集滤器总成": "H1 Oil Strainer Assembly", "曼惰轮": "MAN Idler Pulley",
"H1排气门桥组件": "H1 Exhaust Valve Bridge Assembly", "H1进气门桥": "H1 Intake Valve Bridge",
"0458盖板": "0458 Cover Plate", "输油泵-精滤器燃油管总成": "Feed Pump-to-Fine Filter Fuel Pipe Assembly",
"精滤器-喷油泵燃油进油管总成": "Fine Filter-to-Injection Pump Fuel Pipe Assembly",
"P12缸盖圆柱销修理包": "P12 Head Dowel Pin Repair Kit", "DPM进水管": "DPM Water Inlet Pipe",
"DPM回水管": "DPM Water Return Pipe", "信号盘": "Signal Disc", "226B气缸盖罩": "226B Cylinder Head Cover",
"全铁全车水堵": "All-Iron Water Core Plug Kit", "WP13机油冷却器盖垫": "WP13 Oil Cooler Cover Gasket",
"P12机油冷却器盖垫片": "P12 Oil Cooler Cover Gasket", "空压机水管总成": "Air Compressor Water Pipe Assembly",
"226B缸盖螺栓": "226B Cylinder Head Bolt", "P12后驱力总成": "P12 Rear Drive Assembly",
"P13连接板": "P13 Connecting Plate", "P7发电机支架": "P7 Alternator Bracket",
"P12排气门座": "P12 Exhaust Valve Seat", "1.7米套管": "1.7m Sleeve Pipe",
"L10空压机进气管": "L10 Air Compressor Intake Pipe", "H10节温器支撑块": "H10 Thermostat Support Block",
"618出水管": "618 Water Outlet Pipe", "W型接头": "W-Type Joint",
"冷却器连接胶管": "Cooler Connecting Rubber Hose", "P13机油冷却器芯": "P13 Oil Cooler Core",
"P10H燃油进油管总成": "P10H Fuel Feed Pipe Assembly", "WP7油底壳": "WP7 Oil Pan",
"P12气缸盖罩": "P12 Cylinder Head Cover", "P13缸盖罩": "P13 Cylinder Head Cover",
"P13增压器进油管总成": "P13 Turbo Oil Feed Pipe Assembly", "P6油底壳垫": "P6 Oil Pan Gasket",
"WEVB进油管总成（短）": "WEVB Oil Inlet Pipe Assembly (Short)", "水堵（18*7.3）": "Water Core Plug (18*7.3)",
"P13机油尺": "P13 Oil Dipstick", "M16气路管接头（弯）": "M16 Air Line Joint (Bent)",
"M12气路管接头（弯）": "M12 Air Line Joint (Bent)", "M14气路管接头（弯）": "M14 Air Line Joint (Bent)",
"六角法兰带齿螺栓": "Hex Flange Toothed Bolt", "压缩机支架(H10.5)": "AC Compressor Bracket (H10.5)",
"后驱力输出轴组件": "Rear Drive Output Shaft Module", "油箱盖（原厂）": "Fuel Tank Cap (OEM)",
"油箱盖（普通）": "Fuel Tank Cap (Standard)", "橡胶套": "Rubber Sleeve",
"曼机油尺上头": "MAN Dipstick Upper Head", "D12硅油减震器挡板": "D12 Viscous Damper Baffle",
"H节温器支撑块": "H Thermostat Support Block", "油气预分离器": "Oil-Gas Pre-Separator",
"H10油气分离器橡胶管": "H10 Oil-Gas Separator Rubber Pipe", "P7汽缸垫": "P7 Cylinder Head Gasket",
"P7进气管垫": "P7 Intake Gasket", "P7缸盖罩衬垫": "P7 Head Cover Gasket",
"排气制动卡箍": "Exhaust Brake Clamp", "M11汽缸垫": "M11 Cylinder Head Gasket",
"M13汽缸垫": "M13 Cylinder Head Gasket", "D10发电机螺栓包": "D10 Alternator Bolt Kit",
"D10喷油器喷油泵固定螺栓": "D10 Injector-Pump Fixing Bolt", "D10柴滤支架螺栓": "D10 Diesel Filter Bracket Bolt",
"D10安全阀总成": "D10 Safety Valve Assembly", "D10进气管固定螺栓": "D10 Intake Pipe Fixing Bolt",
"D10出水管节温器固定螺栓": "D10 Thermostat Fixing Bolt", "D10齿轮室端盖固定螺栓": "D10 Gear Housing Cover Bolt",
"D10涨紧轮螺丝（三孔）": "D10 Tensioner Screw (3-Hole)",
"重汽D10发动机全套螺栓": "Sinotruk D10 Engine Complete Bolt Kit", "拉进螺栓": "Tensioning Bolt",
}
