# -*- coding: utf-8 -*-
"""批次6 英文名词典 chunk1（第 1-450 个漏网名称，按频次序）"""
D1 = {
"圆柱销": "Dowel Pin", "水堵": "Water Core Plug", "空压机进气管": "Air Compressor Intake Pipe",
"空压机回水管": "Air Compressor Return Water Pipe", "连杆总成": "Connecting Rod Assembly",
"前排气管": "Front Exhaust Pipe", "卡箍": "Hose Clamp", "螺钉": "Screw",
"拉紧块": "Tensioning Block", "风扇托架总成": "Fan Bracket Assembly",
"加机油短管组件": "Oil Fill Short Pipe Assembly", "燃油进油管总成": "Fuel Feed Pipe Assembly",
"连杆瓦": "Connecting Rod Bearing", "双头螺柱": "Double-End Stud", "夹紧块": "Clamping Block",
"汽缸盖": "Cylinder Head", "胶管": "Rubber Hose", "空压机进水管": "Air Compressor Water Inlet Pipe",
"自动涨紧轮": "Auto Tensioner", "风扇连接盘": "Fan Coupling Disc", "连接盘": "Coupling Disc",
"汽缸垫": "Cylinder Head Gasket", "集滤器总成": "Oil Suction Strainer Assembly",
"连接弯管": "Connecting Elbow Pipe", "机油冷却器盖": "Oil Cooler Cover",
"涨紧轮": "Tensioner Pulley", "风扇轮毂": "Fan Hub", "柴油滤芯": "Diesel Filter Element",
"润滑油管": "Lube Oil Pipe", "空压机": "Air Compressor", "油门杠杆总成": "Throttle Lever Assembly",
"工程机械支撑块": "Construction Machinery Support Block", "空压机总成": "Air Compressor Assembly",
"自动张紧轮": "Auto Tensioner", "放气管总成": "Air Bleed Pipe Assembly", "连接圈": "Connecting Ring",
"空压机水管": "Air Compressor Water Pipe", "空压机齿轮盖": "Air Compressor Gear Cover",
"内六角圆柱螺栓": "Socket Head Bolt", "进气门座": "Intake Valve Seat", "排气门座": "Exhaust Valve Seat",
"中间齿轮轴": "Idler Gear Shaft", "机油压力感应塞": "Oil Pressure Sensor", "风扇叶": "Fan Blade",
"中间法兰": "Intermediate Flange", "进油管总成（长）": "Oil Inlet Pipe Assembly (Long)",
"惰轮": "Idler Pulley", "多韧带": "Poly-V Belt", "机油压力传感器": "Oil Pressure Sensor",
"P12水泵接头": "P12 Water Pump Joint", "六角螺塞": "Hex Plug", "涨紧轮座": "Tensioner Seat",
"主轴承螺栓": "Main Bearing Bolt", "机油喷嘴组件": "Oil Nozzle Assembly", "机滤座": "Oil Filter Bracket",
"固定板": "Fixing Plate", "管子总成": "Pipe Assembly", "磁性螺塞": "Magnetic Plug",
"回油管": "Oil Return Pipe", "耐热螺栓": "Heat-Resistant Bolt", "水温传感器": "Water Temperature Sensor",
"空压机齿轮": "Air Compressor Gear", "多軔带": "Poly-V Belt", "六角螺母": "Hex Nut",
"气路连接胶管": "Air Line Rubber Hose", "缸盖罩": "Cylinder Head Cover",
"排气门摇臂": "Exhaust Valve Rocker Arm", "中间齿轮总成": "Idler Gear Assembly",
"转向助力泵": "Power Steering Pump", "发动机支架": "Engine Mount Bracket",
"硅油减震器": "Viscous Damper", "加机油短管": "Oil Fill Short Pipe", "风扇法兰": "Fan Flange",
"硅油风扇离合器": "Viscous Fan Clutch", "螺塞": "Plug", "盖板": "Cover Plate",
"燃油回油管总成": "Fuel Return Pipe Assembly", "L10燃油进油管总成": "L10 Fuel Feed Pipe Assembly",
"右支架": "Right Bracket", "机油冷却器芯": "Oil Cooler Core", "橡胶软管": "Rubber Hose",
"空压机传动轴": "Air Compressor Drive Shaft", "端盖": "End Cover", "进气接管": "Intake Connection Pipe",
"发动机后支撑": "Engine Rear Support", "压气机进气管": "Compressor Intake Pipe", "衬套": "Bushing",
"10.9级六角头螺栓": "Hex Head Bolt Grade 10.9", "机油压力传感器座": "Oil Pressure Sensor Bracket",
"张紧轮": "Tensioner", "前隔热罩": "Front Heat Shield", "后隔热罩": "Rear Heat Shield",
"发动机全套螺栓": "Engine Complete Bolt Kit", "P12燃油管": "P12 Fuel Pipe", "风扇托架": "Fan Bracket",
"缸盖副螺栓": "Cylinder Head Auxiliary Bolt", "暖风接头": "Heater Joint",
"回油管接头": "Oil Return Pipe Joint", "油路连接胶管": "Oil Line Rubber Hose",
"火花塞衬套": "Spark Plug Bushing", "P13增压器回油管": "P13 Turbo Oil Return Pipe",
"H1支撑块": "H1 Support Block", "冷却液连接胶管": "Coolant Rubber Hose",
"管夹总成": "Pipe Clamp Assembly", "H10.5管接头组件": "H10.5 Pipe Joint Assembly",
"弹性圆柱销": "Spring Dowel Pin", "进气门": "Intake Valve", "挡板": "Baffle Plate",
"隔套": "Spacer Sleeve", "孔用弹性挡圈": "Circlip for Hole", "联轴器总成": "Coupling Assembly",
"油门悬臂": "Throttle Bellcrank", "燃油粗滤芯": "Fuel Primary Filter Element",
"摇臂座": "Rocker Arm Seat", "内六角圆柱头螺钉": "Socket Head Cap Screw",
"柴油滤芯（粗）": "Diesel Filter Element (Primary)", "空压机出水管": "Air Compressor Water Outlet Pipe",
"空压机进气管接头": "Air Compressor Intake Joint", "堵塞": "Plug", "自锁螺母": "Self-Locking Nut",
"气缸垫": "Cylinder Head Gasket", "全车垫": "Complete Gasket Kit", "P12飞轮": "P12 Flywheel",
"1.5KW发电机": "1.5KW Alternator", "连接法兰": "Connecting Flange",
"缸盖罩衬垫": "Cylinder Head Cover Gasket", "P12空压机润滑油管": "P12 Air Compressor Lube Oil Pipe",
"卡套": "Ferrule Sleeve", "尿素管接头": "Urea Pipe Joint", "缸盖夹紧块": "Cylinder Head Clamping Block",
"镀锌水堵": "Galvanized Water Core Plug", "缸盖主螺栓": "Cylinder Head Main Bolt",
"P12连杆总成": "P12 Connecting Rod Assembly", "单管卡子总成": "Single Pipe Clamp Assembly",
"多楔带": "Poly-V Belt", "H1空压机水管": "H1 Air Compressor Water Pipe",
"护风圈支架": "Fan Shroud Bracket", "P13喷油器回油管": "P13 Injector Return Pipe",
"D10高压油管": "D10 High Pressure Pipe", "护风罩支架": "Fan Shroud Bracket",
"P7燃油管管接头": "P7 Fuel Pipe Joint", "机油冷却器盖垫片": "Oil Cooler Cover Gasket",
"加油管组件": "Oil Fill Pipe Assembly", "带纤维夹层橡胶软管": "Rubber Hose with Fabric Insert",
"中间齿轮轴螺栓": "Idler Gear Shaft Bolt", "护风罩总成": "Fan Shroud Assembly",
"左支架": "Left Bracket", "φ10复合垫片": "φ10 Composite Washer", "弹性连接片": "Elastic Connecting Plate",
"交流发电机": "Alternator", "回油管总成": "Oil Return Pipe Assembly",
"废气涡轮增压器": "Exhaust Gas Turbocharger", "燃油粗滤器总成": "Fuel Primary Filter Assembly",
"中冷进气管": "Intercooler Intake Pipe", "隔热罩": "Heat Shield", "垫块": "Pad Block",
"排气门": "Exhaust Valve", "进气门桥": "Intake Valve Bridge", "排气门桥": "Exhaust Valve Bridge",
"进气温度传感器": "Intake Air Temperature Sensor", "后排气歧管": "Rear Exhaust Manifold",
"双缸空压机": "Two-Cylinder Air Compressor", "过渡接头": "Adapter Joint",
"连杆衬套": "Connecting Rod Bushing", "P10喷油泵法兰": "P10 Injection Pump Flange",
"机油喷嘴": "Oil Nozzle", "M8油门球头": "M8 Throttle Ball Joint", "空气管": "Air Pipe",
"进油管总成（短）": "Oil Inlet Pipe Assembly (Short)", "空压机进油管": "Air Compressor Oil Inlet Pipe",
"空压机垫片": "Air Compressor Gasket", "带泵柴滤座": "Diesel Filter Seat with Pump",
"吸油管总成": "Oil Suction Pipe Assembly", "加机油口盖": "Oil Fill Cap", "汽缸套": "Cylinder Liner",
"柴油滤芯总成": "Diesel Filter Element Assembly", "P12喷油器总成": "P12 Injector Assembly",
"高压油泵托架": "High Pressure Pump Bracket", "双温控开关": "Dual Thermostatic Switch",
"618水泵垫": "618 Water Pump Gasket", "P12节温器芯": "P12 Thermostat Element",
"空压机回水管总成": "Air Compressor Return Water Pipe Assembly", "P12排气管": "P12 Exhaust Pipe",
"D12燃油管": "D12 Fuel Pipe", "空压机缸盖总成": "Air Compressor Cylinder Head Assembly",
"放气管": "Air Bleed Pipe", "回水管接头": "Water Return Pipe Joint", "六角薄螺母": "Hex Thin Nut",
"间隔块": "Spacer Block", "螺座": "Threaded Seat", "空压机进气接头": "Air Compressor Intake Joint",
"空压机润滑油管": "Air Compressor Lube Oil Pipe", "发动机前左支架": "Engine Front Left Bracket",
"出水管垫片": "Water Outlet Gasket", "精滤支架": "Fine Filter Bracket",
"内螺纹圆柱销": "Internally Threaded Dowel Pin", "旋入接头": "Screw-In Joint",
"集滤器": "Oil Suction Strainer", "226B汽缸垫": "226B Cylinder Head Gasket",
"缸盖螺栓": "Cylinder Head Bolt", "M12螺母": "M12 Nut", "发动机吊板": "Engine Lifting Plate",
"工程机械空压机水管": "Machinery Air Compressor Water Pipe", "H10支撑块": "H10 Support Block",
"P7空压机水管总成": "P7 Air Compressor Water Pipe Assembly",
"P7空压机润滑油管": "P7 Air Compressor Lube Oil Pipe",
"P7燃油进油管总成": "P7 Fuel Feed Pipe Assembly", "H10集滤器支架": "H10 Oil Strainer Bracket",
"H1护风罩支架": "H1 Fan Shroud Bracket", "空压机接头": "Air Compressor Joint",
"P13中间齿轮总成": "P13 Idler Gear Assembly", "H1空压机水管总成": "H1 Air Compressor Water Pipe Assembly",
"铰链螺栓": "Hinge Bolt", "六角头法兰面螺栓": "Hex Flange Bolt",
"M10施必牢螺母": "M10 Anti-Loosening Nut", "压气机气管": "Compressor Air Pipe",
"P13排气管总成（带隔热棉）": "P13 Exhaust Pipe Assembly (with Heat Insulation)",
"M12尼龙快速接头": "M12 Nylon Quick Coupling", "MC11油底壳托快": "MC11 Oil Pan Support Block",
"H10集滤器": "H10 Oil Strainer", "P13增压器隔热罩": "P13 Turbo Heat Shield",
"P13空压机水管": "P13 Air Compressor Water Pipe", "P8排气管垫": "P8 Exhaust Pipe Gasket",
"P13燃油进油管": "P13 Fuel Feed Pipe", "冷却液连接管": "Coolant Connecting Pipe",
"（耐热钢）排气管螺栓": "Exhaust Pipe Bolt (Heat-Resistant Steel)", "P8模块密封圈": "P8 Module Seal Ring",
"缸盖副栓": "Cylinder Head Auxiliary Bolt", "通风弯管": "Ventilation Elbow Pipe",
"加油短管组件": "Oil Fill Short Pipe Assembly", "油尺管上组件": "Dipstick Tube Upper Assembly",
"无纤维夹层橡胶软管": "Rubber Hose without Fabric Insert", "φ48曲轴法兰": "φ48 Crankshaft Flange",
"带肩螺母": "Shoulder Nut", "排气门弹簧下座": "Exhaust Valve Spring Lower Seat",
"进气门摇臂": "Intake Valve Rocker Arm", "中间齿轮": "Idler Gear",
"硅油离合器风扇": "Viscous Clutch Fan", "护风带总成": "Fan Shroud Strip Assembly",
"旋转式机油滤芯总成": "Spin-on Oil Filter Assembly", "输油泵总成": "Fuel Feed Pump Assembly",
"喷油嘴": "Injection Nozzle", "燃油滤清器总成": "Fuel Filter Assembly",
"温度传感器": "Temperature Sensor", "10*90排气管螺栓": "10*90 Exhaust Pipe Bolt",
"空压机轴油封": "Air Compressor Shaft Oil Seal", "空压机压紧圈": "Air Compressor Pressing Ring",
"减震器": "Damper", "压紧块": "Pressing Block", "防护圈": "Guard Ring",
"集滤器垫片": "Oil Strainer Gasket", "618喷油泵齿轮": "618 Injection Pump Gear",
"液压泵": "Hydraulic Pump", "P12气门调整螺栓": "P12 Valve Adjustment Bolt",
"水冷空压机": "Water-Cooled Air Compressor", "空压机修理包": "Air Compressor Repair Kit",
"拉紧螺栓": "Tensioning Bolt", "油泵托架": "Oil Pump Bracket",
"加油管盖总成": "Oil Fill Pipe Cap Assembly", "管夹": "Pipe Clamp",
"无纤维夹层的橡胶软管": "Rubber Hose without Fabric Insert",
"发动机前吊环": "Engine Front Lifting Eye", "发动机后吊环": "Engine Rear Lifting Eye",
"冷却水软管": "Cooling Water Hose", "进气压力传感器": "Intake Pressure Sensor",
"ECU控制总成": "ECU Control Assembly", "联接软管": "Connecting Hose",
"进油管垫片": "Oil Inlet Pipe Gasket", "回油管法兰垫片": "Oil Return Pipe Flange Gasket",
"空压机进水管接头": "Air Compressor Water Inlet Joint", "EVB进油管总成": "EVB Oil Inlet Pipe Assembly",
"六角头螺塞": "Hex Head Plug", "共轨管": "Common Rail",
"放气阀增压器": "Turbocharger with Bleed Valve", "橡胶管": "Rubber Hose",
"进气门摇臂总成": "Intake Valve Rocker Arm Assembly",
"排气门摇臂总成": "Exhaust Valve Rocker Arm Assembly", "油门悬臂总成": "Throttle Bellcrank Assembly",
"EGR冷却器出水管": "EGR Cooler Water Outlet Pipe", "EGR排气管": "EGR Exhaust Pipe",
"EGR排气阀门总成": "EGR Exhaust Valve Assembly", "EGR水管垫片": "EGR Water Pipe Gasket",
"O型橡胶密封圈": "O-Ring", "EGR冷却器进水管": "EGR Cooler Water Inlet Pipe",
"电磁阀": "Solenoid Valve", "柴油滤芯（细）": "Diesel Filter Element (Fine)",
"润滑油管(带弯)": "Lube Oil Pipe (Bent)", "发动机前支撑": "Engine Front Support",
"P10起动机": "P10 Starter", "铁风圈": "Iron Fan Shroud", "P12全车水堵": "P12 Water Core Plug Kit",
"机油压力温度传感器": "Oil Pressure & Temperature Sensor", "转速传感器": "Speed Sensor",
"连接片总成": "Connecting Plate Assembly", "油门球头": "Throttle Ball Joint",
"燃油粗滤器": "Fuel Primary Filter", "天方地圆": "Round-to-Square Adapter",
"汽缸垫（两气门）": "Cylinder Head Gasket (2-Valve)", "自动涨紧轮110003": "Auto Tensioner 110003",
"空压机活塞环": "Air Compressor Piston Ring", "EGR出气管": "EGR Outlet Pipe",
"发动机后支撑螺栓": "Engine Rear Support Bolt", "电子油门踏板": "Electronic Throttle Pedal",
"618活塞环": "618 Piston Ring", "弹性挡圈（后驱力）": "Circlip (Rear Drive Unit)",
"输出法兰（后驱力）": "Output Flange (Rear Drive Unit)", "传动轴螺丝母": "Propeller Shaft Nut",
"空压机缸体": "Air Compressor Cylinder Block", "空压机活塞肖": "Air Compressor Piston Pin",
"空压机活塞": "Air Compressor Piston", "P12活塞": "P12 Piston", "EGR进气管": "EGR Intake Pipe",
"P12高压油管": "P12 High Pressure Pipe", "3055垫片": "3055 Washer",
"惰性齿轮（42齿）": "Idler Gear (42 Teeth)", "输出齿轮": "Output Gear",
"P10飞轮壳": "P10 Flywheel Housing", "全车水堵": "Water Core Plug Kit",
"停油缸总成": "Fuel Cut-Off Cylinder Assembly", "M8自锁螺母": "M8 Self-Locking Nut",
"成型胶管": "Molded Rubber Hose", "P12进气门": "P12 Intake Valve",
"P12空压机回水管": "P12 Air Compressor Return Water Pipe", "润滑油管总成": "Lube Oil Pipe Assembly",
"D12节温器芯": "D12 Thermostat Element", "P12空压机总成": "P12 Air Compressor Assembly",
"燃油水寒宝": "Fuel Water Separator", "氧传感器": "Oxygen Sensor",
"点火线圈总成": "Ignition Coil Assembly", "发动机后托架": "Engine Rear Bracket",
"连杆总成M": "Connecting Rod Assembly M", "多契带": "Poly-V Belt",
"高压油泵总成": "High Pressure Pump Assembly", "P12气门推杆": "P12 Valve Push Rod",
"φ50曲轴法兰": "φ50 Crankshaft Flange", "φ52.4曲轴法兰": "φ52.4 Crankshaft Flange",
"S气门调整螺栓": "S Valve Adjustment Bolt", "拉紧垫块": "Tensioning Pad Block",
"支撑臂": "Support Arm", "调整螺母": "Adjusting Nut", "压板": "Press Plate", "轮毂": "Wheel Hub",
"铭牌": "Name Plate", "缸盖罩密封垫": "Cylinder Head Cover Seal",
"集滤器小支架": "Oil Strainer Small Bracket", "球面垫圈": "Spherical Washer",
"连杆螺栓": "Connecting Rod Bolt", "放水阀总成": "Water Drain Valve Assembly",
"空压机出气接头": "Air Compressor Air Outlet Joint", "双管接头": "Double Pipe Joint",
"摇臂总成": "Rocker Arm Assembly", "8*30六角头螺栓": "8*30 Hex Head Bolt",
"P13汽缸垫": "P13 Cylinder Head Gasket", "加机油管组件": "Oil Fill Pipe Assembly",
"风扇离合器": "Fan Clutch", "P12气门推杆衬套": "P12 Valve Push Rod Bushing",
"发动机前右支架": "Engine Front Right Bracket", "缸盖加紧块": "Cylinder Head Clamping Block",
"HQL增压器进油管": "HQL Turbo Oil Feed Pipe", "惰齿轮总成": "Idler Gear Assembly",
"燃油精滤芯": "Fuel Fine Filter Element", "风扇驱动轴": "Fan Drive Shaft",
"客车飞轮壳螺栓": "Coach Flywheel Housing Bolt", "P12高压油管螺母": "P12 High Pressure Pipe Nut",
"国四排气管": "China-IV Exhaust Pipe", "P12中间齿轮轴": "P12 Idler Gear Shaft",
"10*10圆柱销": "10*10 Dowel Pin", "摇臂轴": "Rocker Arm Shaft",
"D12喷油泵齿轮": "D12 Injection Pump Gear", "气路连接管": "Air Line Connecting Pipe",
"P7连杆螺栓": "P7 Connecting Rod Bolt", "P12水泵总成": "P12 Water Pump Assembly",
"226B阻水圈": "226B Water Seal Ring", "D12主轴承螺栓": "D12 Main Bearing Bolt",
"油门杠杆": "Throttle Lever", "支撑板": "Support Plate", "H10机油尺": "H10 Oil Dipstick",
"P7飞轮螺栓": "P7 Flywheel Bolt", "排气门桥组件": "Exhaust Valve Bridge Assembly",
"三四缸排气管": "No.3-4 Cylinder Exhaust Pipe", "S喷油器压板": "S Injector Press Plate",
"WP7增压器回油管": "WP7 Turbo Oil Return Pipe", "WP7水泵总成": "WP7 Water Pump Assembly",
"H1空压机回水管": "H1 Air Compressor Return Water Pipe",
"H1空压机进气管接头": "H1 Air Compressor Intake Joint",
"H10喷油泵润滑油管": "H10 Injection Pump Lube Oil Pipe",
"WP12喷油器回油管": "WP12 Injector Return Pipe", "P13集滤器": "P13 Oil Strainer",
"H10飞轮螺栓": "H10 Flywheel Bolt", "压气机出气管": "Compressor Air Outlet Pipe",
"P7油底壳垫": "P7 Oil Pan Gasket", "P12油气分离器支架": "P12 Oil-Gas Separator Bracket",
"WP13燃油进油管总成": "WP13 Fuel Feed Pipe Assembly", "M10螺母": "M10 Nut",
"CNG空压机管接头": "CNG Air Compressor Pipe Joint", "进水管接头": "Water Inlet Joint",
"粗滤器-输油泵燃油管总成": "Primary Filter-Feed Pump Fuel Pipe Assembly",
"缸盖罩支撑块": "Cylinder Head Cover Support Block",
"H10燃油回油管总成": "H10 Fuel Return Pipe Assembly", "一体隔热罩": "Integrated Heat Shield",
"ECU支架": "ECU Bracket", "暖风开关": "Heater Switch", "国四节温器芯": "China-IV Thermostat Element",
"水堵45": "Water Core Plug 45", "H10中间齿轮总成": "H10 Idler Gear Assembly",
"H10中间齿轮轴": "H10 Idler Gear Shaft", "涨紧轮支架": "Tensioner Bracket",
"ECU支撑板": "ECU Support Plate", "P13摇臂轴": "P13 Rocker Arm Shaft",
"摇臂弹簧螺丝": "Rocker Arm Spring Screw",
"WP13燃油管进油管总成": "WP13 Fuel Feed Pipe Assembly", "（不带标）隔热罩": "Heat Shield (Unmarked)",
"H10机油尺管": "H10 Dipstick Tube", "P12水管接头": "P12 Water Pipe Joint",
"混合器接头": "Mixer Joint", "P13ECU支撑块": "P13 ECU Support Block",
"固定支架": "Fixing Bracket", "EGR冷却出水管": "EGR Cooler Water Outlet Pipe",
"空压机水管（带卡套螺母）": "Air Compressor Water Pipe (with Ferrule Nut)",
"客车节温器芯": "Coach Thermostat Element",
"P13油气分离器回油管": "P13 Oil-Gas Separator Return Pipe",
"弹性圆柱销-直槽重型": "Spring Dowel Pin - Straight Slot Heavy Duty",
"摇臂电磁阀总成": "Rocker Arm Solenoid Assembly", "摇臂轴座总成": "Rocker Arm Shaft Seat Assembly",
"P13增压器垫片": "P13 Turbo Gasket", "中间齿轮轴挡板": "Idler Gear Shaft Baffle",
"EVB支撑臂总成": "EVB Support Arm Assembly", "L10喷油器回油管总成": "L10 Injector Return Pipe Assembly",
"P7排气管垫": "P7 Exhaust Pipe Gasket", "P7增压器垫片": "P7 Turbo Gasket",
"P13增压器回油管总成": "P13 Turbo Oil Return Pipe Assembly", "P6机油尺总成": "P6 Oil Dipstick Assembly",
"P13机油冷却器盖": "P13 Oil Cooler Cover", "低压过滤器滤芯": "Low Pressure Filter Element",
"P13空压机水管总成": "P13 Air Compressor Water Pipe Assembly",
"P13空压机进气管": "P13 Air Compressor Intake Pipe",
"P13空压机回水管": "P13 Air Compressor Return Water Pipe",
"P13空压机回水管总成": "P13 Air Compressor Return Water Pipe Assembly",
"P13管接头组件": "P13 Pipe Joint Assembly", "P10H空压机回水管": "P10H Air Compressor Return Water Pipe",
"拉铆钉": "Blind Rivet", "软管接头": "Hose Joint", "橡胶块": "Rubber Block",
"暖风发动机出水管": "Heater Engine Water Outlet Pipe",
"H10.5机油尺套管总成": "H10.5 Dipstick Sleeve Assembly", "国六节温器芯": "China-VI Thermostat Element",
"H10水泵总成": "H10 Water Pump Assembly", "复合垫片": "Composite Washer",
"P13高压油管": "P13 High Pressure Pipe", "P13高压油管（泵-轨）": "P13 High Pressure Pipe (Pump-Rail)",
}
