# -*- coding: utf-8 -*-
"""批次6 英文名词典 chunk3（第 901-1350 个漏网名称）"""
D3 = {
"14*55传动轴螺丝": "14*55 Drive Shaft Screw", "排气过渡弯管": "Exhaust Transition Elbow",
"右支撑托架总成": "Right Support Bracket Assembly", "左支撑托架总成": "Left Support Bracket Assembly",
"WP10油泵固定螺栓包": "WP10 Oil Pump Fixing Bolt Kit", "A7发电机": "A7 Alternator",
"温控开关": "Thermostatic Switch", "电磁硅油离合器": "Electromagnetic Viscous Clutch",
"双联轴承": "Double-Row Bearing", "空压机盖体": "Air Compressor Cover Body",
"空压机活塞肖卡簧": "Air Compressor Piston Pin Circlip", "固定起动机螺栓": "Starter Fixing Bolt",
"六角头螺丝": "Hex Head Screw", "F3000前大灯总成": "F3000 Headlight Assembly",
"EGR总成支架": "EGR Assembly Bracket", "P10油底壳": "P10 Oil Pan", "汽缸体": "Cylinder Block",
"副螺栓丝堵": "Auxiliary Bolt Plug", "发动机进气管": "Engine Intake Pipe",
"隔热板": "Heat Insulation Plate", "M14密封垫圈": "M14 Seal Washer", "P12凸轮轴": "P12 Camshaft",
"P12排气门": "P12 Exhaust Valve", "P12凸轮轴衬套": "P12 Camshaft Bushing",
"进油管螺丝": "Oil Inlet Pipe Screw", "ECU总成": "ECU Assembly",
"P12空压机进水管（带螺母）": "P12 Air Compressor Water Inlet Pipe (with Nut)",
"p12喷油器总成": "P12 Injector Assembly", "EGR出水管总成": "EGR Water Outlet Pipe Assembly",
"波浪轴挡圈": "Wave Shaft Retaining Ring", "波浪轴卡簧": "Wave Shaft Circlip",
"发动机隔热罩": "Engine Heat Shield", "P12润滑油管": "P12 Lube Oil Pipe", "P12机油管": "P12 Oil Pipe",
"WEVB气门桥(2231)": "WEVB Valve Bridge (2231)", "D12缸盖组装明细": "D12 Cylinder Head Assembly List",
"双级机油泵": "Two-Stage Oil Pump", "排气制动": "Exhaust Brake", "电子节气门": "Electronic Throttle",
"出水管": "Water Outlet Pipe", "后驱力飞轮螺丝": "Rear Drive Flywheel Screw",
"WP12缸盖螺栓": "WP12 Cylinder Head Bolt", "水寒宝": "Fuel Water Separator", "联轴器": "Coupling",
"大圆连接片": "Large Round Connecting Plate", "小圆连接片": "Small Round Connecting Plate",
"WP10空心螺栓包": "WP10 Hollow Bolt Kit", "P12汽缸垫": "P12 Cylinder Head Gasket",
"P10高压油泵": "P10 High Pressure Pump", "P12曲轴后油封": "P12 Crankshaft Rear Oil Seal",
"P12曲轴前油封": "P12 Crankshaft Front Oil Seal", "高压线": "High Voltage Wire",
"橡胶软管（耐低温）": "Rubber Hose (Low Temperature Resistant)", "68B活塞": "68B Piston",
"P12曲轴止推片": "P12 Crankshaft Thrust Washer", "P12气门导管": "P12 Valve Guide",
"P12支撑摇臂座": "P12 Support Rocker Seat", "P12摇臂轴总成（2231）": "P12 Rocker Arm Shaft Assembly (2231)",
"P12连杆瓦": "P12 Connecting Rod Bearing", "加机油管法兰": "Oil Fill Pipe Flange",
"P12活塞销卡簧": "P12 Piston Pin Circlip", "1075多挈带": "1075 Poly-V Belt",
"三、四排气管": "No.3-4 Exhaust Pipe", "三、四缸排气管": "No.3-4 Cylinder Exhaust Pipe",
"P12排气管螺丝": "P12 Exhaust Pipe Screw", "船用节温器总成": "Marine Thermostat Assembly",
"原厂排气管密封环": "OEM Exhaust Pipe Seal Ring", "自动张紧轮110010": "Auto Tensioner 110010",
"自动张紧轮110012": "Auto Tensioner 110012", "惰轮120049": "Idler Pulley 120049",
"3305轴承": "3305 Bearing", "NU2207轴承": "NU2207 Bearing", "桥壳双头螺栓": "Axle Housing Stud",
"67水泵总成": "67 Water Pump Assembly", "68A活塞": "68A Piston",
"P12缸盖副螺栓": "P12 Cylinder Head Auxiliary Bolt", "ECU线束": "ECU Wiring Harness",
"618油气分离器": "618 Oil-Gas Separator", "P12飞轮螺丝": "P12 Flywheel Screw",
"连接弯管密封圈": "Connecting Elbow Seal Ring", "EGR输油泵": "EGR Fuel Feed Pump",
"欧II曲轴前油封": "Euro-II Crankshaft Front Oil Seal", "高压油泵": "High Pressure Pump",
"P12EVB支架螺栓": "P12 EVB Bracket Bolt", "P12摇臂轴螺丝": "P12 Rocker Arm Shaft Screw",
"EVB调整螺钉": "EVB Adjusting Screw", "EVB调整螺钉螺母": "EVB Adjusting Screw Nut",
"缸盖主螺丝": "Cylinder Head Main Screw", "WP10排气管增压器螺栓包": "WP10 Exhaust-Turbo Bolt Kit",
"差速器壳（0166）": "Differential Housing (0166)", "连杆总成L": "Connecting Rod Assembly L",
"P12气门挺柱": "P12 Valve Tappet", "齿圈支架螺母": "Ring Gear Bracket Nut",
"连体轮边油封": "Integral Wheel End Oil Seal", "主动齿轮总成": "Drive Gear Assembly",
"轮边行星齿轮轴": "Wheel Planetary Gear Shaft", "P12机油冷却器盖": "P12 Oil Cooler Cover",
"60*4密封圈": "60*4 Seal Ring", "联管螺母": "Union Nut", "左支架总成": "Left Bracket Assembly",
"右支架总成": "Right Bracket Assembly",
"615标准连杆螺栓（不三包）": "615 Standard Connecting Rod Bolt (No Warranty)",
"副厂排气管密封环": "Aftermarket Exhaust Pipe Seal Ring", "P12气门油封": "P12 Valve Stem Seal",
"P12皮带轮螺栓": "P12 Pulley Bolt", "EVB排气门摇臂": "EVB Exhaust Valve Rocker Arm",
"615加粗连杆螺栓（不三包)": "615 Heavy-Duty Connecting Rod Bolt (No Warranty)",
"后取力器油封(原厂)": "Rear PTO Oil Seal (OEM)", "圆柱滚子轴承NJ208": "Cylindrical Roller Bearing NJ208",
"隔圈（搅拌车）": "Spacer Ring (Mixer Truck)", "环状弹簧外圈": "Ring Spring Outer Ring",
"环状弹簧内圈": "Ring Spring Inner Ring", "P12排气制动螺栓": "P12 Exhaust Brake Bolt",
"发动机后吊板": "Engine Rear Lifting Plate", "发动机前吊板": "Engine Front Lifting Plate",
"EVB摇臂座螺栓": "EVB Rocker Seat Bolt", "8.8级六角头螺栓Q150B10100": "Hex Head Bolt Gr.8.8 Q150B10100",
"内六角螺钉Q218B0835TF2": "Socket Screw Q218B0835TF2", "内六角螺钉": "Socket Screw",
"预热器": "Preheater", "D12缸盖罩衬垫": "D12 Cylinder Head Cover Gasket",
"S进油管总成": "S Oil Inlet Pipe Assembly", "0047四配套": "0047 Four-Piece Kit",
"φ18柴滤座": "φ18 Diesel Filter Seat", "P12集滤器": "P12 Oil Strainer",
"034四配套": "034 Four-Piece Kit", "10*65六角头螺栓": "10*65 Hex Head Bolt",
"D12空压机螺母": "D12 Air Compressor Nut", "010四配套": "010 Four-Piece Kit", "护风罩": "Fan Shroud",
"618加粗连杆螺栓(PJA002）": "618 Heavy-Duty Connecting Rod Bolt (PJA002)",
"加宽曲轴止推片": "Wide Crankshaft Thrust Washer", "047空压机缸盖": "047 Air Compressor Cylinder Head",
"吊环接块": "Lifting Eye Joint Block", "机滤器总成": "Oil Filter Assembly",
"φ10球面垫圈": "φ10 Spherical Washer", "618连杆总成": "618 Connecting Rod Assembly",
"618发动机密封圈修理包": "618 Engine Seal Repair Kit",
"168空压机缸盖总成": "168 Air Compressor Cylinder Head Assembly",
"168空压机缸体": "168 Air Compressor Cylinder Block", "168空压机活塞": "168 Air Compressor Piston",
"168空压机修理包": "168 Air Compressor Repair Kit", "11叶风扇叶": "11-Blade Fan Blade",
"发动机拉紧块": "Engine Tensioning Block", "0042油滤支架": "0042 Oil Filter Bracket",
"高压油泵润滑油管": "High Pressure Pump Lube Oil Pipe", "发动机密封圈": "Engine Seal Ring",
"后轴承盖": "Rear Bearing Cover", "前轴承盖": "Front Bearing Cover", "定位销": "Locating Pin",
"定位套": "Locating Sleeve", "隔环": "Spacer Ring", "支撑环": "Support Ring",
"前轴承盖衬垫": "Front Bearing Cover Gasket", "后轴承盖衬垫": "Rear Bearing Cover Gasket",
"WP10空压机螺丝包": "WP10 Air Compressor Screw Kit", "空压机压紧块": "Air Compressor Pressing Block",
"水温表": "Water Temperature Gauge", "Q1860法兰面六角头螺栓": "Q1860 Hex Flange Bolt",
"摇臂轴支架": "Rocker Arm Shaft Bracket", "WEVB进油管总成": "WEVB Oil Inlet Pipe Assembly",
"风扇连接圈": "Fan Connecting Ring", "P12增压器垫片（方）": "P12 Turbo Gasket (Square)",
"D12缸盖主螺栓": "D12 Cylinder Head Main Bolt", "进气门弹簧": "Intake Valve Spring",
"排气门弹簧": "Exhaust Valve Spring", "17水堵": "17 Water Core Plug",
"15.3*2.4密封圈": "15.3*2.4 Seal Ring", "输出轴": "Output Shaft",
"装机进气门座": "Assembly Intake Valve Seat", "装机排气门座": "Assembly Exhaust Valve Seat",
"D12缸盖副螺栓": "D12 Cylinder Head Auxiliary Bolt", "集滤器压板": "Oil Strainer Press Plate",
"包装箱": "Packing Box", "空压机回水管（新式）": "Air Compressor Return Water Pipe (New Type)",
"联接螺栓": "Connecting Bolt", "异型接头": "Special-Shaped Joint", "压套": "Press Sleeve",
"暖风过渡接头": "Heater Adapter Joint", "35*3密封圈": "35*3 Seal Ring",
"波形弹性垫圈": "Wave Elastic Washer", "弹性波形垫圈": "Elastic Wave Washer",
"电磁离合器线束": "Electromagnetic Clutch Wiring Harness", "10*110六角头螺栓": "10*110 Hex Head Bolt",
"WP10EGR发动机密封圈修理包": "WP10 EGR Engine Seal Repair Kit",
"WP10电喷发动机密封圈修理包": "WP10 EFI Engine Seal Repair Kit",
"P12管接头组件": "P12 Pipe Joint Assembly", "进油管接头": "Oil Inlet Pipe Joint",
"EGR挡板": "EGR Baffle Plate", "机油散热器": "Oil Radiator", "机油冷却器": "Oil Cooler",
"过度接头": "Adapter Joint", "惰轮螺栓": "Idler Pulley Bolt", "排气接头": "Exhaust Joint",
"P12缸盖罩": "P12 Cylinder Head Cover", "机滤器": "Oil Filter", "28*3密封圈": "28*3 Seal Ring",
"转向巨力泵": "Heavy-Duty Steering Pump", "226B气门推杆": "226B Valve Push Rod",
"783多锲带（三元乙丙）": "783 Poly-V Belt (EPDM)", "φ12复合垫片": "φ12 Composite Washer",
"φ14复合垫片": "φ14 Composite Washer", "φ16复合垫片": "φ16 Composite Washer",
"φ6复合垫片": "φ6 Composite Washer", "φ8复合垫片": "φ8 Composite Washer",
"φ30复合垫片": "φ30 Composite Washer", "后驱力螺栓": "Rear Drive Bolt",
"D12气门摇臂总成": "D12 Valve Rocker Arm Assembly", "D12摇臂轴": "D12 Rocker Arm Shaft",
"自锁垫片": "Self-Locking Washer", "M8法兰面螺母": "M8 Flange Nut",
"D12空压机出水管接头": "D12 Air Compressor Water Outlet Joint", "出水管法兰": "Water Outlet Flange",
"后取力飞轮壳螺栓": "Rear PTO Flywheel Housing Bolt", "摇臂支架": "Rocker Arm Bracket",
"缸盖罩（带加机油口）": "Cylinder Head Cover (with Oil Filler)", "弯管": "Elbow Pipe",
"618汽缸体": "618 Cylinder Block", "热交换器水管接座": "Heat Exchanger Water Pipe Seat",
"燃气接头": "Gas Joint", "客车机滤器垫片": "Coach Oil Filter Gasket", "M10弹垫": "M10 Spring Washer",
"M10平垫": "M10 Flat Washer", "原厂气门弹簧上座": "OEM Valve Spring Upper Seat",
"原厂气门弹簧下座": "OEM Valve Spring Lower Seat", "管接螺母": "Pipe Joint Nut",
"P12连杆衬套": "P12 Connecting Rod Bushing", "M8弹簧垫": "M8 Spring Washer",
"M12弹性垫圈": "M12 Elastic Washer", "回水接头": "Water Return Joint",
"小底盘气门油封": "Small Chassis Valve Stem Seal", "P10机滤座垫片": "P10 Oil Filter Seat Gasket",
"615空压机阀板总成": "615 Air Compressor Valve Plate Assembly",
"618空压机阀板总成": "618 Air Compressor Valve Plate Assembly",
"纯铜空心螺栓": "Pure Copper Hollow Bolt", "油门卡簧": "Throttle Circlip",
"加重排气管": "Heavy-Duty Exhaust Pipe", "后取力输出轴组件": "Rear PTO Output Shaft Module",
"P13密封圈": "P13 Seal Ring", "机滤座总成": "Oil Filter Seat Assembly",
"P12密封圈修理包": "P12 Seal Ring Repair Kit", "堵头": "Plug Head",
"暖风回水管接头": "Heater Water Return Joint",
"空压机水管接头(弯）": "Air Compressor Water Pipe Joint (Bent)", "前端盖": "Front Cover",
"D10喷油器密封圈": "D10 Injector Seal Ring", "D10吊环接块": "D10 Lifting Eye Joint Block",
"环形风扇叶": "Ring Fan Blade", "暖风接头（丝24）": "Heater Joint (Thread 24)",
"p12机油滤芯": "P12 Oil Filter Element", "M10弹簧垫": "M10 Spring Washer",
"D12排气管密封环": "D12 Exhaust Pipe Seal Ring", "EVB压板": "EVB Press Plate",
"EVB调节螺钉": "EVB Adjusting Screw", "EVB调节螺母": "EVB Adjusting Nut",
"内六角头螺栓": "Socket Head Bolt", "P12夹紧块": "P12 Clamping Block",
"电控硅油风扇离合器": "Electronically Controlled Viscous Fan Clutch",
"D12曲轴后齿轮": "D12 Crankshaft Rear Gear", "0311柴滤座": "0311 Diesel Filter Seat",
"发动机固定支腿": "Engine Fixing Leg", "镀铜10*90螺栓": "Copper-Plated 10*90 Bolt",
"暖风接口": "Heater Port", "热交换器回水管": "Heat Exchanger Water Return Pipe",
"热交换器出水管": "Heat Exchanger Water Outlet Pipe",
"热交换器到节温器水管": "Heat Exchanger-to-Thermostat Water Pipe",
"热交换器取水管": "Heat Exchanger Water Draw Pipe", "回水管": "Water Return Pipe",
"226B罩盖垫": "226B Cover Gasket", "226B连杆螺栓": "226B Connecting Rod Bolt",
"排气弯管": "Exhaust Elbow Pipe", "变径螺栓": "Step Bolt",
"12*35法兰面六角头螺栓": "12*35 Hex Flange Bolt", "36D排气管": "36D Exhaust Pipe",
"奥威排气管": "Aowei Exhaust Pipe", "P12凸轮轴止推片": "P12 Camshaft Thrust Washer",
"WEVB摇臂总成": "WEVB Rocker Arm Assembly", "V推螺栓": "V-Push Bolt",
"WEVB摇臂座": "WEVB Rocker Seat", "D12进气管垫": "D12 Intake Pipe Gasket",
"连杆总成J": "Connecting Rod Assembly J", "风扇连驱动轴": "Fan with Drive Shaft",
"WP12圆柱销修理包": "WP12 Dowel Pin Repair Kit", "传动轴盖板": "Drive Shaft Cover Plate",
"(天然气)排气门": "(Natural Gas) Exhaust Valve", "P7气门挺住": "P7 Valve Tappet",
"重汽中缸螺丝": "Sinotruk Mid-Cylinder Screw", "机油喷嘴铜垫": "Oil Nozzle Copper Washer",
"重汽中间轴螺栓": "Sinotruk Intermediate Shaft Bolt", "重汽机油冷却器盖螺栓": "Sinotruk Oil Cooler Cover Bolt",
"重汽空压机螺丝": "Sinotruk Air Compressor Screw", "重汽EGR高压油泵螺栓": "Sinotruk EGR HP Pump Bolt",
"重汽EGR出水管螺栓": "Sinotruk EGR Water Outlet Bolt", "EGR冷却器螺栓": "EGR Cooler Bolt",
"重汽排气管增压器螺栓": "Sinotruk Exhaust-Turbo Bolt", "P7气门推杆": "P7 Valve Push Rod",
"解放涨紧轮": "FAW Jiefang Tensioner", "P12多层排气管垫": "P12 Multi-Layer Exhaust Gasket",
"10槽惰轮": "10-Groove Idler Pulley", "618出气管接头": "618 Air Outlet Joint",
"WP7曲轴后油封": "WP7 Crankshaft Rear Oil Seal", "差速器总成": "Differential Assembly",
"空调压缩机支架": "AC Compressor Bracket", "尿素箱回水管接头": "Urea Tank Water Return Joint",
"取水接头": "Water Draw Joint", "出水接头": "Water Outlet Joint", "空气管接头": "Air Pipe Joint",
"375高压油泵": "375 High Pressure Pump", "输出齿轮后轴承": "Output Gear Rear Bearing",
"输出齿轮前轴承": "Output Gear Front Bearing", "高压油泵溢流阀": "High Pressure Pump Overflow Valve",
"618水泵体垫片": "618 Water Pump Body Gasket", "加机油短管总成": "Oil Fill Short Pipe Assembly",
"D12曲轴前油封": "D12 Crankshaft Front Oil Seal", "10E摇臂总成": "10E Rocker Arm Assembly",
"P12凸轮轴齿轮": "P12 Camshaft Gear", "进气法兰面六角头管螺栓": "Intake Hex Flange Pipe Bolt",
"后取力油封": "Rear PTO Oil Seal", "09款金王子涨紧轮支架": "09 Golden Prince Tensioner Bracket",
"调节螺钉": "Adjusting Screw", "潍柴中缸螺丝": "Weichai Mid-Cylinder Screw",
"潍柴欧2全机螺栓": "Weichai Euro-2 Complete Engine Bolt Kit",
"空压机盖涨紧轮固定螺栓": "Air Compressor Cover Tensioner Fixing Bolt",
"国四缸盖罩衬垫": "China-IV Cylinder Head Cover Gasket", "燃气管": "Gas Pipe",
"20水堵": "20 Water Core Plug", "10PK皮带轮": "10PK Pulley", "喷射阀": "Injection Valve",
"161涨紧轮固定螺栓": "161 Tensioner Fixing Bolt", "10PK自动涨紧轮": "10PK Auto Tensioner",
"618全车垫": "618 Complete Gasket Kit", "FP9喷油泵托架": "FP9 Injection Pump Bracket",
"618四配套": "618 Four-Piece Kit", "14PK*1134多挈带": "14PK*1134 Poly-V Belt",
"全钢排气管垫": "All-Steel Exhaust Gasket", "618水泵销子": "618 Water Pump Pin",
"天然气缸盖罩密封圈": "Natural Gas Cylinder Head Cover Seal Ring",
"10*60双头螺栓": "10*60 Stud Bolt", "P12曲轴齿轮": "P12 Crankshaft Gear",
"P12摇臂结合组": "P12 Rocker Arm Combination", "EVB调节螺栓固定支架": "EVB Adjusting Bolt Fixing Bracket",
"心组件四配套": "Core Module Four-Piece Kit", "双管管夹": "Double Pipe Clamp",
"圆柱销(Q5210820)": "Dowel Pin (Q5210820)", "中间齿轮轴（E056）": "Idler Gear Shaft (E056)",
"自动张紧轮110052": "Auto Tensioner 110052", "D12气缸盖": "D12 Cylinder Head",
"P12连杆瓦+0.03": "P12 Connecting Rod Bearing +0.03", "22*3密封圈": "22*3 Seal Ring",
"EVB支架总成": "EVB Bracket Assembly", "EVB气门桥": "EVB Valve Bridge",
"P12惰轮轴挡板": "P12 Idler Shaft Baffle", "D12排气管垫": "D12 Exhaust Gasket",
"前支撑板": "Front Support Plate", "惰轮支架": "Idler Pulley Bracket",
"自动张紧轮（110112）": "Auto Tensioner (110112)", "D12空压机齿轮": "D12 Air Compressor Gear",
"D12曲轴前齿轮": "D12 Crankshaft Front Gear", "M24*1.5六角薄螺母": "M24*1.5 Hex Thin Nut",
"内六角圆头螺栓": "Socket Round Head Bolt", "226B活塞销卡簧": "226B Piston Pin Circlip",
"WEVB缸盖螺栓包": "WEVB Cylinder Head Bolt Kit",
"欧II/P10/618油底壳机油泵螺丝包": "Euro-II/P10/618 Oil Pan Pump Screw Kit",
"WP10/618端盖齿轮室螺丝包": "WP10/618 Gear Housing Screw Kit",
"重汽油底壳机油泵螺栓": "Sinotruk Oil Pan Pump Bolt", "重汽空心螺栓包": "Sinotruk Hollow Bolt Kit",
"欧II柴滤支架螺栓": "Euro-II Diesel Filter Bracket Bolt", "615安全阀": "615 Safety Valve",
"欧II缸盖螺栓": "Euro-II Cylinder Head Bolt",
"重汽欧II出水管节温器固定螺栓": "Sinotruk Euro-II Thermostat Fixing Bolt",
"欧II进气管固定螺栓": "Euro-II Intake Pipe Fixing Bolt", "D12喷油泵法兰": "D12 Injection Pump Flange",
"原厂排气门": "OEM Exhaust Valve", "国四空压机进气管": "China-IV Air Compressor Intake Pipe",
"齿形带": "Timing Toothed Belt", "618中缸螺丝": "618 Mid-Cylinder Screw",
"618水泵风扇托架螺栓": "618 Water Pump Fan Bracket Bolt", "618涨紧轮螺丝": "618 Tensioner Screw",
"618进气管螺丝": "618 Intake Pipe Screw", "618机油冷却器盖螺丝": "618 Oil Cooler Cover Screw",
"618出水管螺栓": "618 Water Outlet Bolt", "618发电机支架螺丝": "618 Alternator Bracket Screw",
"重汽欧II油泵固定螺栓": "Sinotruk Euro-II Oil Pump Fixing Bolt",
"P13连杆螺栓（14*1.25）": "P13 Connecting Rod Bolt (14*1.25)",
"后驱力泵总成": "Rear Drive Pump Assembly", "10*85六角头": "10*85 Hex Head",
"P7加机油口盖": "P7 Oil Fill Cap", "中间接头": "Intermediate Joint",
"摇臂座组件": "Rocker Seat Module", "左油底壳托块": "Left Oil Pan Support Block",
"右油底壳托块": "Right Oil Pan Support Block", "WP12中缸螺栓": "WP12 Mid-Cylinder Bolt",
"（工程机械）曲轴法兰": "(Construction Machinery) Crankshaft Flange",
"工程机械曲轴法兰": "Construction Machinery Crankshaft Flange",
"天然气气门油封": "Natural Gas Valve Stem Seal",
"工程机械增压器回油管": "Construction Machinery Turbo Oil Return Pipe",
"排气尾管总成": "Exhaust Tail Pipe Assembly", "10*70内六角": "10*70 Socket Screw",
"8*60六角头螺栓": "8*60 Hex Head Bolt", "10*40双头螺栓": "10*40 Stud Bolt",
"10升天然气活塞环": "10L Natural Gas Piston Ring", "废气放气控制阀": "Exhaust Waste Gate Control Valve",
"WEVB气门桥（1751）": "WEVB Valve Bridge (1751)", "工程机械接管": "Construction Machinery Connecting Pipe",
"客车水泵总成": "Coach Water Pump Assembly", "P12后驱力润滑油管": "P12 Rear Drive Lube Oil Pipe",
"出水管接头": "Water Outlet Joint", "三通阀": "Three-Way Valve",
"惰齿轮支架": "Idler Gear Bracket", "工程机械进气接管": "Construction Machinery Intake Connection",
"P7阻水圈": "P7 Water Seal Ring", "P7阻水圈（113*3.05）": "P7 Water Seal Ring (113*3.05)",
"空压机进水管接头（带螺母）": "Air Compressor Water Inlet Joint (with Nut)",
"618气缸套": "618 Cylinder Liner", "缸台加0.10气缸套": "Oversized +0.10 Cylinder Liner",
"方形錐螺塞Q614B06": "Square Taper Plug Q614B06", "平槽惰轮120022": "Flat Groove Idler Pulley 120022",
"客车出水管": "Coach Water Outlet Pipe", "D12油泵机油进油管": "D12 Oil Pump Oil Inlet Pipe",
"D12机油喷嘴": "D12 Oil Nozzle", "P12连接板": "P12 Connecting Plate",
"EGR进气管垫片": "EGR Intake Pipe Gasket", "WP7机油尺总成": "WP7 Oil Dipstick Assembly",
"WP7机油尺": "WP7 Oil Dipstick", "WP6机油尺": "WP6 Oil Dipstick",
"膨胀管结合子组排气管": "Expansion Pipe Combination Exhaust Pipe",
"消声器支架": "Muffler Bracket", "P13排气管垫": "P13 Exhaust Gasket",
"10*40内六角螺丝": "10*40 Socket Screw", "工程机械燃油管": "Construction Machinery Fuel Pipe",
"潍柴615空压机螺栓": "Weichai 615 Air Compressor Bolt", "潍柴615空心螺栓": "Weichai 615 Hollow Bolt",
"潍柴615油泵固定螺栓": "Weichai 615 Oil Pump Fixing Bolt",
"潍柴615排气管增压器螺栓": "Weichai 615 Exhaust-Turbo Bolt",
"曼水堵（φ32）": "MAN Water Core Plug (φ32)", "曼水堵（φ25）": "MAN Water Core Plug (φ25)",
"后驱力飞轮壳": "Rear Drive Flywheel Housing", "六角螺母（天力)": "Hex Nut (Tianli)",
"WP12中间齿轮轴止推片": "WP12 Idler Gear Shaft Thrust Washer",
"WP7连杆螺栓": "WP7 Connecting Rod Bolt", "10*90带齿法兰面螺栓": "10*90 Toothed Flange Bolt",
"机滤器托架": "Oil Filter Bracket", "WP7油底壳垫": "WP7 Oil Pan Gasket",
"后取力油封(普通)": "Rear PTO Oil Seal (Standard)", "连接板": "Connecting Plate",
"H10/节温器支撑块": "H10/Thermostat Support Block",
"后驱力增压器进油管（后）": "Rear Drive Turbo Oil Feed Pipe (Rear)",
"吸油管法兰": "Oil Suction Pipe Flange", "隔热罩下垫圈": "Heat Shield Lower Washer",
"P7缸盖主螺栓（全长185）": "P7 Cylinder Head Main Bolt (185mm)",
}
