# -*- coding: utf-8 -*-
"""批次6 英文名词典 chunk2（第 451-900 个漏网名称）"""
D2 = {
"P13空压机进气接头": "P13 Air Compressor Intake Joint", "P13油底壳托快": "P13 Oil Pan Support Block",
"国六EGR出气管总成": "China-VI EGR Outlet Pipe Assembly", "风扇离合器总成": "Fan Clutch Assembly",
"卡套式端直通接头体": "Ferrule Type Straight Connector Body", "P13机油尺总成": "P13 Oil Dipstick Assembly",
"P13气路连接胶管": "P13 Air Line Rubber Hose", "H10燃油进油管总成": "H10 Fuel Feed Pipe Assembly",
"燃油滤清器盖": "Fuel Filter Cover", "D12油泵辅助支架": "D12 Oil Pump Auxiliary Bracket",
"P7点火线圈衬套": "P7 Ignition Coil Bushing", "EGR冷却器出水管总成": "EGR Cooler Water Outlet Pipe Assembly",
"M14复合垫片": "M14 Composite Washer", "EGR冷却器水管": "EGR Cooler Water Pipe",
"P8后排气管卡箍": "P8 Rear Exhaust Pipe Clamp", "后取力总成": "Rear PTO Assembly",
"P13增压器后排气管卡箍": "P13 Turbo Rear Exhaust Pipe Clamp",
"P8模块密封圈修理包": "P8 Module Seal Ring Repair Kit", "厚垫片": "Thick Washer",
"226B冷却液连接胶管": "226B Coolant Rubber Hose", "P13油气分离器出气管": "P13 Oil-Gas Separator Outlet Pipe",
"相位传感器": "Phase Sensor", "H10水管接头": "H10 Water Pipe Joint",
"P13EGR固定支架": "P13 EGR Fixing Bracket", "全铜水堵": "All-Copper Water Core Plug",
"空压机齿轮盖垫片": "Air Compressor Gear Cover Gasket", "喷嘴组件": "Nozzle Assembly",
"安全阀螺塞": "Safety Valve Plug", "冷却器盖防水罗塞": "Cooler Cover Water Plug",
"前油封垫片": "Front Oil Seal Gasket", "加油短管垫片": "Oil Fill Short Pipe Gasket",
"油尺管头": "Dipstick Tube Head", "油尺管下组件": "Dipstick Tube Lower Assembly",
"大口油气分离器组件": "Large-Inlet Oil-Gas Separator Assembly", "硅油减振器": "Viscous Damper",
"连杆轴瓦(上瓦)": "Connecting Rod Bearing (Upper)", "连杆螺栓（不三包)": "Connecting Rod Bolt (No Warranty)",
"吊环夹紧块": "Lifting Eye Clamping Block", "615气缸盖主螺栓": "615 Cylinder Head Main Bolt",
"吊环螺钉": "Lifting Eye Screw", "驱动销": "Drive Pin",
"进气门弹簧下座": "Intake Valve Spring Lower Seat", "0058轴": "0058 Shaft",
"三角盖板": "Triangle Cover Plate", "张紧轮支撑板": "Tensioner Support Plate", "风扇": "Fan",
"铁风圈支架": "Iron Fan Shroud Bracket", "带凸齿的孔用挡圈": "Toothed Circlip for Hole",
"安全阀": "Safety Valve", "安全阀弹簧": "Safety Valve Spring",
"主油道限压阀": "Main Oil Gallery Relief Valve", "联轴器法兰组件": "Coupling Flange Assembly",
"波许喷油泵托架": "Bosch Injection Pump Bracket", "润滑油回油管总成": "Lube Oil Return Pipe Assembly",
"单向阀": "Check Valve", "潍柴欧II燃油管（弯）": "Weichai Euro-II Fuel Pipe (Bent)",
"潍柴欧II燃油管(直)": "Weichai Euro-II Fuel Pipe (Straight)",
"连接片螺丝(带衬套）": "Connecting Plate Screw (with Bushing)", "角度调整板": "Angle Adjustment Plate",
"火焰预热电磁阀": "Flame Preheating Solenoid Valve", "火焰预热电热塞": "Flame Preheating Glow Plug",
"进油管法兰": "Oil Inlet Pipe Flange", "压气机进气管组件": "Compressor Intake Pipe Module",
"615进气管垫片": "615 Intake Pipe Gasket", "气泵齿轮支承环": "Air Pump Gear Support Ring",
"气泵轴承（2207）": "Air Pump Bearing (2207)", "气泵轴承（7207B）": "Air Pump Bearing (7207B)",
"传动轴挡板": "Drive Shaft Baffle", "气泵轴螺母（头）": "Air Pump Shaft Nut (Front)",
"空压机齿轮(小）": "Air Compressor Gear (Small)", "空压机传动轴螺母（中）": "Air Compressor Drive Shaft Nut (Middle)",
"空压机油封座": "Air Compressor Oil Seal Seat", "挡油盘": "Oil Baffle Plate",
"机油冷却器垫": "Oil Cooler Gasket", "618标准连杆螺丝（不三包）": "618 Standard Connecting Rod Bolt (No Warranty)",
"进气门外弹簧": "Intake Valve Outer Spring", "0161涨紧轮总成": "0161 Tensioner Assembly",
"张紧板": "Tensioning Plate", "机油冷却器总成": "Oil Cooler Assembly", "油嘴": "Oil Nozzle",
"618柴油滤芯托架": "618 Diesel Filter Element Bracket", "618空压机密封圈": "618 Air Compressor Seal Ring",
"转向泵垫片": "Steering Pump Gasket", "气泵齿轮（小）": "Air Pump Gear (Small)",
"重汽四气门摇臂总成": "Sinotruk 4-Valve Rocker Arm Assembly", "MC曼机油": "MC MAN Engine Oil",
"桥壳磁性螺塞": "Axle Housing Magnetic Plug", "传动轴螺母": "Drive Shaft Nut",
"老四气门摇臂总成": "Old 4-Valve Rocker Arm Assembly", "传动轴罗丝": "Drive Shaft Screw",
"加机油管固定螺栓": "Oil Fill Pipe Fixing Bolt", "油门踏板": "Throttle Pedal",
"油门杠杆衬套": "Throttle Lever Bushing", "悬臂总成": "Cantilever Assembly", "油门弹簧": "Throttle Spring",
"销轴": "Hinge Pin", "停油缸螺杆": "Fuel Cut-Off Cylinder Screw",
"燃油粗滤器滤芯": "Fuel Primary Filter Element", "WP12空压机螺栓": "WP12 Air Compressor Bolt",
"传动轴螺丝": "Drive Shaft Screw", "转向机回油管": "Steering Gear Return Pipe", "放水阀": "Drain Valve",
"空压机接头螺母": "Air Compressor Joint Nut", "WP12整套螺栓": "WP12 Complete Bolt Set",
"WP12进气管螺栓": "WP12 Intake Pipe Bolt", "WP12机油泵油底壳螺栓": "WP12 Oil Pump Oil Pan Bolt",
"WP12发电机螺栓": "WP12 Alternator Bolt", "P7活塞销卡簧": "P7 Piston Pin Circlip",
"WP12油泵部分螺栓": "WP12 Oil Pump Section Bolts", "重汽后驱力螺栓包": "Sinotruk Rear Drive Bolt Kit",
"WP12缸体螺栓": "WP12 Cylinder Block Bolt", "变径卡箍总成": "Step-Down Clamp Assembly",
"WP12机冷盖螺栓": "WP12 Oil Cooler Cover Bolt", "WP12前端盖螺栓": "WP12 Front Cover Bolt",
"后支撑支架": "Rear Support Bracket", "连接弯管(后取力)": "Connecting Elbow (Rear PTO)",
"中冷管(后取力)": "Intercooler Pipe (Rear PTO)", "上进油管(后取力)": "Upper Oil Inlet Pipe (Rear PTO)",
"油标尺": "Oil Dipstick", "机油加油管": "Oil Fill Pipe", "连接短管": "Connecting Short Pipe",
"中冷进气管下组件": "Intercooler Intake Pipe Lower Module", "堵盖": "Plug Cover",
"镀铜排气管螺栓": "Copper-Plated Exhaust Pipe Bolt", "中冷管": "Intercooler Pipe", "进水管": "Water Inlet Pipe",
"φ590 环形风扇": "φ590 Ring Fan", "1KW发电机": "1KW Alternator", "1.5KW 发电机": "1.5KW Alternator",
"8.8级六角头螺栓": "Hex Head Bolt Grade 8.8", "050053齿轮固定螺丝包": "050053 Gear Fixing Screw Kit",
"WP12前支架螺栓": "WP12 Front Bracket Bolt", "83B机油冷却器盖螺丝包": "83B Oil Cooler Cover Screw Kit",
"M8平垫": "M8 Flat Washer", "机滤座固定螺栓": "Oil Filter Bracket Fixing Bolt",
"潍柴后驱力螺栓包": "Weichai Rear Drive Bolt Kit", "WP12飞轮皮带轮螺栓": "WP12 Flywheel Pulley Bolt",
"WP12水泵风扇托架螺栓": "WP12 Water Pump Fan Bracket Bolt", "WP12连接板螺栓": "WP12 Connecting Plate Bolt",
"碗行塞17×7.3": "Core Plug 17×7.3", "空压机出水管接头": "Air Compressor Water Outlet Joint",
"O型密封圈（小）": "O-Ring (Small)", "前油封座垫片": "Front Oil Seal Seat Gasket",
"带纤维夹层的橡胶软管": "Rubber Hose with Fabric Insert", "机油冷却汽器盖片": "Oil Cooler Cover Plate",
"平键": "Parallel Key", "六角头螺母": "Hex Head Nut", "连杆螺栓(不三包）": "Connecting Rod Bolt (No Warranty)",
"连杆上瓦": "Connecting Rod Upper Bearing", "连杆下瓦": "Connecting Rod Lower Bearing",
"螺旋撑簧油环": "Spiral Expander Oil Ring", "油孔堵塞": "Oil Hole Plug",
"JQB缸盖主螺栓": "JQB Cylinder Head Main Bolt", "摇臂罩下罩": "Rocker Cover Lower Shield",
"摇臂罩下罩衬垫": "Rocker Cover Lower Shield Gasket", "骨架油封": "Skeleton Oil Seal",
"摇臂罩衬垫": "Rocker Cover Gasket", "欧II全套圆柱销": "Euro-II Complete Dowel Pin Set",
"碗行环": "Core Plug Ring", "中间齿轮轴（2231)": "Idler Gear Shaft (2231)",
"中间齿轮垫片": "Idler Gear Washer", "紧固螺钉": "Fastening Screw", "640环形风扇": "640 Ring Fan",
"590环形风扇": "590 Ring Fan", "新式节温器总成80℃": "New Type Thermostat Assembly 80℃",
"自动张紧轮总成": "Auto Tensioner Assembly", "中间隔圈": "Intermediate Spacer Ring",
"机油冷却器（8片）": "Oil Cooler (8-Plate)", "双杆空压机联轴器": "Double-Rod Air Compressor Coupling",
"角度调节板": "Angle Adjusting Plate", "1": "1", "紧固螺母": "Fastening Nut", "供油泵": "Fuel Supply Pump",
"半圆键": "Woodruff Key", "共轨组件": "Common Rail Module", "φ8球面垫圈": "φ8 Spherical Washer",
"燃油滤托架": "Fuel Filter Bracket", "燃油精滤器总成": "Fuel Fine Filter Assembly",
"燃油精滤器虑座": "Fuel Fine Filter Seat", "旋装式燃油精滤器": "Spin-on Fuel Fine Filter",
"柴虑溢油阀": "Diesel Filter Overflow Valve", "旋装式燃油粗滤器虑座": "Spin-on Fuel Primary Filter Seat",
"虑杯和水位传感器总成": "Filter Bowl & Water Level Sensor Assembly",
"润滑油回油管组件": "Lube Oil Return Pipe Module", "燃油温度传感器座": "Fuel Temperature Sensor Seat",
"回油连接座": "Return Oil Connecting Seat", "共轨组件回油管": "Common Rail Module Return Pipe",
"油泵回油管": "Oil Pump Return Pipe", "支撑架（一）": "Support Bracket (1)", "支撑架（二）": "Support Bracket (2)",
"支撑架（三）": "Support Bracket (3)", "支撑架（四）": "Support Bracket (4)",
"1540W交流发电机": "1540W Alternator", "减速型起动机": "Gear-Reduction Starter",
"电子式机油压力传感器": "Electronic Oil Pressure Sensor",
"机电式机油压力传感器": "Electromechanical Oil Pressure Sensor", "柴油温度传感器": "Diesel Temperature Sensor",
"前排气歧管": "Front Exhaust Manifold", "回油管法兰": "Return Pipe Flange", "共轨支架": "Common Rail Bracket",
"中冷管总成": "Intercooler Pipe Assembly", "中冷管支撑板": "Intercooler Pipe Support Plate",
"卡箍带（长）": "Clamp Band (Long)", "气泵轴垫片": "Air Pump Shaft Washer",
"空压机传动轴螺母": "Air Compressor Drive Shaft Nut", "磁性螺塞总成": "Magnetic Plug Assembly",
"三角盖板螺栓": "Triangle Cover Plate Bolt", "80041柴滤支架螺栓": "80041 Diesel Filter Bracket Bolt",
"WP10缸盖出水管螺栓": "WP10 Cylinder Head Water Outlet Bolt",
"双缸空压机出气接头": "Two-Cylinder Air Compressor Air Outlet Joint",
"618/P10安全阀": "618/P10 Safety Valve", "主油道后螺塞": "Main Oil Gallery Rear Plug",
"观察孔盖": "Inspection Hole Cover", "机油标尺橡胶软管": "Oil Dipstick Rubber Hose",
"大垫圈": "Large Washer", "FEF罩盖垫": "FEF Cover Gasket", "吊板": "Lifting Plate",
"欧II齿轮室固定螺栓": "Euro-II Gear Housing Fixing Bolt", "WEVB支撑臂": "WEVB Support Arm",
"圆柱滚子轴承": "Cylindrical Roller Bearing", "黄油杯座": "Grease Cup Seat", "紧定螺钉": "Set Screw",
"向心球轴承": "Deep Groove Ball Bearing", "加宽机油泵": "Wide Oil Pump", "内六角螺丝": "Hex Socket Screw",
"限压阀": "Pressure Relief Valve", "非油道限压阀弹簧座": "Non-Oil-Gallery Relief Valve Spring Seat",
"非油道限压阀弹簧": "Non-Oil-Gallery Relief Valve Spring", "三通管接头": "Three-Way Pipe Joint",
"精滤固定板": "Fine Filter Fixing Plate", "润滑油进油管组件": "Lube Oil Inlet Pipe Module",
"电控单元组件": "Electronic Control Unit Module", "粗滤器": "Primary Filter", "精滤器": "Fine Filter",
"第6缸高压油管": "No.6 Cylinder High Pressure Pipe", "第5缸高压油管": "No.5 Cylinder High Pressure Pipe",
"第4缸高压油管": "No.4 Cylinder High Pressure Pipe", "第3缸高压油管": "No.3 Cylinder High Pressure Pipe",
"第2缸高压油管": "No.2 Cylinder High Pressure Pipe", "第1缸高压油管": "No.1 Cylinder High Pressure Pipe",
"P10喷油器总成": "P10 Injector Assembly", "共轨喷油管": "Common Rail Injection Pipe",
"水温表传感器（带报警）": "Water Temperature Gauge Sensor (with Alarm)",
"压力传感器（带报警）": "Pressure Sensor (with Alarm)", "前排起歧管": "Front Exhaust Manifold",
"进油管": "Oil Inlet Pipe", "软管": "Hose", "加热器垫片": "Heater Gasket", "加热器": "Heater",
"φ38复合垫片": "φ38 Composite Washer", "蛙胶管": "Rubber Hose",
"（瑞驰）WP10齿轮室螺丝修理包": "(Ruichi) WP10 Gear Housing Screw Repair Kit",
"气管总成": "Air Pipe Assembly", "进气道总成": "Intake Port Assembly", "波纹管": "Bellows",
"托架总成": "Bracket Assembly", "发动机后支撑六角头螺栓": "Engine Rear Support Hex Bolt",
"右驱力附件": "Right Drive Unit Accessory", "轮边盖堵": "Wheel End Cover Plug",
"改装15335": "Modification 15335", "涨紧轮螺丝包": "Tensioner Screw Kit", "碗型堵塞": "Bowl-Type Core Plug",
"空压机活塞环（75）": "Air Compressor Piston Ring (75)", "M16*1.5六角螺塞": "M16*1.5 Hex Plug",
"欧II发动机密封圈修理包": "Euro-II Engine Seal Repair Kit", "滚轮总成": "Roller Assembly",
"停油缸": "Fuel Cut-Off Cylinder", "空压机（老式）": "Air Compressor (Old Type)",
"自动放水阀": "Automatic Drain Valve", "方向盘": "Steering Wheel", "金王子加机油口盖": "Golden Prince Oil Fill Cap",
"联组带": "Joined Belt", "内六角螺塞": "Socket Hex Plug", "共轨喷油泵": "Common Rail Injection Pump",
"转向机进油管": "Steering Gear Inlet Pipe", "空气软管": "Air Hose", "中驱力附件": "Middle Drive Unit Accessory",
"D12圆柱销修理包": "D12 Dowel Pin Repair Kit", "潍柴欧II发电机螺栓": "Weichai Euro-II Alternator Bolt",
"潍柴欧II空压机盖涨紧轮": "Weichai Euro-II Air Compressor Cover Tensioner", "回油短管": "Return Short Pipe",
"前油封": "Front Oil Seal", "发动机支架（左）": "Engine Mount Bracket (Left)",
"发动机支架（右）": "Engine Mount Bracket (Right)", "摇臂罩下罩总成": "Rocker Cover Lower Shield Assembly",
"EGR缸盖罩衬垫": "EGR Cylinder Head Cover Gasket", "摇臂罩上罩": "Rocker Cover Upper Shield",
"缸盖罩密封圈": "Cylinder Head Cover Seal Ring", "孔用弹性挡圈62*2": "Circlip for Hole 62*2",
"旋装式燃油精滤清器总成": "Spin-on Fuel Fine Filter Assembly", "燃油细滤器支架总成": "Fuel Fine Filter Bracket Assembly",
"润滑油管(带弯）": "Lube Oil Pipe (Bent)", "旋转式燃油粗滤器总成": "Spin-on Fuel Primary Filter Assembly",
"粗滤支架": "Primary Filter Bracket", "燃油粗滤器护套": "Fuel Primary Filter Protective Cover",
"机油冷却器(8片)": "Oil Cooler (8-Plate)", "盖片": "Cover Plate", "止推垫圈": "Thrust Washer",
"HOLSET废气涡轮增压器": "HOLSET Turbocharger", "联接弯管": "Connecting Elbow Pipe",
"EGR出水连接弯管": "EGR Water Outlet Connecting Elbow", "EGR冷却水软管": "EGR Cooling Water Hose",
"EGR单向阀总成": "EGR Check Valve Assembly", "EGR冷却器阀连接法兰": "EGR Cooler Valve Connecting Flange",
"EGR冷却器阀连接法兰垫片": "EGR Cooler Valve Flange Gasket", "EGR冷却器壳": "EGR Cooler Housing",
"EGR冷却管总成": "EGR Cooling Pipe Assembly", "EGR进气管（一）": "EGR Intake Pipe (1)",
"EGR垫片": "EGR Gasket", "EGR进气管（二）": "EGR Intake Pipe (2)",
"EGR进水管隔热罩": "EGR Water Inlet Pipe Heat Shield", "压力传感器": "Pressure Sensor",
"温度压力传感器": "Temperature & Pressure Sensor", "节气门位置传感器": "Throttle Position Sensor",
"EGR气缸": "EGR Cylinder", "783多锲带（碌丁胶）": "783 Poly-V Belt (Rubber)", "间隔板": "Spacer Plate",
"欧II曲轴后油封": "Euro-II Crankshaft Rear Oil Seal", "卡箍带（短）": "Clamp Band (Short)",
"空压机轴油封（双缸）": "Air Compressor Shaft Oil Seal (Two-Cylinder)", "615摇臂座": "615 Rocker Arm Seat",
"废气制动停油缸": "Exhaust Brake Fuel Cut-Off Cylinder", "铜垫（φ14）": "Copper Washer (φ14)",
"铜垫（φ6）": "Copper Washer (φ6)", "铜垫（φ8）": "Copper Washer (φ8)",
"铜垫（φ10）": "Copper Washer (φ10)", "铜垫（φ12）": "Copper Washer (φ12)",
"空压机齿轮（小）": "Air Compressor Gear (Small)", "驾驶室举升铁管": "Cab Lifting Steel Pipe",
"连接片衬套": "Connecting Plate Bushing", "空压机轴油封（小）": "Air Compressor Shaft Oil Seal (Small)",
"前脸": "Front Fascia", "WP12增压器排气管": "WP12 Turbo Exhaust Pipe",
"WP12飞轮壳螺栓": "WP12 Flywheel Housing Bolt", "护风帽": "Fan Shroud Cap", "气管帽": "Air Pipe Cap",
"涨紧轮支座": "Tensioner Bracket Seat", "双缸空压机阀板总成": "Two-Cylinder Air Compressor Valve Plate Assembly",
"双缸空压机缸盖": "Two-Cylinder Air Compressor Cylinder Head",
"双缸空压机缸盖垫片": "Two-Cylinder Air Compressor Cylinder Head Gasket",
"双缸空压机阀片": "Two-Cylinder Air Compressor Valve Plate", "430飞轮": "430 Flywheel",
"气罐手动放水阀": "Air Tank Manual Drain Valve", "φ16柴滤座": "φ16 Diesel Filter Seat",
"430推式离合器片": "430 Push-Type Clutch Disc", "驾驶室翻转胶垫": "Cab Tilt Rubber Pad",
"71°工程节温器总成": "71℃ Construction Machinery Thermostat Assembly", "φ640环形风扇": "φ640 Ring Fan",
"电控EGR气缸总成": "Electronic EGR Cylinder Assembly", "输油泵手泵体": "Feed Pump Hand Pump Body",
"618连杆瓦": "618 Connecting Rod Bearing", "汽缸盖（P12）": "Cylinder Head (P12)",
"水温传感器（小）": "Water Temperature Sensor (Small)", "转速传感器(EGR)": "Speed Sensor (EGR)",
"水温传感器（大）": "Water Temperature Sensor (Large)", "油门位置传感器": "Throttle Position Sensor",
"气泵轴承206": "Air Pump Bearing 206", "气泵轴承6306": "Air Pump Bearing 6306",
"一道滤芯": "First Stage Filter Element", "(80度）节温器": "Thermostat (80℃)",
"重汽发电机螺栓包": "Sinotruk Alternator Bolt Kit", "气泵铁管（电喷）": "Air Pump Steel Pipe (EFI)",
"618机油泵": "618 Oil Pump", "高压油泵法兰盘": "High Pressure Pump Flange Plate",
"WP12凸轮轴齿轮固定螺栓": "WP12 Camshaft Gear Fixing Bolt", "自动涨紧轮110017": "Auto Tensioner 110017",
"自动涨紧轮110014": "Auto Tensioner 110014", "自动涨紧轮110016": "Auto Tensioner 110016",
"自动涨紧轮110012": "Auto Tensioner 110012", "10槽平槽惰轮120004": "10-Groove Flat Idler Pulley 120004",
"6槽平槽惰轮": "6-Groove Flat Idler Pulley", "气制动总阀": "Air Brake Master Valve",
"590环形风扇叶": "590 Ring Fan Blade", "WEVB进油管接头总成": "WEVB Oil Inlet Joint Assembly",
"P12缸盖罩衬垫": "P12 Cylinder Head Cover Gasket", "P12排气垫": "P12 Exhaust Gasket",
"P12单层进气垫": "P12 Single-Layer Intake Gasket", "润滑油管（后驱力）": "Lube Oil Pipe (Rear Drive Unit)",
"柴油滤杯": "Diesel Filter Bowl", "自动涨紧轮110007": "Auto Tensioner 110007",
"φ14柴滤座": "φ14 Diesel Filter Seat", "67风扇轮毂": "67 Fan Hub", "空压机阀板": "Air Compressor Valve Plate",
"P10进气管固定螺栓包": "P10 Intake Pipe Fixing Bolt Kit", "596环型风扇叶子": "596 Ring Fan Blade",
"640环形风扇叶子": "640 Ring Fan Blade", "输油泵": "Fuel Feed Pump",
"自动涨紧轮（十槽惰轮）": "Auto Tensioner (10-Groove Idler)", "电控EGR气缸": "Electronic EGR Cylinder",
"紧固带拉紧肖": "Fastening Belt Tensioning Pin", "角齿螺丝": "Bevel Gear Screw", "组合仪表": "Combination Instrument",
"0013柴滤座": "0013 Diesel Filter Seat", "桥壳双头栓": "Axle Housing Stud", "P10飞轮": "P10 Flywheel",
"WP12缸盖组装明细": "WP12 Cylinder Head Assembly List", "后支撑托架": "Rear Support Bracket",
"钢丝机油尺": "Steel Wire Oil Dipstick", "EGR废气排气管": "EGR Exhaust Pipe",
"P12加机油口盖": "P12 Oil Fill Cap", "618护风带": "618 Fan Shroud Strip",
"P12油气分离器": "P12 Oil-Gas Separator", "继电器": "Relay", "EVB汽缸体": "EVB Cylinder Block",
"STR挡把簧": "STR Gear Lever Spring", "P10高压油泵计量单元": "P10 High Pressure Pump Metering Unit",
"左发动机后支架": "Left Engine Rear Bracket", "右发动机后支架": "Right Engine Rear Bracket",
"输出齿轮（后驱力）": "Output Gear (Rear Drive Unit)", "输出法兰固定板": "Output Flange Fixing Plate",
"中间齿轮轴盖板（后驱力）": "Idler Gear Shaft Cover Plate (Rear Drive Unit)",
"中间齿轮轴（后驱力）": "Idler Gear Shaft (Rear Drive Unit)", "P12主轴承螺栓": "P12 Main Bearing Bolt",
"OM转向助力泵": "OM Power Steering Pump", "空压机缸盖": "Air Compressor Cylinder Head",
"P12皮带轮": "P12 Pulley", "EGR电磁阀": "EGR Solenoid Valve", "EGR总成": "EGR Assembly",
"618四配套（不三包）": "618 Four-Piece Kit (No Warranty)", "618曲轴": "618 Crankshaft",
"空压机上水管": "Air Compressor Water Feed Pipe", "EGR废气管法兰垫": "EGR Waste Pipe Flange Gasket",
"EGR排气管法兰垫": "EGR Exhaust Pipe Flange Gasket", "2W发电机": "2W Alternator",
"P12活塞肖": "P12 Piston Pin", "P12活塞环": "P12 Piston Ring", "平衡轴螺丝": "Balance Shaft Screw",
"EGR发电机": "EGR Alternator", "P12进气管": "P12 Intake Pipe", "后驱力曲轴齿轮": "Rear Drive Crankshaft Gear",
"81334柴滤座": "81334 Diesel Filter Seat", "全车稳丁": "Complete Vehicle Dowel Pin",
"润滑油管（带弯）": "Lube Oil Pipe (Bent)", "WP10EGR燃油管": "WP10 EGR Fuel Pipe",
"中间齿轮分总成": "Idler Gear Sub-Assembly", "惰轮轴": "Idler Pulley Shaft", "输出法兰": "Output Flange",
"惰性齿轮（45齿）": "Idler Gear (45 Teeth)", "转向液压泵齿轮": "Steering Hydraulic Pump Gear",
"WD618飞轮壳": "WD618 Flywheel Housing", "后驱力润滑油管（96厘米）": "Rear Drive Lube Oil Pipe (96cm)",
"汽缸盖主螺栓": "Cylinder Head Main Bolt", "EGR悬臂总成": "EGR Cantilever Assembly",
"WP13飞轮螺栓": "WP13 Flywheel Bolt", "P10活塞": "P10 Piston",
"双缸空压机修理包": "Two-Cylinder Air Compressor Repair Kit", "D12活塞肖挡圈": "D12 Piston Pin Circlip",
"10PK涨紧轮": "10PK Tensioner", "轨压传感器": "Rail Pressure Sensor",
"P12油轨限压阀": "P12 Fuel Rail Pressure Relief Valve",
}
