# -*- coding: utf-8 -*-
"""批次6 英文名词典 chunk5（第 1801-2222 个漏网名称，末段）"""
D5 = {
"P7气门锁夹": "P7 Valve Lock Clamp", "D10ECU螺栓": "D10 ECU Bolt", "P7曲轴止推片": "P7 Crankshaft Thrust Washer",
"M11手油泵进油管": "M11 Hand Pump Oil Inlet Pipe", "M11/13燃油管(粗滤-输油泵)": "M11/13 Fuel Pipe (Primary Filter-Feed Pump)",
"M11/13燃油管（输油泵-滤清器）": "M11/13 Fuel Pipe (Feed Pump-Filter)",
"M11/13燃油管（滤清器-高压油泵）": "M11/13 Fuel Pipe (Filter-HP Pump)",
"M11/13回油管": "M11/13 Return Pipe", "回油管（限压阀-异径管接头）": "Return Pipe (Relief Valve-Reducer Joint)",
"MC11/13空压机冷却回水管": "MC11/13 Air Compressor Cooling Return Pipe",
"P7喷油泵机油管": "P7 Injection Pump Oil Pipe", "P13机油喷嘴（拆机）": "P13 Oil Nozzle (Dismantled)",
"MC05/07滤清器回油管": "MC05/07 Filter Return Pipe", "MC05/07油泵回油管": "MC05/07 Oil Pump Return Pipe",
"MC05/07滤清器进油管": "MC05/07 Filter Inlet Pipe", "高压连接器外套": "HV Connector Outer Sleeve",
"P13增压器放水阀": "P13 Turbo Drain Valve", "P13机油喷嘴总成": "P13 Oil Nozzle Assembly",
"P7飞轮螺栓（客车）": "P7 Flywheel Bolt (Coach)", "P6凸轮轴止推片（拆机）": "P6 Camshaft Thrust Washer (Dismantled)",
"P7凸轮轴止推片(拆机)": "P7 Camshaft Thrust Washer (Dismantled)",
"P12凸轮轴止推片（拆机）": "P12 Camshaft Thrust Washer (Dismantled)",
"P12/13空压机进气管": "P12/13 Air Compressor Intake Pipe", "P13连杆螺栓（14*1.5）": "P13 Connecting Rod Bolt (14*1.5)",
"空压机齿轮/28齿": "Air Compressor Gear / 28 Teeth", "扎带": "Cable Tie", "MC11/13机油尺": "MC11/13 Oil Dipstick",
"六角法兰带突齿螺栓": "Hex Flange Serrated Bolt", "六角法兰面带突齿螺栓": "Hex Flange Serrated Bolt",
"H10.5飞轮螺栓": "H10.5 Flywheel Bolt", "P13摇臂座": "P13 Rocker Seat", "ECU防护罩": "ECU Protective Cover",
"P12水泵垫片": "P12 Water Pump Gasket", "P10H油气分离器总成": "P10H Oil-Gas Separator Assembly",
"P13排气管": "P13 Exhaust Pipe", "φ282平卡": "φ282 Flat Clamp", "气路接头": "Air Line Joint",
"P7/P8支撑块": "P7/P8 Support Block", "10*28六角法兰面螺栓": "10*28 Hex Flange Bolt",
"H10汽缸垫": "H10 Cylinder Head Gasket", "WP13增压器双头螺栓": "WP13 Turbo Stud Bolt",
"MP13增压器双头螺栓": "MP13 Turbo Stud Bolt", "施必牢螺母": "Anti-Loosening Nut (SPILock)",
"H10空压机管接头（V21）": "H10 Air Compressor Pipe Joint (V21)", "H10压气机进气管": "H10 Compressor Intake Pipe",
"H10排气管（前）": "H10 Exhaust Pipe (Front)",
"单缸空压机（带节能系统）": "Single-Cylinder Air Compressor (with Energy Saving)",
"机油模块": "Oil Module", "惰轮总成": "Idler Pulley Assembly", "电控硅油风扇": "Electronically Controlled Viscous Fan",
"83-95度节温器芯": "83-95℃ Thermostat Element", "MC11缸盖组合件总成（带气门）": "MC11 Head Combination Assembly (with Valves)",
"M11气缸盖罩组件": "M11 Cylinder Head Cover Module", "冷却液弯管（MC11）": "Coolant Elbow Pipe (MC11)",
"(MC11)水泵密封垫": "(MC11) Water Pump Seal Gasket", "进气温度压力传感器": "Intake Temperature & Pressure Sensor",
"（MC11）分配壳密封垫": "(MC11) Distribution Housing Gasket", "吸油管O型圈（28*3）": "Suction Pipe O-Ring (28*3)",
"(MC11/13)油底壳垫": "(MC11/13) Oil Pan Gasket", "空压机冷却水管": "Air Compressor Cooling Water Pipe",
"(MC11)曲轴前油封": "(MC11) Crankshaft Front Oil Seal", "燃油压力传感器": "Fuel Pressure Sensor",
"(MC11/13)曲轴后油封": "(MC11/13) Crankshaft Rear Oil Seal", "机油模块密封垫": "Oil Module Gasket",
"角形法兰密封垫": "Angle Flange Gasket", "（MC11）涡轮出口垫片": "(MC11) Turbine Outlet Gasket",
"（MC11）前端盖密封垫": "(MC11) Front Cover Gasket", "（MC11）水管": "(MC11) Water Pipe",
"（MC11）油气分离器出气管总成": "(MC11) Oil-Gas Separator Outlet Pipe Assembly",
"MC11油气分离器回油接管": "MC11 Oil-Gas Separator Return Connection", "MC11活塞环组件": "MC11 Piston Ring Set",
"MC11油气分离器回油管": "MC11 Oil-Gas Separator Return Pipe", "MC11气缸套密封圈": "MC11 Cylinder Liner Seal Ring",
"MC11排气管垫片 三层": "MC11 Exhaust Gasket 3-Layer", "MC油底壳托快": "MC Oil Pan Support Block",
"角形法兰": "Angle Flange", "MC11中冷后进气管": "MC11 Post-Intercooler Intake Pipe",
"中排气管": "Middle Exhaust Pipe", "MC11飞轮壳": "MC11 Flywheel Housing", "进气弯管": "Intake Elbow Pipe",
"空压机冷却回水管": "Air Compressor Cooling Return Pipe", "分配壳": "Distribution Housing",
"冷却液管": "Coolant Pipe", "P7气门摇臂": "P7 Valve Rocker Arm", "P12喷油器压紧块": "P12 Injector Clamping Block",
"P13机油尺下组件": "P13 Dipstick Lower Module", "后驱力盖板": "Rear Drive Cover Plate",
"P8增压器隔热罩": "P8 Turbo Heat Shield", "P7机油尺下组件": "P7 Dipstick Lower Module",
"L10增压器进水管": "L10 Turbo Water Inlet Pipe", "P13国六增压器隔热罩": "P13 China-VI Turbo Heat Shield",
"TX国三全功能发动机线束总成": "TX China-III Full Engine Harness Assembly",
"冷却模块总成": "Cooling Module Assembly", "TX散热器出水胶管": "TX Radiator Outlet Rubber Hose",
"TX中冷器进气胶管": "TX Intercooler Inlet Rubber Hose", "TX中冷器出气胶管": "TX Intercooler Outlet Rubber Hose",
"TX冷却模块拉杆": "TX Cooling Module Tie Rod", "膨胀水箱总成": "Expansion Tank Assembly",
"TX发动机左后支撑": "TX Engine Left Rear Support", "TX发动机右后支撑": "TX Engine Right Rear Support",
"卡套式直通接头": "Ferrule Type Straight Joint", "10*30双头螺栓": "10*30 Stud Bolt",
"10*25双头螺栓": "10*25 Stud Bolt", "M12支撑块": "M12 Support Block", "机油冷却器垫片": "Oil Cooler Gasket",
"铝前橡胶支撑总成": "Aluminum-Front Rubber Mount Assembly", "DPF垫片275*300*1.8": "DPF Gasket 275*300*1.8",
"P7增压器双头螺栓": "P7 Turbo Stud Bolt", "M24*1.5薄螺母": "M24*1.5 Thin Nut",
"离合器液压油管": "Clutch Hydraulic Pipe", "左橡胶支撑": "Left Rubber Mount", "右橡胶支撑": "Right Rubber Mount",
"暖风驾驶室进水胶管": "Heater Cab Water Inlet Rubber Hose", "暖风驾驶室回水胶管": "Heater Cab Water Return Rubber Hose",
"双管夹（φ18）": "Double Pipe Clamp (φ18)", "暖风出水钢管": "Heater Water Outlet Steel Pipe",
"暖风发动机回水钢管": "Heater Engine Return Steel Pipe", "暖风水管支架": "Heater Water Pipe Bracket",
"H型减压阀": "H-Type Pressure Reducing Valve", "变速箱管夹": "Gearbox Pipe Clamp", "缓冲块": "Buffer Block",
"支撑杆总成": "Support Rod Assembly", "暖风减压阀出水胶管": "Heater PRV Outlet Rubber Hose",
"H10.5集滤器支架": "H10.5 Oil Strainer Bracket", "P8集滤器": "P8 Oil Strainer", "V型卡箍": "V-Band Clamp",
"P13排气制动支架": "P13 Exhaust Brake Bracket", "P13排气尾管支架": "P13 Exhaust Tail Pipe Bracket",
"P13线束支架": "P13 Harness Bracket", "P13NG支撑（缸盖罩）": "P13NG Support (Head Cover)",
"空压机胶管": "Air Compressor Rubber Hose", "曼11/13集滤器总成": "MAN 11/13 Oil Strainer Assembly",
"H10.5机油尺": "H10.5 Oil Dipstick", "P10H燃油管总成/输油泵-精滤器": "P10H Fuel Pipe / Feed Pump-Fine Filter",
"P12增压器回油管": "P12 Turbo Oil Return Pipe", "镀锌空心螺栓": "Galvanized Hollow Bolt",
"达克罗空心螺栓": "Dacromet Hollow Bolt", "φ10平垫圈": "φ10 Flat Washer", "10*60六角头螺栓": "10*60 Hex Head Bolt",
"10*25六角头螺栓": "10*25 Hex Head Bolt", "P13CNG增压器隔热罩": "P13 CNG Turbo Heat Shield",
"天然气滤芯": "Natural Gas Filter Element", "国V进气门座圈MT13": "China-V Intake Valve Seat MT13",
"国V排气门座圈MT13": "China-V Exhaust Valve Seat MT13", "进气门MT13": "Intake Valve MT13",
"排气门MT13": "Exhaust Valve MT13", "MT13国五气缸盖总成": "MT13 China-V Cylinder Head Assembly",
"P13国六排气管密封环": "P13 China-VI Exhaust Seal Ring", "H1摇臂座组件": "H1 Rocker Seat Module",
"原厂油底壳托快": "OEM Oil Pan Support Block", "L10燃油回油管总成": "L10 Fuel Return Pipe Assembly",
"D10空滤支架": "D10 Air Filter Bracket", "H10.5暖风接头": "H10.5 Heater Joint",
"进气摇臂组件": "Intake Rocker Module", "排气摇臂组件": "Exhaust Rocker Module",
"精滤-喷油泵燃油管总成": "Fine Filter-to-Injection Pump Fuel Pipe Assembly",
"燃油滤清器支架": "Fuel Filter Bracket", "H10空压机水管卡箍": "H10 Air Compressor Water Hose Clamp",
"P型管夹": "P-Type Pipe Clamp", "P8连杆瓦上瓦": "P8 Connecting Rod Upper Bearing",
"P8连杆瓦下瓦": "P8 Connecting Rod Lower Bearing", "P8阻水圈": "P8 Water Seal Ring",
"P8气缸套": "P8 Cylinder Liner", "P8活塞销": "P8 Piston Pin", "P8活塞": "P8 Piston",
"P8活塞环组件": "P8 Piston Ring Set", "P8汽缸垫": "P8 Cylinder Head Gasket",
"H10.5护风圈支架": "H10.5 Fan Shroud Bracket", "六角锁紧螺母(110040用)": "Hex Lock Nut (for 110040)",
"H10喷油器压板固定螺栓": "H10 Injector Plate Fixing Bolt", "H10/P7球面垫圈": "H10/P7 Spherical Washer",
"H10喷油器压板": "H10 Injector Press Plate", "耐热六角螺栓": "Heat-Resistant Hex Bolt",
"P13缸盖主螺栓": "P13 Head Main Bolt", "P13缸盖副螺栓": "P13 Head Auxiliary Bolt",
"P8机油尺下组件": "P8 Dipstick Lower Module", "空压机支架": "Air Compressor Bracket",
"H10空调压缩支架": "H10 AC Compressor Bracket", "带肩飞轮螺栓": "Shoulder Flywheel Bolt",
"精滤出油管": "Fine Filter Outlet Pipe", "18L齿轮油": "18L Gear Oil", "P8进气管垫": "P8 Intake Gasket",
"P8缸盖罩衬垫": "P8 Head Cover Gasket", "12*30双头螺栓": "12*30 Stud Bolt",
"柴油滤清器盖": "Diesel Filter Cover", "大卡环（拉式）6爪": "Large Circlip (Pull Type) 6-Claw",
"P13增压器双头螺栓": "P13 Turbo Stud Bolt", "P12(6305)飞轮轴承": "P12 (6305) Flywheel Bearing",
"EVB润滑油管总成": "EVB Lube Oil Pipe Assembly", "φ6空心螺栓": "φ6 Hollow Bolt",
"P8空压机密封圈": "P8 Air Compressor Seal Ring", "液压泵盖板": "Hydraulic Pump Cover Plate",
"EGR冷却出水管总成": "EGR Cooling Outlet Pipe Assembly", "P7/P8发动机支架": "P7/P8 Engine Mount Bracket",
"预分离器回油管": "Pre-Separator Return Pipe", "DPM进水管组件": "DPM Water Inlet Pipe Module",
"DPM回水管组件": "DPM Water Return Pipe Module", "EGR出气管总成": "EGR Outlet Pipe Assembly",
"MT13空压机回水管": "MT13 Air Compressor Return Water Pipe", "10.9六角法兰面螺栓": "Hex Flange Bolt Grade 10.9",
"（黑）增压器双头螺栓": "(Black) Turbo Stud Bolt", "P13进气门座": "P13 Intake Valve Seat",
"P13排气门座": "P13 Exhaust Valve Seat", "P13后驱力总成": "P13 Rear Drive Assembly",
"卡套式管接头用螺母": "Nut for Ferrule Type Joint", "锐动力机油滤芯": "Ruidongli Oil Filter Element",
"P10H机滤盖": "P10H Oil Filter Cover", "钢管总成（20空压机）": "Steel Pipe Assembly (20 Air Compressor)",
"WP13燃油回油管总成": "WP13 Fuel Return Pipe Assembly", "H09/10飞轮壳法兰面螺栓": "H09/10 Flywheel Housing Flange Bolt",
"D10涨紧轮螺丝（四孔）": "D10 Tensioner Screw (4-Hole)", "铰接式管接头体": "Articulated Joint Body",
"12升火花塞衬套": "12L Spark Plug Bushing", "原装P12曲轴后油封": "Genuine P12 Crankshaft Rear Oil Seal",
"H10气缸套": "H10 Cylinder Liner", "0756冷盖法兰": "0756 Coolant Cover Flange",
"0756冷盖法兰垫片": "0756 Coolant Cover Flange Gasket", "0756冷盖管接头": "0756 Coolant Cover Pipe Joint",
"P13集滤器支架": "P13 Oil Strainer Bracket", "14*50带肩飞轮螺栓": "14*50 Shoulder Flywheel Bolt",
"P10H机油尺": "P10H Oil Dipstick", "装机曲轴前油封": "Assembly Crankshaft Front Oil Seal",
"M10组合密封垫圈": "M10 Combined Seal Washer", "M16组合密封垫圈": "M16 Combined Seal Washer",
"组合密封垫圈": "Combined Seal Washer", "风扇罩总成": "Fan Shroud Assembly",
"原厂样件机油尺管总成": "OEM Sample Dipstick Tube Assembly", "P10H气门室盖": "P10H Valve Chamber Cover",
"WP10H曲轴总成": "WP10H Crankshaft Assembly", "L级连杆总成": "L-Grade Connecting Rod Assembly",
"WP10H主轴瓦": "WP10H Main Bearing", "WP10H连杆瓦": "WP10H Connecting Rod Bearing",
"WP10H全车垫": "WP10H Complete Gasket Kit", "WP10H机油滤芯": "WP10H Oil Filter Element",
"WP10H心组件": "WP10H Core Module", "EGR出气胶管": "EGR Outlet Rubber Hose",
"WP13气路连接胶管": "WP13 Air Line Rubber Hose", "装机主轴瓦": "Assembly Main Bearing",
"WP17空压机润滑油管": "WP17 Air Compressor Lube Oil Pipe", "P12空压机进水管": "P12 Air Compressor Water Inlet Pipe",
"P12空压机进水管总成": "P12 Air Compressor Water Inlet Pipe Assembly",
"P12空压机回水管总成": "P12 Air Compressor Return Water Pipe Assembly",
"D12空压机润滑油管": "D12 Air Compressor Lube Oil Pipe", "M26复合垫片": "M26 Composite Washer",
"后驱力润滑油管": "Rear Drive Lube Oil Pipe", "P7水泵垫": "P7 Water Pump Gasket",
"P13EGR水管接头": "P13 EGR Water Pipe Joint", "H10空压机管接头": "H10 Air Compressor Pipe Joint",
"H10.5空压机出气接头": "H10.5 Air Compressor Air Outlet Joint", "D10G增压器进油管": "D10G Turbo Oil Feed Pipe",
"D10增压器进油管总成": "D10 Turbo Oil Feed Pipe Assembly", "柴机油（18L）": "Diesel Engine Oil (18L)",
"D12空压机进水管总成": "D12 Air Compressor Water Inlet Pipe Assembly",
"D12空压机进水管接头": "D12 Air Compressor Water Inlet Joint", "T7机油尺（154.5）": "T7 Oil Dipstick (154.5)",
"MC07机油尺套管总成": "MC07 Dipstick Sleeve Assembly", "D12双级机油泵吸管": "D12 Two-Stage Oil Pump Suction Pipe",
"D12集滤器": "D12 Oil Strainer", "D12喷油器压紧块": "D12 Injector Clamping Block",
"P8后驱力盖密封圈": "P8 Rear Drive Cover Seal Ring", "V型沟槽卡箍φ104": "V-Groove Clamp φ104",
"P8液压泵支架": "P8 Hydraulic Pump Bracket", "D12粗滤固定支架": "D12 Primary Filter Fixing Bracket",
"D12精滤固定支架": "D12 Fine Filter Fixing Bracket", "D12机油加油管座": "D12 Oil Fill Pipe Seat",
"P8垫片": "P8 Washer", "机油模块改装修理包": "Oil Module Modification Repair Kit",
"空压机进水管总成": "Air Compressor Water Inlet Pipe Assembly", "L10喷油器回油管": "L10 Injector Return Pipe",
"H10.5机油喷嘴总成": "H10.5 Oil Nozzle Assembly", "H10.5空压机气管接头": "H10.5 Air Compressor Air Pipe Joint",
"连杆瓦（B504）": "Connecting Rod Bearing (B504)", "D12共轨组件回油管": "D12 Common Rail Module Return Pipe",
"D12共轨油泵机油进油管总成": "D12 Common Rail Pump Oil Inlet Pipe Assembly",
"D12共轨喷油泵回油管": "D12 Common Rail Injection Pump Return Pipe",
"2064机油尺套管": "2064 Dipstick Sleeve", "空压机进水管组件": "Air Compressor Water Inlet Pipe Module",
"混合器支架": "Mixer Bracket", "MT曼机油": "MT MAN Engine Oil", "汽缸盖总成": "Cylinder Head Assembly",
"WP12喷油泵法兰": "WP12 Injection Pump Flange", "进气门挺住": "Intake Valve Tappet",
"H10气门导管": "H10 Valve Guide", "M18复合垫片": "M18 Composite Washer", "M10复合垫片": "M10 Composite Washer",
"M6复合垫片": "M6 Composite Washer", "M8复合垫片": "M8 Composite Washer", "M20复合垫片": "M20 Composite Washer",
"M16复合垫片": "M16 Composite Washer", "M12复合垫片": "M12 Composite Washer", "192309轴承": "192309 Bearing",
"P13支撑块（燃油滤清器）": "P13 Support Block (Fuel Filter)", "WP13齿轮润滑油管总成": "WP13 Gear Lube Oil Pipe Assembly",
"EGR冷却水管": "EGR Cooling Water Pipe", "铰链式管接头体": "Hinge Type Joint Body",
"P8水管接头": "P8 Water Pipe Joint", "WP13增压器回油管总成": "WP13 Turbo Oil Return Pipe Assembly",
"P13NG增压器进油管": "P13NG Turbo Oil Feed Pipe", "H10NG增压器回油管": "H10NG Turbo Oil Return Pipe",
"H10NG增压器进油管": "H10NG Turbo Oil Feed Pipe", "曼增压器回油管": "MAN Turbo Oil Return Pipe",
"14*75飞轮螺栓": "14*75 Flywheel Bolt", "后驱力总成": "Rear Drive Assembly",
"WP13空压机水管": "WP13 Air Compressor Water Pipe", "H10增压器隔热罩": "H10 Turbo Heat Shield",
"P8支撑快": "P8 Support Block", "D12增压器进油管": "D12 Turbo Oil Feed Pipe",
"D12增压器回油管": "D12 Turbo Oil Return Pipe", "P12喷油器垫片": "P12 Injector Gasket",
"P13NG油气分离器进气管": "P13NG Oil-Gas Separator Intake Pipe", "出水管接管垫片": "Water Outlet Connection Gasket",
"P13排气管螺栓": "P13 Exhaust Pipe Bolt", "P13隔热罩螺栓": "P13 Heat Shield Bolt",
"燃油回油管总成(10.5)": "Fuel Return Pipe Assembly (10.5)", "燃油进油管（H10.5）": "Fuel Feed Pipe (H10.5)",
"H10.5增压器进油管总成": "H10.5 Turbo Oil Feed Pipe Assembly", "排气接管": "Exhaust Connection Pipe",
"P8机油模块支撑快": "P8 Oil Module Support Block", "M14空心螺栓": "M14 Hollow Bolt",
"原厂机油尺套管总成": "OEM Dipstick Sleeve Assembly", "H10出水管盖板": "H10 Water Outlet Cover Plate",
"P8机油冷却器盖板": "P8 Oil Cooler Cover Plate", "P12/13增压器进油管": "P12/13 Turbo Oil Feed Pipe",
"P13发动机前支架": "P13 Engine Front Bracket", "P13油气分离器胶管": "P13 Oil-Gas Separator Rubber Hose",
"P12/13增压器隔热罩": "P12/13 Turbo Heat Shield", "L10护风圈支架": "L10 Fan Shroud Bracket",
"燃油进油管": "Fuel Feed Pipe", "P7燃油进油管": "P7 Fuel Feed Pipe", "P8机油滤清器盖": "P8 Oil Filter Cover",
"P6机油喷嘴密封圈": "P6 Oil Nozzle Seal Ring", "销(电装压紧块下)": "Pin (under Injector Clamping Block)",
"中置增压器回油管": "Mid-Mounted Turbo Oil Return Pipe", "中置增压器进油管": "Mid-Mounted Turbo Oil Feed Pipe",
"H10.5阻水圈（蓝色）": "H10.5 Water Seal Ring (Blue)", "H10.5阻水圈（红色）": "H10.5 Water Seal Ring (Red)",
"H10.5阻水圈（黑）": "H10.5 Water Seal Ring (Black)", "废气旁通阀出气管": "Waste Gate Outlet Pipe",
"119.5机油尺套管": "119.5 Dipstick Sleeve", "正时齿轮室": "Timing Gear Housing",
"带肩空心螺栓": "Shoulder Hollow Bolt", "快插接头体": "Quick Plug Joint Body",
"EGR阀水管总成": "EGR Valve Water Pipe Assembly", "ERG冷却水管": "EGR Cooling Water Pipe",
"P7管接头组件": "P7 Pipe Joint Assembly", "（Z镀铜）双头螺栓": "(Z Copper-Plated) Stud Bolt",
"点火线圈衬套压板": "Ignition Coil Bushing Plate", "P7气门油封": "P7 Valve Stem Seal",
"P7缸盖螺座": "P7 Head Threaded Seat", "P7排气门座圈": "P7 Exhaust Valve Seat",
"进气门座圈": "Intake Valve Seat", "P7缸盖罩六角头螺栓": "P7 Head Cover Hex Bolt",
"支撑快（P7缸盖罩）": "Support Block (P7 Head Cover)", "风扇离合器(装机)": "Fan Clutch (Assembly Line)",
"风扇离合器（装机）": "Fan Clutch (Assembly Line)", "10175盖板垫片": "10175 Cover Plate Gasket",
"P10H曲轴前后油封（一套）": "P10H Crankshaft Oil Seal Set", "615气门弹簧": "615 Valve Spring",
"P13油底壳垫": "P13 Oil Pan Gasket", "P13机油冷却器盖总成": "P13 Oil Cooler Cover Assembly",
"D10齿轮室前端盖": "D10 Gear Housing Front Cover", "工程机械柴滤支架": "Machinery Diesel Filter Bracket",
"水封": "Water Seal", "P7增压器方垫": "P7 Turbo Square Gasket", "M10自锁垫片": "M10 Self-Locking Washer",
"发动机垫片修理包": "Engine Gasket Repair Kit", "加机油管垫片": "Oil Fill Pipe Gasket",
"H10排气管垫": "H10 Exhaust Gasket", "连杆瓦（V777.6）": "Connecting Rod Bearing (V777.6)",
"P7连杆总成": "P7 Connecting Rod Assembly", "P7缸盖罩（天然气）": "P7 Head Cover (Natural Gas)",
"P7气缸套": "P7 Cylinder Liner", "P7活塞": "P7 Piston", "P7活塞环装机": "P7 Piston Ring (Assembly Line)",
"P7活塞销": "P7 Piston Pin", "P6连杆总成（涨段）": "P6 Connecting Rod Assembly (Stretch Section)",
"P7汽缸盖分总成": "P7 Cylinder Head Sub-Assembly", "P13冷却液连接胶管": "P13 Coolant Rubber Hose",
"P7活塞（装机）": "P7 Piston (Assembly Line)", "P12加紧块": "P12 Clamping Block",
"燃油滤清器（无手油泵升级滤芯）": "Fuel Filter (Upgrade Element without Hand Pump)",
"燃油滤总成": "Fuel Filter Assembly", "P7节温器芯": "P7 Thermostat Element",
"12*50联轴器螺栓": "12*50 Coupling Bolt", "12*35联轴器螺栓": "12*35 Coupling Bolt",
"卡箍21-43": "Hose Clamp 21-43", "P10H.5气路连接胶管": "P10H.5 Air Line Rubber Hose",
"P13EGR冷却液胶管": "P13 EGR Coolant Rubber Hose", "P13油气分离器隔热罩": "P13 Oil-Gas Separator Heat Shield",
"P13油气分离器润滑油管": "P13 Oil-Gas Separator Lube Oil Pipe",
"P13油气分离器出气管总成": "P13 Oil-Gas Separator Outlet Pipe Assembly",
"P13油气分离器": "P13 Oil-Gas Separator", "618冷却液连接胶管": "618 Coolant Rubber Hose",
"低压油管管接头": "Low Pressure Fuel Pipe Joint", "0302中冷器管": "0302 Intercooler Pipe",
"P13油气分离器管接头": "P13 Oil-Gas Separator Pipe Joint", "P13冷却器连接胶管": "P13 Cooler Connecting Rubber Hose",
"P8增压器进油管": "P8 Turbo Oil Feed Pipe", "P8增压器回油管总成": "P8 Turbo Oil Return Pipe Assembly",
"机油压力传感器接头": "Oil Pressure Sensor Joint", "P13G后取利总成": "P13G Rear PTO Assembly",
"P13后取利总成": "P13 Rear PTO Assembly", "H10模块支撑快": "H10 Module Support Block",
"P13柴滤支架": "P13 Diesel Filter Bracket", "H10.5缸体接头": "H10.5 Cylinder Block Joint",
"H10水泵接头": "H10 Water Pump Joint", "P7EVB排气门桥总成": "P7 EVB Exhaust Valve Bridge Assembly",
"P7EVB支架": "P7 EVB Bracket", "P13油气分离器出气胶管": "P13 Oil-Gas Separator Outlet Rubber Hose",
"H10出水管管接头": "H10 Water Outlet Pipe Joint", "管夹总成(96830管)": "Pipe Clamp Assembly (96830 Pipe)",
"P13EGR支架": "P13 EGR Bracket", "P13汽化路管接头": "P13 Vaporizing Line Joint",
"P7水管接头": "P7 Water Pipe Joint", "P13EGR冷却器支架": "P13 EGR Cooler Bracket",
"P12/13水泵接头": "P12/13 Water Pump Joint", "H10.5水管接头": "H10.5 Water Pipe Joint",
"DPM进水管组件（P10H/国六）": "DPM Water Inlet Pipe Module (P10H/China-VI)",
"DPM回水管组件（P10H/国六）": "DPM Water Return Pipe Module (P10H/China-VI)",
"P7油底壳": "P7 Oil Pan", "H10空压机垫片": "H10 Air Compressor Gasket", "P13卡箍": "P13 Hose Clamp",
}
